//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IAcOtherShouldCollectionAccessor.autogenerated.cs
// author: mayanjun
// create date：2011-6-10 11:24:11
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IAcOtherShouldCollectionAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.AcOtherShouldCollection Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.AcOtherShouldCollection e);
		
		void Update(Model.AcOtherShouldCollection e);
		
		IList<Model.AcOtherShouldCollection> Select();
		
		IList<Model.AcOtherShouldCollection> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.AcOtherShouldCollection e);
		
		bool HasRowsAfter(Model.AcOtherShouldCollection e);
		
		Model.AcOtherShouldCollection GetFirst();
		
		Model.AcOtherShouldCollection GetLast();
		
		Model.AcOtherShouldCollection GetPrev(Model.AcOtherShouldCollection e);
		
		Model.AcOtherShouldCollection GetNext(Model.AcOtherShouldCollection e);

	}
}

