//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IAssemblySiteDifferenceDetaiAccessor.autogenerated.cs
// author: mayanjun
// create date：2018-05-14 19:16:31
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IAssemblySiteDifferenceDetaiAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.AssemblySiteDifferenceDetai Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.AssemblySiteDifferenceDetai e);
		
		void Update(Model.AssemblySiteDifferenceDetai e);
		
		IList<Model.AssemblySiteDifferenceDetai> Select();
		
		IList<Model.AssemblySiteDifferenceDetai> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}
