//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IBGHandbookDepotOutDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2014/3/5 16:32:46
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IBGHandbookDepotOutDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.BGHandbookDepotOutDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.BGHandbookDepotOutDetail e);
		
		void Update(Model.BGHandbookDepotOutDetail e);
		
		IList<Model.BGHandbookDepotOutDetail> Select();
		
		IList<Model.BGHandbookDepotOutDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}

