//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ICompanyLevelAccessor.autogenerated.cs
// author: peidun
// create date：2009-10-13 下午 05:12:51
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface ICompanyLevelAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.CompanyLevel Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.CompanyLevel e);
		
		void Update(Model.CompanyLevel e);
		
		IList<Model.CompanyLevel> Select();
		
		IList<Model.CompanyLevel> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		bool HasRowsBefore(Model.CompanyLevel e);
		
		bool HasRowsAfter(Model.CompanyLevel e);
		
		Model.CompanyLevel GetFirst();
		
		Model.CompanyLevel GetLast();
		
		Model.CompanyLevel GetPrev(Model.CompanyLevel e);
		
		Model.CompanyLevel GetNext(Model.CompanyLevel e);

	}
}

