//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCEarPressCheckAccessor.autogenerated.cs
// author: mayanjun
// create date：2013-08-23 16:50:38
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCEarPressCheckAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCEarPressCheck Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCEarPressCheck e);
		
		void Update(Model.PCEarPressCheck e);
		
		IList<Model.PCEarPressCheck> Select();
		
		IList<Model.PCEarPressCheck> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.PCEarPressCheck e);
		
		bool HasRowsAfter(Model.PCEarPressCheck e);
		
		Model.PCEarPressCheck GetFirst();
		
		Model.PCEarPressCheck GetLast();
		
		Model.PCEarPressCheck GetPrev(Model.PCEarPressCheck e);
		
		Model.PCEarPressCheck GetNext(Model.PCEarPressCheck e);


    }
}

