//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCExportReportANSIDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2012-6-13 14:02:25
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCExportReportANSIDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCExportReportANSIDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCExportReportANSIDetail e);
		
		void Update(Model.PCExportReportANSIDetail e);
		
		IList<Model.PCExportReportANSIDetail> Select();
		
		IList<Model.PCExportReportANSIDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.PCExportReportANSIDetail e);
		
		bool HasRowsAfter(Model.PCExportReportANSIDetail e);
		
		Model.PCExportReportANSIDetail GetFirst();
		
		Model.PCExportReportANSIDetail GetLast();
		
		Model.PCExportReportANSIDetail GetPrev(Model.PCExportReportANSIDetail e);
		
		Model.PCExportReportANSIDetail GetNext(Model.PCExportReportANSIDetail e);

	}
}

