//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPersonworkAccessor.autogenerated.cs
// author: peidun
// create date：2009-11-26 15:16:39
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPersonworkAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.Personwork Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.Personwork e);
		
		void Update(Model.Personwork e);
		
		IList<Model.Personwork> Select();
		
		IList<Model.Personwork> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);

	}
}

