//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ISalesForHeaderAccessor.autogenerated.cs
// author: peidun
// create date：2009-12-18 11:23:45
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface ISalesForHeaderAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.SalesForHeader Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.SalesForHeader e);
		
		void Update(Model.SalesForHeader e);
		
		IList<Model.SalesForHeader> Select();
		
		IList<Model.SalesForHeader> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		bool HasRowsBefore(Model.SalesForHeader e);
		
		bool HasRowsAfter(Model.SalesForHeader e);
		
		Model.SalesForHeader GetFirst();
		
		Model.SalesForHeader GetLast();
		
		Model.SalesForHeader GetPrev(Model.SalesForHeader e);
		
		Model.SalesForHeader GetNext(Model.SalesForHeader e);

		bool Exists(string id);
		
		Model.SalesForHeader GetById(string id);
		
		bool ExistsExcept(Model.SalesForHeader e);
	}
}

