//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IThicknessTestDetailsAccessor.autogenerated.cs
// author: mayanjun
// create date：2012-4-24 10:33:13
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IThicknessTestDetailsAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.ThicknessTestDetails Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.ThicknessTestDetails e);
		
		void Update(Model.ThicknessTestDetails e);
		
		IList<Model.ThicknessTestDetails> Select();
		
		IList<Model.ThicknessTestDetails> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}

