//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IXP1Accessor.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:03
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IXP1Accessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.XP1 Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.XP1 e);
		
		void Update(Model.XP1 e);
		
		IList<Model.XP1> Select();
		
		IList<Model.XP1> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);

	}
}

