//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IAtAccountingCategoryAccessor.autogenerated.cs
// author: mayanjun
// create date：2011-3-3 14:30:19
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IAtAccountingCategoryAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.AtAccountingCategory Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.AtAccountingCategory e);
		
		void Update(Model.AtAccountingCategory e);
		
		IList<Model.AtAccountingCategory> Select();
		
		IList<Model.AtAccountingCategory> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.AtAccountingCategory e);
		
		bool HasRowsAfter(Model.AtAccountingCategory e);
		
		Model.AtAccountingCategory GetFirst();
		
		Model.AtAccountingCategory GetLast();
		
		Model.AtAccountingCategory GetPrev(Model.AtAccountingCategory e);
		
		Model.AtAccountingCategory GetNext(Model.AtAccountingCategory e);

		bool Exists(string id);
		
		Model.AtAccountingCategory GetById(string id);
		
		bool ExistsExcept(Model.AtAccountingCategory e);
		
	}
}

