//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IAtBankSaveUpAccessor.autogenerated.cs
// author: mayanjun
// create date：2011-3-3 14:30:19
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IAtBankSaveUpAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.AtBankSaveUp Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.AtBankSaveUp e);
		
		void Update(Model.AtBankSaveUp e);
		
		IList<Model.AtBankSaveUp> Select();
		
		IList<Model.AtBankSaveUp> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.AtBankSaveUp e);
		
		bool HasRowsAfter(Model.AtBankSaveUp e);
		
		Model.AtBankSaveUp GetFirst();
		
		Model.AtBankSaveUp GetLast();
		
		Model.AtBankSaveUp GetPrev(Model.AtBankSaveUp e);
		
		Model.AtBankSaveUp GetNext(Model.AtBankSaveUp e);

		bool Exists(string id);
		
		Model.AtBankSaveUp GetById(string id);
		
		bool ExistsExcept(Model.AtBankSaveUp e);
		
	}
}

