//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IAtDepreciationDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2011-3-3 14:30:19
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IAtDepreciationDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.AtDepreciationDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.AtDepreciationDetail e);
		
		void Update(Model.AtDepreciationDetail e);
		
		IList<Model.AtDepreciationDetail> Select();
		
		IList<Model.AtDepreciationDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.AtDepreciationDetail e);
		
		bool HasRowsAfter(Model.AtDepreciationDetail e);
		
		Model.AtDepreciationDetail GetFirst();
		
		Model.AtDepreciationDetail GetLast();
		
		Model.AtDepreciationDetail GetPrev(Model.AtDepreciationDetail e);
		
		Model.AtDepreciationDetail GetNext(Model.AtDepreciationDetail e);

		bool Exists(string id);
		
		Model.AtDepreciationDetail GetById(string id);
		
		bool ExistsExcept(Model.AtDepreciationDetail e);
		
	}
}

