//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IBOMProductProcessAccessor.autogenerated.cs
// author: peidun
// create date：2009-11-14 9:57:09
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IBOMProductProcessAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.BOMProductProcess Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.BOMProductProcess e);
		
		void Update(Model.BOMProductProcess e);
		
		IList<Model.BOMProductProcess> Select();
		
		IList<Model.BOMProductProcess> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);

	}
}

