//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IFreightedCompanyAccessor.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:02
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IFreightedCompanyAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.FreightedCompany Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.FreightedCompany e);
		
		void Update(Model.FreightedCompany e);
		
		IList<Model.FreightedCompany> Select();
		
		IList<Model.FreightedCompany> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		bool HasRowsBefore(Model.FreightedCompany e);
		
		bool HasRowsAfter(Model.FreightedCompany e);
		
		Model.FreightedCompany GetFirst();
		
		Model.FreightedCompany GetLast();
		
		Model.FreightedCompany GetPrev(Model.FreightedCompany e);
		
		Model.FreightedCompany GetNext(Model.FreightedCompany e);

		bool Exists(string id);
		
		Model.FreightedCompany GetById(string id);
		
		bool ExistsExcept(Model.FreightedCompany e);
	}
}

