//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IInvoiceCTAccessor.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:02
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IInvoiceCTAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.InvoiceCT Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.InvoiceCT e);
		
		void Update(Model.InvoiceCT e);
		
		IList<Model.InvoiceCT> Select();
		
		IList<Model.InvoiceCT> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		bool HasRowsBefore(Model.InvoiceCT e);
		
		bool HasRowsAfter(Model.InvoiceCT e);
		
		Model.InvoiceCT GetFirst();
		
		Model.InvoiceCT GetLast();
		
		Model.InvoiceCT GetPrev(Model.InvoiceCT e);
		
		Model.InvoiceCT GetNext(Model.InvoiceCT e);

	}
}

