//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IProduceStatisticsCheckDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2011-07-22 10:44:51
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IProduceStatisticsCheckDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.ProduceStatisticsCheckDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.ProduceStatisticsCheckDetail e);
		
		void Update(Model.ProduceStatisticsCheckDetail e);
		
		IList<Model.ProduceStatisticsCheckDetail> Select();
		
		IList<Model.ProduceStatisticsCheckDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.ProduceStatisticsCheckDetail e);
		
		bool HasRowsAfter(Model.ProduceStatisticsCheckDetail e);
		
		Model.ProduceStatisticsCheckDetail GetFirst();
		
		Model.ProduceStatisticsCheckDetail GetLast();
		
		Model.ProduceStatisticsCheckDetail GetPrev(Model.ProduceStatisticsCheckDetail e);
		
		Model.ProduceStatisticsCheckDetail GetNext(Model.ProduceStatisticsCheckDetail e);

	}
}

