//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IProductUnitAccessor.autogenerated.cs
// author: peidun
// create date：2010-4-19 11:18:38
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IProductUnitAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.ProductUnit Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.ProductUnit e);
		
		void Update(Model.ProductUnit e);
		
		IList<Model.ProductUnit> Select();
		
		IList<Model.ProductUnit> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.ProductUnit e);
		
		bool HasRowsAfter(Model.ProductUnit e);
		
		Model.ProductUnit GetFirst();
		
		Model.ProductUnit GetLast();
		
		Model.ProductUnit GetPrev(Model.ProductUnit e);
		
		Model.ProductUnit GetNext(Model.ProductUnit e);

		bool Exists(string id);
		
		Model.ProductUnit GetById(string id);
		
		bool ExistsExcept(Model.ProductUnit e);
		
	}
}

