//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IProduceOtherCompactDetailAccessor.autogenerated.cs
// author: peidun
// create date：2010-1-4 15:32:38
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IProduceOtherCompactDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.ProduceOtherCompactDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.ProduceOtherCompactDetail e);
		
		void Update(Model.ProduceOtherCompactDetail e);
		
		IList<Model.ProduceOtherCompactDetail> Select();
		
		IList<Model.ProduceOtherCompactDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);

	}
}

