//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：AcInvoiceCOBillAccessor.autogenerated.cs
// author: mayanjun
// create date：2011-06-27 15:08:17
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class AcInvoiceCOBillAccessor
    {
		public Model.AcInvoiceCOBill Get(string id)
		{
			return this.Get<Model.AcInvoiceCOBill>(id);
		}
		
		public void Insert(Model.AcInvoiceCOBill e)
		{
			this.Insert<Model.AcInvoiceCOBill>(e);
		}
		
		public void Update(Model.AcInvoiceCOBill e)
		{
			this.Update<Model.AcInvoiceCOBill>(e);
		}
		
		public IList<Model.AcInvoiceCOBill> Select()
		{
			return this.Select<Model.AcInvoiceCOBill>();
		}
		
		public IList<Model.AcInvoiceCOBill> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.AcInvoiceCOBill>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.AcInvoiceCOBill>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.AcInvoiceCOBill>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.AcInvoiceCOBill>();
		}
		public int Count()
		{
			return this.Count<Model.AcInvoiceCOBill>();
		}
		public bool HasRowsBefore(Model.AcInvoiceCOBill e)
		{
			return sqlmapper.QueryForObject<bool>("AcInvoiceCOBill.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.AcInvoiceCOBill e)
		{
			return sqlmapper.QueryForObject<bool>("AcInvoiceCOBill.has_rows_after", e);
		}
		public Model.AcInvoiceCOBill GetFirst()
		{
			return sqlmapper.QueryForObject<Model.AcInvoiceCOBill>("AcInvoiceCOBill.get_first", null);
		}
		public Model.AcInvoiceCOBill GetLast()
		{
			return sqlmapper.QueryForObject<Model.AcInvoiceCOBill>("AcInvoiceCOBill.get_last", null);
		}
		public Model.AcInvoiceCOBill GetNext(Model.AcInvoiceCOBill e)
		{
			return sqlmapper.QueryForObject<Model.AcInvoiceCOBill>("AcInvoiceCOBill.get_next", e);
		}
		public Model.AcInvoiceCOBill GetPrev(Model.AcInvoiceCOBill e)
		{
			return sqlmapper.QueryForObject<Model.AcInvoiceCOBill>("AcInvoiceCOBill.get_prev", e);
		}
		

		public bool Exists(string id)
		{
			return sqlmapper.QueryForObject<bool>("AcInvoiceCOBill.exists", id);
		}
		
		public Model.AcInvoiceCOBill GetById(string id)
		{
			return sqlmapper.QueryForObject<Model.AcInvoiceCOBill>("AcInvoiceCOBill.get_by_id", id);
		}
		
		public bool ExistsExcept(Model.AcInvoiceCOBill e)
		{
			Hashtable paras = new Hashtable();
			paras.Add("newId", e.Id);
            paras.Add("oldId", Get(e.AcInvoiceCOBillId)==null?null:Get(e.AcInvoiceCOBillId).Id);
			return sqlmapper.QueryForObject<bool>("AcInvoiceCOBill.existsexcept", paras);
		}		
		
		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("AcInvoiceCOBill.existsPrimary", id);
		}
  
    }
}
