//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：AcPaymentDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2011-6-23 09:29:21
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class AcPaymentDetailAccessor
    {
		public Model.AcPaymentDetail Get(string id)
		{
			return this.Get<Model.AcPaymentDetail>(id);
		}
		
		public void Insert(Model.AcPaymentDetail e)
		{
			this.Insert<Model.AcPaymentDetail>(e);
		}
		
		public void Update(Model.AcPaymentDetail e)
		{
			this.Update<Model.AcPaymentDetail>(e);
		}
		
		public IList<Model.AcPaymentDetail> Select()
		{
			return this.Select<Model.AcPaymentDetail>();
		}
		
		public IList<Model.AcPaymentDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.AcPaymentDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.AcPaymentDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.AcPaymentDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.AcPaymentDetail>();
		}
		public int Count()
		{
			return this.Count<Model.AcPaymentDetail>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("AcPaymentDetail.existsPrimary", id);
		}
    }
}
