//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：BGHandbookDepotOutAccessor.autogenerated.cs
// author: mayanjun
// create date：2014/3/5 16:32:46
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class BGHandbookDepotOutAccessor
    {
		public Model.BGHandbookDepotOut Get(string id)
		{
			return this.Get<Model.BGHandbookDepotOut>(id);
		}
		
		public void Insert(Model.BGHandbookDepotOut e)
		{
			this.Insert<Model.BGHandbookDepotOut>(e);
		}
		
		public void Update(Model.BGHandbookDepotOut e)
		{
			this.Update<Model.BGHandbookDepotOut>(e);
		}
		
		public IList<Model.BGHandbookDepotOut> Select()
		{
			return this.Select<Model.BGHandbookDepotOut>();
		}
		
		public IList<Model.BGHandbookDepotOut> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.BGHandbookDepotOut>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.BGHandbookDepotOut>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.BGHandbookDepotOut>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.BGHandbookDepotOut>();
		}
		public int Count()
		{
			return this.Count<Model.BGHandbookDepotOut>();
		}
		public bool HasRowsBefore(Model.BGHandbookDepotOut e)
		{
			return sqlmapper.QueryForObject<bool>("BGHandbookDepotOut.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.BGHandbookDepotOut e)
		{
			return sqlmapper.QueryForObject<bool>("BGHandbookDepotOut.has_rows_after", e);
		}
		public Model.BGHandbookDepotOut GetFirst()
		{
			return sqlmapper.QueryForObject<Model.BGHandbookDepotOut>("BGHandbookDepotOut.get_first", null);
		}
		public Model.BGHandbookDepotOut GetLast()
		{
			return sqlmapper.QueryForObject<Model.BGHandbookDepotOut>("BGHandbookDepotOut.get_last", null);
		}
		public Model.BGHandbookDepotOut GetNext(Model.BGHandbookDepotOut e)
		{
			return sqlmapper.QueryForObject<Model.BGHandbookDepotOut>("BGHandbookDepotOut.get_next", e);
		}
		public Model.BGHandbookDepotOut GetPrev(Model.BGHandbookDepotOut e)
		{
			return sqlmapper.QueryForObject<Model.BGHandbookDepotOut>("BGHandbookDepotOut.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("BGHandbookDepotOut.existsPrimary", id);
		}
    }
}
