//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：CustomerMarksAccessor.autogenerated.cs
// author: mayanjun
// create date：2013-5-8 13:43:44
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class CustomerMarksAccessor
    {
		public Model.CustomerMarks Get(string id)
		{
			return this.Get<Model.CustomerMarks>(id);
		}
		
		public void Insert(Model.CustomerMarks e)
		{
			this.Insert<Model.CustomerMarks>(e);
		}
		
		public void Update(Model.CustomerMarks e)
		{
			this.Update<Model.CustomerMarks>(e);
		}
		
		public IList<Model.CustomerMarks> Select()
		{
			return this.Select<Model.CustomerMarks>();
		}
		
		public IList<Model.CustomerMarks> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.CustomerMarks>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.CustomerMarks>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.CustomerMarks>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.CustomerMarks>();
		}
		public int Count()
		{
			return this.Count<Model.CustomerMarks>();
		}

		public bool Exists(string id)
		{
			return sqlmapper.QueryForObject<bool>("CustomerMarks.exists", id);
		}
		
		public Model.CustomerMarks GetById(string id)
		{
			return sqlmapper.QueryForObject<Model.CustomerMarks>("CustomerMarks.get_by_id", id);
		}
		
		public bool ExistsExcept(Model.CustomerMarks e)
		{
			Hashtable paras = new Hashtable();
			paras.Add("newId", e.Id);
            paras.Add("oldId", Get(e.CustomerMarksId)==null?null:Get(e.CustomerMarksId).Id);
			return sqlmapper.QueryForObject<bool>("CustomerMarks.existsexcept", paras);
		}
		
		
		
		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("CustomerMarks.existsPrimary", id);
		}
    }
}
