//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：DepotAccessor.autogenerated.cs
// author: peidun
// create date：2010-4-22 11:01:39
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class DepotAccessor
    {
		public Model.Depot Get(string id)
		{
			return this.Get<Model.Depot>(id);
		}
		
		public void Insert(Model.Depot e)
		{
			this.Insert<Model.Depot>(e);
		}
		
		public void Update(Model.Depot e)
		{
			this.Update<Model.Depot>(e);
		}
		
		public IList<Model.Depot> Select()
		{
			return this.Select<Model.Depot>();
		}
		
		public IList<Model.Depot> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.Depot>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.Depot>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.Depot>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.Depot>();
		}
		public int Count()
		{
			return this.Count<Model.Depot>();
		}
		public bool HasRowsBefore(Model.Depot e)
		{
			return sqlmapper.QueryForObject<bool>("Depot.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.Depot e)
		{
			return sqlmapper.QueryForObject<bool>("Depot.has_rows_after", e);
		}
		public Model.Depot GetFirst()
		{
			return sqlmapper.QueryForObject<Model.Depot>("Depot.get_first", null);
		}
		public Model.Depot GetLast()
		{
			return sqlmapper.QueryForObject<Model.Depot>("Depot.get_last", null);
		}
		public Model.Depot GetNext(Model.Depot e)
		{
			return sqlmapper.QueryForObject<Model.Depot>("Depot.get_next", e);
		}
		public Model.Depot GetPrev(Model.Depot e)
		{
			return sqlmapper.QueryForObject<Model.Depot>("Depot.get_prev", e);
		}
		

		public bool Exists(string id)
		{
			return sqlmapper.QueryForObject<bool>("Depot.exists", id);
		}
		
		public Model.Depot GetById(string id)
		{
			return sqlmapper.QueryForObject<Model.Depot>("Depot.get_by_id", id);
		}
		
		public bool ExistsExcept(Model.Depot e)
		{
			Hashtable paras = new Hashtable();
			paras.Add("newId", e.Id);
            paras.Add("oldId", Get(e.DepotId)==null?null:Get(e.DepotId).Id);
			return sqlmapper.QueryForObject<bool>("Depot.existsexcept", paras);
		}
		
		
		
		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("Depot.existsPrimary", id);
		}
    }
}
