//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoicePOAccessor.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:04
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class InvoicePOAccessor
    {
		public Model.InvoicePO Get(string id)
		{
			return this.Get<Model.InvoicePO>(id);
		}
		
		public void Insert(Model.InvoicePO e)
		{
			this.Insert<Model.InvoicePO>(e);
		}
		
		public void Update(Model.InvoicePO e)
		{
			this.Update<Model.InvoicePO>(e);
		}
		
		public IList<Model.InvoicePO> Select()
		{
			return this.Select<Model.InvoicePO>();
		}
		
		public IList<Model.InvoicePO> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.InvoicePO>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.InvoicePO>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.InvoicePO>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.InvoicePO>();
		}
		public int Count()
		{
			return this.Count<Model.InvoicePO>();
		}
		public bool HasRowsBefore(Model.InvoicePO e)
		{
			return sqlmapper.QueryForObject<bool>("InvoicePO.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.InvoicePO e)
		{
			return sqlmapper.QueryForObject<bool>("InvoicePO.has_rows_after", e);
		}
		public Model.InvoicePO GetFirst()
		{
			return sqlmapper.QueryForObject<Model.InvoicePO>("InvoicePO.get_first", null);
		}
		public Model.InvoicePO GetLast()
		{
			return sqlmapper.QueryForObject<Model.InvoicePO>("InvoicePO.get_last", null);
		}
		public Model.InvoicePO GetNext(Model.InvoicePO e)
		{
			return sqlmapper.QueryForObject<Model.InvoicePO>("InvoicePO.get_next", e);
		}
		public Model.InvoicePO GetPrev(Model.InvoicePO e)
		{
			return sqlmapper.QueryForObject<Model.InvoicePO>("InvoicePO.get_prev", e);
		}
		

    }
}
