//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceZXAccessor.autogenerated.cs
// author: mayanjun
// create date：2012-10-29 14:32:21
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class InvoiceZXAccessor
    {
		public Model.InvoiceZX Get(string id)
		{
			return this.Get<Model.InvoiceZX>(id);
		}
		
		public void Insert(Model.InvoiceZX e)
		{
			this.Insert<Model.InvoiceZX>(e);
		}
		
		public void Update(Model.InvoiceZX e)
		{
			this.Update<Model.InvoiceZX>(e);
		}
		
		public IList<Model.InvoiceZX> Select()
		{
			return this.Select<Model.InvoiceZX>();
		}
		
		public IList<Model.InvoiceZX> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.InvoiceZX>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.InvoiceZX>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.InvoiceZX>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.InvoiceZX>();
		}
		public int Count()
		{
			return this.Count<Model.InvoiceZX>();
		}
		public bool HasRowsBefore(Model.InvoiceZX e)
		{
			return sqlmapper.QueryForObject<bool>("InvoiceZX.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.InvoiceZX e)
		{
			return sqlmapper.QueryForObject<bool>("InvoiceZX.has_rows_after", e);
		}
		public Model.InvoiceZX GetFirst()
		{
			return sqlmapper.QueryForObject<Model.InvoiceZX>("InvoiceZX.get_first", null);
		}
		public Model.InvoiceZX GetLast()
		{
			return sqlmapper.QueryForObject<Model.InvoiceZX>("InvoiceZX.get_last", null);
		}
		public Model.InvoiceZX GetNext(Model.InvoiceZX e)
		{
			return sqlmapper.QueryForObject<Model.InvoiceZX>("InvoiceZX.get_next", e);
		}
		public Model.InvoiceZX GetPrev(Model.InvoiceZX e)
		{
			return sqlmapper.QueryForObject<Model.InvoiceZX>("InvoiceZX.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("InvoiceZX.existsPrimary", id);
		}
    }
}
