//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PassNoteBookAccessor.autogenerated.cs
// author: mayanjun
// create date：2013-4-3 17:47:19
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PassNoteBookAccessor
    {
		public Model.PassNoteBook Get(string id)
		{
			return this.Get<Model.PassNoteBook>(id);
		}
		
		public void Insert(Model.PassNoteBook e)
		{
			this.Insert<Model.PassNoteBook>(e);
		}
		
		public void Update(Model.PassNoteBook e)
		{
			this.Update<Model.PassNoteBook>(e);
		}
		
		public IList<Model.PassNoteBook> Select()
		{
			return this.Select<Model.PassNoteBook>();
		}
		
		public IList<Model.PassNoteBook> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PassNoteBook>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PassNoteBook>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PassNoteBook>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PassNoteBook>();
		}
		public int Count()
		{
			return this.Count<Model.PassNoteBook>();
		}
		public bool HasRowsBefore(Model.PassNoteBook e)
		{
			return sqlmapper.QueryForObject<bool>("PassNoteBook.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.PassNoteBook e)
		{
			return sqlmapper.QueryForObject<bool>("PassNoteBook.has_rows_after", e);
		}
		public Model.PassNoteBook GetFirst()
		{
			return sqlmapper.QueryForObject<Model.PassNoteBook>("PassNoteBook.get_first", null);
		}
		public Model.PassNoteBook GetLast()
		{
			return sqlmapper.QueryForObject<Model.PassNoteBook>("PassNoteBook.get_last", null);
		}
		public Model.PassNoteBook GetNext(Model.PassNoteBook e)
		{
			return sqlmapper.QueryForObject<Model.PassNoteBook>("PassNoteBook.get_next", e);
		}
		public Model.PassNoteBook GetPrev(Model.PassNoteBook e)
		{
			return sqlmapper.QueryForObject<Model.PassNoteBook>("PassNoteBook.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PassNoteBook.existsPrimary", id);
		}
    }
}
