//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCBoxFootCheckAccessor.autogenerated.cs
// author: mayanjun
// create date：2013-1-29 16:06:00
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCBoxFootCheckAccessor
    {
		public Model.PCBoxFootCheck Get(string id)
		{
			return this.Get<Model.PCBoxFootCheck>(id);
		}
		
		public void Insert(Model.PCBoxFootCheck e)
		{
			this.Insert<Model.PCBoxFootCheck>(e);
		}
		
		public void Update(Model.PCBoxFootCheck e)
		{
			this.Update<Model.PCBoxFootCheck>(e);
		}
		
		public IList<Model.PCBoxFootCheck> Select()
		{
			return this.Select<Model.PCBoxFootCheck>();
		}
		
		public IList<Model.PCBoxFootCheck> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCBoxFootCheck>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCBoxFootCheck>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCBoxFootCheck>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCBoxFootCheck>();
		}
		public int Count()
		{
			return this.Count<Model.PCBoxFootCheck>();
		}
		public bool HasRowsBefore(Model.PCBoxFootCheck e)
		{
			return sqlmapper.QueryForObject<bool>("PCBoxFootCheck.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.PCBoxFootCheck e)
		{
			return sqlmapper.QueryForObject<bool>("PCBoxFootCheck.has_rows_after", e);
		}
		public Model.PCBoxFootCheck GetFirst()
		{
			return sqlmapper.QueryForObject<Model.PCBoxFootCheck>("PCBoxFootCheck.get_first", null);
		}
		public Model.PCBoxFootCheck GetLast()
		{
			return sqlmapper.QueryForObject<Model.PCBoxFootCheck>("PCBoxFootCheck.get_last", null);
		}
		public Model.PCBoxFootCheck GetNext(Model.PCBoxFootCheck e)
		{
			return sqlmapper.QueryForObject<Model.PCBoxFootCheck>("PCBoxFootCheck.get_next", e);
		}
		public Model.PCBoxFootCheck GetPrev(Model.PCBoxFootCheck e)
		{
			return sqlmapper.QueryForObject<Model.PCBoxFootCheck>("PCBoxFootCheck.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCBoxFootCheck.existsPrimary", id);
		}
    }
}
