//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCExportReportANSIAccessor.autogenerated.cs
// author: mayanjun
// create date：2012-3-13 15:25:59
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCExportReportANSIAccessor
    {
		public Model.PCExportReportANSI Get(string id)
		{
			return this.Get<Model.PCExportReportANSI>(id);
		}
		
		public void Insert(Model.PCExportReportANSI e)
		{
			this.Insert<Model.PCExportReportANSI>(e);
		}
		
		public void Update(Model.PCExportReportANSI e)
		{
			this.Update<Model.PCExportReportANSI>(e);
		}
		
		public IList<Model.PCExportReportANSI> Select()
		{
			return this.Select<Model.PCExportReportANSI>();
		}
		
		public IList<Model.PCExportReportANSI> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCExportReportANSI>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCExportReportANSI>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCExportReportANSI>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCExportReportANSI>();
		}
		public int Count()
		{
			return this.Count<Model.PCExportReportANSI>();
		}
		public bool HasRowsBefore(Model.PCExportReportANSI e)
		{
			return sqlmapper.QueryForObject<bool>("PCExportReportANSI.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.PCExportReportANSI e)
		{
			return sqlmapper.QueryForObject<bool>("PCExportReportANSI.has_rows_after", e);
		}
		public Model.PCExportReportANSI GetFirst()
		{
			return sqlmapper.QueryForObject<Model.PCExportReportANSI>("PCExportReportANSI.get_first", null);
		}
		public Model.PCExportReportANSI GetLast()
		{
			return sqlmapper.QueryForObject<Model.PCExportReportANSI>("PCExportReportANSI.get_last", null);
		}
		public Model.PCExportReportANSI GetNext(Model.PCExportReportANSI e)
		{
			return sqlmapper.QueryForObject<Model.PCExportReportANSI>("PCExportReportANSI.get_next", e);
		}
		public Model.PCExportReportANSI GetPrev(Model.PCExportReportANSI e)
		{
			return sqlmapper.QueryForObject<Model.PCExportReportANSI>("PCExportReportANSI.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCExportReportANSI.existsPrimary", id);
		}
    }
}
