//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCFlameRetardantAccessor.autogenerated.cs
// author: mayanjun
// create date：2018/12/27 13:18:23
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCFlameRetardantAccessor
    {
		public Model.PCFlameRetardant Get(string id)
		{
			return this.Get<Model.PCFlameRetardant>(id);
		}
		
		public void Insert(Model.PCFlameRetardant e)
		{
			this.Insert<Model.PCFlameRetardant>(e);
		}
		
		public void Update(Model.PCFlameRetardant e)
		{
			this.Update<Model.PCFlameRetardant>(e);
		}
		
		public IList<Model.PCFlameRetardant> Select()
		{
			return this.Select<Model.PCFlameRetardant>();
		}
		
		public IList<Model.PCFlameRetardant> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCFlameRetardant>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCFlameRetardant>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCFlameRetardant>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCFlameRetardant>();
		}
		public int Count()
		{
			return this.Count<Model.PCFlameRetardant>();
		}
		public bool HasRowsBefore(Model.PCFlameRetardant e)
		{
			return sqlmapper.QueryForObject<bool>("PCFlameRetardant.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.PCFlameRetardant e)
		{
			return sqlmapper.QueryForObject<bool>("PCFlameRetardant.has_rows_after", e);
		}
		public Model.PCFlameRetardant GetFirst()
		{
			return sqlmapper.QueryForObject<Model.PCFlameRetardant>("PCFlameRetardant.get_first", null);
		}
		public Model.PCFlameRetardant GetLast()
		{
			return sqlmapper.QueryForObject<Model.PCFlameRetardant>("PCFlameRetardant.get_last", null);
		}
		public Model.PCFlameRetardant GetNext(Model.PCFlameRetardant e)
		{
			return sqlmapper.QueryForObject<Model.PCFlameRetardant>("PCFlameRetardant.get_next", e);
		}
		public Model.PCFlameRetardant GetPrev(Model.PCFlameRetardant e)
		{
			return sqlmapper.QueryForObject<Model.PCFlameRetardant>("PCFlameRetardant.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCFlameRetardant.existsPrimary", id);
		}
    }
}
