//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCIncomingCheckDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/11/8 20:10:10
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCIncomingCheckDetailAccessor
    {
		public Model.PCIncomingCheckDetail Get(string id)
		{
			return this.Get<Model.PCIncomingCheckDetail>(id);
		}
		
		public void Insert(Model.PCIncomingCheckDetail e)
		{
			this.Insert<Model.PCIncomingCheckDetail>(e);
		}
		
		public void Update(Model.PCIncomingCheckDetail e)
		{
			this.Update<Model.PCIncomingCheckDetail>(e);
		}
		
		public IList<Model.PCIncomingCheckDetail> Select()
		{
			return this.Select<Model.PCIncomingCheckDetail>();
		}
		
		public IList<Model.PCIncomingCheckDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCIncomingCheckDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCIncomingCheckDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCIncomingCheckDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCIncomingCheckDetail>();
		}
		public int Count()
		{
			return this.Count<Model.PCIncomingCheckDetail>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCIncomingCheckDetail.existsPrimary", id);
		}
    }
}
