//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCSamplingDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/10/30 17:07:37
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCSamplingDetailAccessor
    {
		public Model.PCSamplingDetail Get(string id)
		{
			return this.Get<Model.PCSamplingDetail>(id);
		}
		
		public void Insert(Model.PCSamplingDetail e)
		{
			this.Insert<Model.PCSamplingDetail>(e);
		}
		
		public void Update(Model.PCSamplingDetail e)
		{
			this.Update<Model.PCSamplingDetail>(e);
		}
		
		public IList<Model.PCSamplingDetail> Select()
		{
			return this.Select<Model.PCSamplingDetail>();
		}
		
		public IList<Model.PCSamplingDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCSamplingDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCSamplingDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCSamplingDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCSamplingDetail>();
		}
		public int Count()
		{
			return this.Count<Model.PCSamplingDetail>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCSamplingDetail.existsPrimary", id);
		}
    }
}
