//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：accepterattribManager.autogenerated.cs
// author: peidun
// create date：2009-12-9 10:27:05
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class accepterattribManager
    {
		///<summary>
		/// Data accessor of dbo.accepterattrib
		///</summary>
		private static readonly DA.IaccepterattribAccessor accessor = (DA.IaccepterattribAccessor)Accessors.Get("accepterattribAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.accepterattrib Get(string accepterattribID)
		{
			return accessor.Get(accepterattribID);
		}
		
		public bool HasRows(string accepterattribID)
		{
			return accessor.HasRows(accepterattribID);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool HasRowsBefore(Model.accepterattrib e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.accepterattrib e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.accepterattrib GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.accepterattrib GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.accepterattrib GetPrev(Model.accepterattrib e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.accepterattrib GetNext(Model.accepterattrib e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.accepterattrib> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.accepterattrib> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		
    }
}
