//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：BGHandbookDepotInManager.autogenerated.cs
// author: mayanjun
// create date：2013/12/27 13:34:11
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class BGHandbookDepotInManager
    {
		///<summary>
		/// Data accessor of dbo.BGHandbookDepotIn
		///</summary>
		private static readonly DA.IBGHandbookDepotInAccessor accessor = (DA.IBGHandbookDepotInAccessor)Accessors.Get("BGHandbookDepotInAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.BGHandbookDepotIn Get(string bGHandbookDepotInId)
		{
			return accessor.Get(bGHandbookDepotInId);
		}
		
		public bool HasRows(string bGHandbookDepotInId)
		{
			return accessor.HasRows(bGHandbookDepotInId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.BGHandbookDepotIn e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.BGHandbookDepotIn e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.BGHandbookDepotIn GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.BGHandbookDepotIn GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.BGHandbookDepotIn GetPrev(Model.BGHandbookDepotIn e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.BGHandbookDepotIn GetNext(Model.BGHandbookDepotIn e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.BGHandbookDepotIn> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.BGHandbookDepotIn> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
