//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：CustomerPackageManager.autogenerated.cs
// author: peidun
// create date：2010-2-4 11:15:11
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class CustomerPackageManager
    {
		///<summary>
		/// Data accessor of dbo.CustomerPackage
		///</summary>
		private static readonly DA.ICustomerPackageAccessor accessor = (DA.ICustomerPackageAccessor)Accessors.Get("CustomerPackageAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.CustomerPackage Get(string customerPackageId)
		{
			return accessor.Get(customerPackageId);
		}
		
		public bool HasRows(string customerPackageId)
		{
			return accessor.HasRows(customerPackageId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool Exists(string id)
		{
			return accessor.Exists(id);
		}
		
		public Model.CustomerPackage GetById(string id)
		{
			return accessor.GetById(id);
		}
		
		public bool ExistsExcept(Model.CustomerPackage e)
		{
			return accessor.ExistsExcept(e);
		}
		public bool HasRowsBefore(Model.CustomerPackage e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.CustomerPackage e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.CustomerPackage GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.CustomerPackage GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.CustomerPackage GetPrev(Model.CustomerPackage e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.CustomerPackage GetNext(Model.CustomerPackage e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.CustomerPackage> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.CustomerPackage> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		
    }
}
