//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：CustomerMarksManager.autogenerated.cs
// author: mayanjun
// create date：2013-5-8 13:43:44
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class CustomerMarksManager
    {
		///<summary>
		/// Data accessor of dbo.CustomerMarks
		///</summary>
		private static readonly DA.ICustomerMarksAccessor accessor = (DA.ICustomerMarksAccessor)Accessors.Get("CustomerMarksAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.CustomerMarks Get(string customerMarksId)
		{
			return accessor.Get(customerMarksId);
		}
		
		public bool HasRows(string customerMarksId)
		{
			return accessor.HasRows(customerMarksId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool Exists(string id)
		{
			return accessor.Exists(id);
		}
		
		public Model.CustomerMarks GetById(string id)
		{
			return accessor.GetById(id);
		}		
		public bool ExistsExcept(Model.CustomerMarks e)
		{
			return accessor.ExistsExcept(e);
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.CustomerMarks> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.CustomerMarks> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
