//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：FreightedCompanyManager.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:01
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class FreightedCompanyManager
    {
		///<summary>
		/// Data accessor of dbo.FreightedCompany
		///</summary>
		private static readonly DA.IFreightedCompanyAccessor accessor = (DA.IFreightedCompanyAccessor)Accessors.Get("FreightedCompanyAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.FreightedCompany Get(string freightedCompanyId)
		{
			return accessor.Get(freightedCompanyId);
		}
		
		public bool HasRows(string freightedCompanyId)
		{
			return accessor.HasRows(freightedCompanyId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool Exists(string id)
		{
			return accessor.Exists(id);
		}
		
		public Model.FreightedCompany GetById(string id)
		{
			return accessor.GetById(id);
		}
		
		public bool ExistsExcept(Model.FreightedCompany e)
		{
			return accessor.ExistsExcept(e);
		}
		public bool HasRowsBefore(Model.FreightedCompany e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.FreightedCompany e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.FreightedCompany GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.FreightedCompany GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.FreightedCompany GetPrev(Model.FreightedCompany e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.FreightedCompany GetNext(Model.FreightedCompany e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.FreightedCompany> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.FreightedCompany> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		
    }
}
