//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：processedaccepterManager.autogenerated.cs
// author: peidun
// create date：2009-12-9 10:27:05
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class processedaccepterManager
    {
		///<summary>
		/// Data accessor of dbo.processedaccepter
		///</summary>
		private static readonly DA.IprocessedaccepterAccessor accessor = (DA.IprocessedaccepterAccessor)Accessors.Get("processedaccepterAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.processedaccepter Get(string processedaccepterid)
		{
			return accessor.Get(processedaccepterid);
		}
		
		public bool HasRows(string processedaccepterid)
		{
			return accessor.HasRows(processedaccepterid);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool HasRowsBefore(Model.processedaccepter e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.processedaccepter e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.processedaccepter GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.processedaccepter GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.processedaccepter GetPrev(Model.processedaccepter e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.processedaccepter GetNext(Model.processedaccepter e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.processedaccepter> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.processedaccepter> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		
    }
}
