//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProceduresMachineManager.autogenerated.cs
// author: mayanjun
// create date：2010-9-17 16:47:14
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class ProceduresMachineManager
    {
		///<summary>
		/// Data accessor of dbo.ProceduresMachine
		///</summary>
		private static readonly DA.IProceduresMachineAccessor accessor = (DA.IProceduresMachineAccessor)Accessors.Get("ProceduresMachineAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.ProceduresMachine Get(string proceduresMachineId)
		{
			return accessor.Get(proceduresMachineId);
		}
		
		public bool HasRows(string proceduresMachineId)
		{
			return accessor.HasRows(proceduresMachineId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.ProceduresMachine e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.ProceduresMachine e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.ProceduresMachine GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.ProceduresMachine GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.ProceduresMachine GetPrev(Model.ProceduresMachine e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.ProceduresMachine GetNext(Model.ProceduresMachine e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.ProceduresMachine> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.ProceduresMachine> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
