//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProduceOtherInDepotManager.autogenerated.cs
// author: mayanjun
// create date：2011-10-28 14:02:01
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class ProduceOtherInDepotManager
    {
		///<summary>
		/// Data accessor of dbo.ProduceOtherInDepot
		///</summary>
		private static readonly DA.IProduceOtherInDepotAccessor accessor = (DA.IProduceOtherInDepotAccessor)Accessors.Get("ProduceOtherInDepotAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.ProduceOtherInDepot Get(string produceOtherInDepotId)
		{
			return accessor.Get(produceOtherInDepotId);
		}
		
		public bool HasRows(string produceOtherInDepotId)
		{
			return accessor.HasRows(produceOtherInDepotId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.ProduceOtherInDepot e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.ProduceOtherInDepot e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.ProduceOtherInDepot GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.ProduceOtherInDepot GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.ProduceOtherInDepot GetPrev(Model.ProduceOtherInDepot e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.ProduceOtherInDepot GetNext(Model.ProduceOtherInDepot e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.ProduceOtherInDepot> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.ProduceOtherInDepot> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
