//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProduceOtherExitDetailManager.autogenerated.cs
// author: peidun
// create date：2010-1-6 10:20:15
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class ProduceOtherExitDetailManager
    {
		///<summary>
		/// Data accessor of dbo.ProduceOtherExitDetail
		///</summary>
		private static readonly DA.IProduceOtherExitDetailAccessor accessor = (DA.IProduceOtherExitDetailAccessor)Accessors.Get("ProduceOtherExitDetailAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.ProduceOtherExitDetail Get(string produceOtherExitDetailId)
		{
			return accessor.Get(produceOtherExitDetailId);
		}
		
		public bool HasRows(string produceOtherExitDetailId)
		{
			return accessor.HasRows(produceOtherExitDetailId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.ProduceOtherExitDetail> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.ProduceOtherExitDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		
    }
}
