//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：SalesForHeaderManager.autogenerated.cs
// author: peidun
// create date：2009-12-18 11:23:45
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class SalesForHeaderManager
    {
		///<summary>
		/// Data accessor of dbo.SalesForHeader
		///</summary>
		private static readonly DA.ISalesForHeaderAccessor accessor = (DA.ISalesForHeaderAccessor)Accessors.Get("SalesForHeaderAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.SalesForHeader Get(string salesForHeaderId)
		{
			return accessor.Get(salesForHeaderId);
		}
		
		public bool HasRows(string salesForHeaderId)
		{
			return accessor.HasRows(salesForHeaderId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool Exists(string id)
		{
			return accessor.Exists(id);
		}
		
		public Model.SalesForHeader GetById(string id)
		{
			return accessor.GetById(id);
		}
		
		public bool ExistsExcept(Model.SalesForHeader e)
		{
			return accessor.ExistsExcept(e);
		}
		public bool HasRowsBefore(Model.SalesForHeader e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.SalesForHeader e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.SalesForHeader GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.SalesForHeader GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.SalesForHeader GetPrev(Model.SalesForHeader e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.SalesForHeader GetNext(Model.SalesForHeader e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.SalesForHeader> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.SalesForHeader> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		
    }
}
