//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：WorkhouselogManager.autogenerated.cs
// author: peidun
// create date：2009-12-9 10:27:05
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class WorkhouselogManager
    {
		///<summary>
		/// Data accessor of dbo.Workhouselog
		///</summary>
		private static readonly DA.IWorkhouselogAccessor accessor = (DA.IWorkhouselogAccessor)Accessors.Get("WorkhouselogAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.Workhouselog Get(string workhouselogID)
		{
			return accessor.Get(workhouselogID);
		}
		
		public bool HasRows(string workhouselogID)
		{
			return accessor.HasRows(workhouselogID);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool HasRowsBefore(Model.Workhouselog e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.Workhouselog e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.Workhouselog GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.Workhouselog GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.Workhouselog GetPrev(Model.Workhouselog e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.Workhouselog GetNext(Model.Workhouselog e)
		{
			return accessor.GetNext(e);
		}
        //public Model.Workhouselog GetById(string id)
        //{
        //    return accessor.GetById(id);
        //}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.Workhouselog> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.Workhouselog> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		
    }
}
