//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：AcOtherShouldCollectionManager.autogenerated.cs
// author: mayanjun
// create date：2011-6-10 11:24:11
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class AcOtherShouldCollectionManager
    {
		///<summary>
		/// Data accessor of dbo.AcOtherShouldCollection
		///</summary>
		private static readonly DA.IAcOtherShouldCollectionAccessor accessor = (DA.IAcOtherShouldCollectionAccessor)Accessors.Get("AcOtherShouldCollectionAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.AcOtherShouldCollection Get(string acOtherShouldCollectionId)
		{
			return accessor.Get(acOtherShouldCollectionId);
		}
		
		public bool HasRows(string acOtherShouldCollectionId)
		{
			return accessor.HasRows(acOtherShouldCollectionId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.AcOtherShouldCollection e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.AcOtherShouldCollection e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.AcOtherShouldCollection GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.AcOtherShouldCollection GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.AcOtherShouldCollection GetPrev(Model.AcOtherShouldCollection e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.AcOtherShouldCollection GetNext(Model.AcOtherShouldCollection e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.AcOtherShouldCollection> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.AcOtherShouldCollection> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
