//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：AtProfitLossManager.autogenerated.cs
// author: mayanjun
// create date：2011-3-3 14:30:19
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class AtProfitLossManager
    {
		///<summary>
		/// Data accessor of dbo.AtProfitLoss
		///</summary>
		private static readonly DA.IAtProfitLossAccessor accessor = (DA.IAtProfitLossAccessor)Accessors.Get("AtProfitLossAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.AtProfitLoss Get(string profitLossId)
		{
			return accessor.Get(profitLossId);
		}
		
		public bool HasRows(string profitLossId)
		{
			return accessor.HasRows(profitLossId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool Exists(string id)
		{
			return accessor.Exists(id);
		}
		
		public Model.AtProfitLoss GetById(string id)
		{
			return accessor.GetById(id);
		}		
		public bool ExistsExcept(Model.AtProfitLoss e)
		{
			return accessor.ExistsExcept(e);
		}
		
		
		public bool HasRowsBefore(Model.AtProfitLoss e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.AtProfitLoss e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.AtProfitLoss GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.AtProfitLoss GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.AtProfitLoss GetPrev(Model.AtProfitLoss e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.AtProfitLoss GetNext(Model.AtProfitLoss e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.AtProfitLoss> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.AtProfitLoss> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
