//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProceduresManager.autogenerated.cs
// author: peidun
// create date：2009-12-9 10:27:05
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class ProceduresManager
    {
		///<summary>
		/// Data accessor of dbo.Procedures
		///</summary>
		private static readonly DA.IProceduresAccessor accessor = (DA.IProceduresAccessor)Accessors.Get("ProceduresAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.Procedures Get(string procedureid)
		{
			return accessor.Get(procedureid);
		}
		
		public bool HasRows(string procedureid)
		{
			return accessor.HasRows(procedureid);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool Exists(string id)
		{
			return accessor.Exists(id);
		}
		
		public Model.Procedures GetById(string id)
		{
			return accessor.GetById(id);
		}
		
		public bool ExistsExcept(Model.Procedures e)
		{
			return accessor.ExistsExcept(e);
		}
		public bool HasRowsBefore(Model.Procedures e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.Procedures e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.Procedures GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.Procedures GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.Procedures GetPrev(Model.Procedures e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.Procedures GetNext(Model.Procedures e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.Procedures> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.Procedures> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		
    }
}
