//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：QualityTestPlanManager.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:02
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class QualityTestPlanManager
    {
		///<summary>
		/// Data accessor of dbo.QualityTestPlan
		///</summary>
		private static readonly DA.IQualityTestPlanAccessor accessor = (DA.IQualityTestPlanAccessor)Accessors.Get("QualityTestPlanAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.QualityTestPlan Get(string qualityTestPlanId)
		{
			return accessor.Get(qualityTestPlanId);
		}
		
		public bool HasRows(string qualityTestPlanId)
		{
			return accessor.HasRows(qualityTestPlanId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool Exists(string id)
		{
			return accessor.Exists(id);
		}
		
		public Model.QualityTestPlan GetById(string id)
		{
			return accessor.GetById(id);
		}
		
		public bool ExistsExcept(Model.QualityTestPlan e)
		{
			return accessor.ExistsExcept(e);
		}
		public bool HasRowsBefore(Model.QualityTestPlan e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.QualityTestPlan e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.QualityTestPlan GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.QualityTestPlan GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.QualityTestPlan GetPrev(Model.QualityTestPlan e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.QualityTestPlan GetNext(Model.QualityTestPlan e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.QualityTestPlan> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.QualityTestPlan> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		
    }
}
