//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：RoleOperationManager.autogenerated.cs
// author: mayanjun
// create date：2011-5-11 10:51:07
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class RoleOperationManager
    {
		///<summary>
		/// Data accessor of dbo.RoleOperation
		///</summary>
		private static readonly DA.IRoleOperationAccessor accessor = (DA.IRoleOperationAccessor)Accessors.Get("RoleOperationAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.RoleOperation Get(string roleOperationId)
		{
			return accessor.Get(roleOperationId);
		}
		
		public bool HasRows(string roleOperationId)
		{
			return accessor.HasRows(roleOperationId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.RoleOperation> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.RoleOperation> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
