//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：StockEditorManager.autogenerated.cs
// author: mayanjun
// create date：2010-11-4 11:02:31
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class StockEditorManager
    {
		///<summary>
		/// Data accessor of dbo.StockEditor
		///</summary>
		private static readonly DA.IStockEditorAccessor accessor = (DA.IStockEditorAccessor)Accessors.Get("StockEditorAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.StockEditor Get(string stockEditorId)
		{
			return accessor.Get(stockEditorId);
		}
		
		public bool HasRows(string stockEditorId)
		{
			return accessor.HasRows(stockEditorId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.StockEditor e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.StockEditor e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.StockEditor GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.StockEditor GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.StockEditor GetPrev(Model.StockEditor e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.StockEditor GetNext(Model.StockEditor e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.StockEditor> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.StockEditor> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
