//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：wfrecordlogManager.autogenerated.cs
// author: peidun
// create date：2009-12-11 14:53:01
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class wfrecordlogManager
    {
		///<summary>
		/// Data accessor of dbo.wfrecordlog
		///</summary>
		private static readonly DA.IwfrecordlogAccessor accessor = (DA.IwfrecordlogAccessor)Accessors.Get("wfrecordlogAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.wfrecordlog Get(string wfrecordlogid)
		{
			return accessor.Get(wfrecordlogid);
		}
		
		public bool HasRows(string wfrecordlogid)
		{
			return accessor.HasRows(wfrecordlogid);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		public bool HasRowsBefore(Model.wfrecordlog e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.wfrecordlog e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.wfrecordlog GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.wfrecordlog GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.wfrecordlog GetPrev(Model.wfrecordlog e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.wfrecordlog GetNext(Model.wfrecordlog e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.wfrecordlog> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.wfrecordlog> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		
    }
}
