//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceCODetailAccessor.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:03
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class InvoiceCODetailAccessor
    {
		public Model.InvoiceCODetail Get(string id)
		{
			return this.Get<Model.InvoiceCODetail>(id);
		}
		
		public void Insert(Model.InvoiceCODetail e)
		{
			this.Insert<Model.InvoiceCODetail>(e);
		}
		
		public void Update(Model.InvoiceCODetail e)
		{
			this.Update<Model.InvoiceCODetail>(e);
		}
		
		public IList<Model.InvoiceCODetail> Select()
		{
			return this.Select<Model.InvoiceCODetail>();
		}
		
		public IList<Model.InvoiceCODetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.InvoiceCODetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.InvoiceCODetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.InvoiceCODetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.InvoiceCODetail>();
		}
		public int Count()
		{
			return this.Count<Model.InvoiceCODetail>();
		}

    }
}
