//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：MaterialTypeAccessor.autogenerated.cs
// author: peidun
// create date：2010-4-20 15:57:56
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class MaterialTypeAccessor
    {
		public Model.MaterialType Get(string id)
		{
			return this.Get<Model.MaterialType>(id);
		}
		
		public void Insert(Model.MaterialType e)
		{
			this.Insert<Model.MaterialType>(e);
		}
		
		public void Update(Model.MaterialType e)
		{
			this.Update<Model.MaterialType>(e);
		}
		
		public IList<Model.MaterialType> Select()
		{
			return this.Select<Model.MaterialType>();
		}
		
		public IList<Model.MaterialType> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.MaterialType>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.MaterialType>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.MaterialType>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.MaterialType>();
		}
		public int Count()
		{
			return this.Count<Model.MaterialType>();
		}
		public bool HasRowsBefore(Model.MaterialType e)
		{
			return sqlmapper.QueryForObject<bool>("MaterialType.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.MaterialType e)
		{
			return sqlmapper.QueryForObject<bool>("MaterialType.has_rows_after", e);
		}
		public Model.MaterialType GetFirst()
		{
			return sqlmapper.QueryForObject<Model.MaterialType>("MaterialType.get_first", null);
		}
		public Model.MaterialType GetLast()
		{
			return sqlmapper.QueryForObject<Model.MaterialType>("MaterialType.get_last", null);
		}
		public Model.MaterialType GetNext(Model.MaterialType e)
		{
			return sqlmapper.QueryForObject<Model.MaterialType>("MaterialType.get_next", e);
		}
		public Model.MaterialType GetPrev(Model.MaterialType e)
		{
			return sqlmapper.QueryForObject<Model.MaterialType>("MaterialType.get_prev", e);
		}
		

		public bool Exists(string id)
		{
			return sqlmapper.QueryForObject<bool>("MaterialType.exists", id);
		}
		
		public Model.MaterialType GetById(string id)
		{
			return sqlmapper.QueryForObject<Model.MaterialType>("MaterialType.get_by_id", id);
		}
		
		public bool ExistsExcept(Model.MaterialType e)
		{
			Hashtable paras = new Hashtable();
			paras.Add("newId", e.Id);
            paras.Add("oldId", Get(e.MaterialTypeID).Id);
			return sqlmapper.QueryForObject<bool>("MaterialType.existsexcept", paras);
		}
		
		
		
		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("MaterialType.existsPrimary", id);
		}
    }
}
