//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProceduresPriceAccessor.autogenerated.cs
// author: mayanjun
// create date：2011-3-31 10:22:31
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class ProceduresPriceAccessor
    {
		public Model.ProceduresPrice Get(string id)
		{
			return this.Get<Model.ProceduresPrice>(id);
		}
		
		public void Insert(Model.ProceduresPrice e)
		{
			this.Insert<Model.ProceduresPrice>(e);
		}
		
		public void Update(Model.ProceduresPrice e)
		{
			this.Update<Model.ProceduresPrice>(e);
		}
		
		public IList<Model.ProceduresPrice> Select()
		{
			return this.Select<Model.ProceduresPrice>();
		}
		
		public IList<Model.ProceduresPrice> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.ProceduresPrice>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.ProceduresPrice>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.ProceduresPrice>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.ProceduresPrice>();
		}
		public int Count()
		{
			return this.Count<Model.ProceduresPrice>();
		}
		public bool HasRowsBefore(Model.ProceduresPrice e)
		{
			return sqlmapper.QueryForObject<bool>("ProceduresPrice.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.ProceduresPrice e)
		{
			return sqlmapper.QueryForObject<bool>("ProceduresPrice.has_rows_after", e);
		}
		public Model.ProceduresPrice GetFirst()
		{
			return sqlmapper.QueryForObject<Model.ProceduresPrice>("ProceduresPrice.get_first", null);
		}
		public Model.ProceduresPrice GetLast()
		{
			return sqlmapper.QueryForObject<Model.ProceduresPrice>("ProceduresPrice.get_last", null);
		}
		public Model.ProceduresPrice GetNext(Model.ProceduresPrice e)
		{
			return sqlmapper.QueryForObject<Model.ProceduresPrice>("ProceduresPrice.get_next", e);
		}
		public Model.ProceduresPrice GetPrev(Model.ProceduresPrice e)
		{
			return sqlmapper.QueryForObject<Model.ProceduresPrice>("ProceduresPrice.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("ProceduresPrice.existsPrimary", id);
		}
    }
}
