//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：TableManageAccessor.autogenerated.cs
// author: peidun
// create date：2009-11-23 10:26:16
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class TableManageAccessor
    {
		public Model.TableManage Get(string id)
		{
			return this.Get<Model.TableManage>(id);
		}
		
		public void Insert(Model.TableManage e)
		{
			this.Insert<Model.TableManage>(e);
		}
		
		public void Update(Model.TableManage e)
		{
			this.Update<Model.TableManage>(e);
		}
		
		public IList<Model.TableManage> Select()
		{
			return this.Select<Model.TableManage>();
		}
		
		public IList<Model.TableManage> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.TableManage>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.TableManage>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.TableManage>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.TableManage>();
		}
		public int Count()
		{
			return this.Count<Model.TableManage>();
		}

    }
}
