//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：TablesAccessor.autogenerated.cs
// author: peidun
// create date：2009-12-11 14:53:03
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class TablesAccessor
    {
		public Model.Tables Get(string id)
		{
			return this.Get<Model.Tables>(id);
		}
		
		public void Insert(Model.Tables e)
		{
			this.Insert<Model.Tables>(e);
		}
		
		public void Update(Model.Tables e)
		{
			this.Update<Model.Tables>(e);
		}
		
		public IList<Model.Tables> Select()
		{
			return this.Select<Model.Tables>();
		}
		
		public IList<Model.Tables> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.Tables>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.Tables>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.Tables>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.Tables>();
		}
		public int Count()
		{
			return this.Count<Model.Tables>();
		}
		public bool HasRowsBefore(Model.Tables e)
		{
			return sqlmapper.QueryForObject<bool>("Tables.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.Tables e)
		{
			return sqlmapper.QueryForObject<bool>("Tables.has_rows_after", e);
		}
		public Model.Tables GetFirst()
		{
			return sqlmapper.QueryForObject<Model.Tables>("Tables.get_first", null);
		}
		public Model.Tables GetLast()
		{
			return sqlmapper.QueryForObject<Model.Tables>("Tables.get_last", null);
		}
		public Model.Tables GetNext(Model.Tables e)
		{
			return sqlmapper.QueryForObject<Model.Tables>("Tables.get_next", e);
		}
		public Model.Tables GetPrev(Model.Tables e)
		{
			return sqlmapper.QueryForObject<Model.Tables>("Tables.get_prev", e);
		}
		

    }
}
