//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：WorkflowAccessor.autogenerated.cs
// author: peidun
// create date：2009-12-9 10:27:05
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class WorkflowAccessor
    {
		public Model.Workflow Get(string id)
		{
			return this.Get<Model.Workflow>(id);
		}
		
		public void Insert(Model.Workflow e)
		{
			this.Insert<Model.Workflow>(e);
		}
		
		public void Update(Model.Workflow e)
		{
			this.Update<Model.Workflow>(e);
		}
		
		public IList<Model.Workflow> Select()
		{
			return this.Select<Model.Workflow>();
		}
		
		public IList<Model.Workflow> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.Workflow>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.Workflow>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.Workflow>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.Workflow>();
		}
		public int Count()
		{
			return this.Count<Model.Workflow>();
		}
		public bool HasRowsBefore(Model.Workflow e)
		{
			return sqlmapper.QueryForObject<bool>("Workflow.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.Workflow e)
		{
			return sqlmapper.QueryForObject<bool>("Workflow.has_rows_after", e);
		}
		public Model.Workflow GetFirst()
		{
			return sqlmapper.QueryForObject<Model.Workflow>("Workflow.get_first", null);
		}
		public Model.Workflow GetLast()
		{
			return sqlmapper.QueryForObject<Model.Workflow>("Workflow.get_last", null);
		}
		public Model.Workflow GetNext(Model.Workflow e)
		{
			return sqlmapper.QueryForObject<Model.Workflow>("Workflow.get_next", e);
		}
		public Model.Workflow GetPrev(Model.Workflow e)
		{
			return sqlmapper.QueryForObject<Model.Workflow>("Workflow.get_prev", e);
		}
		

    }
}
