//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：AcbeginAccountPayable.autogenerated.cs
// author: mayanjun
// create date：2011-6-13 09:19:29
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class AcbeginAccountPayable
	{
		#region Data

		/// <summary>
		/// 头编号
		/// </summary>
		private string _acbeginAccountPayableId;
		
		/// <summary>
		/// 币别编号
		/// </summary>
		private string _atCurrencyCategoryId;
		
		/// <summary>
		/// 操作人
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 审核
		/// </summary>
		private string _employee0Id;
		
		/// <summary>
		/// 日期
		/// </summary>
		private DateTime? _acbeginAccountPayableDate;
		
		/// <summary>
		/// 备注
		/// </summary>
		private string _acbeginAccountPayableDesc;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 审核状态
		/// </summary>
		private int? _auditingState;

        private int? _auditState;

        private string _auditEmpId;

        private Employee _auditEmp;
		
		/// <summary>
		/// 币种类别
		/// </summary>
		private AtCurrencyCategory _atCurrencyCategory;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee0;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 头编号
		/// </summary>
		public string AcbeginAccountPayableId
		{
			get 
			{
				return this._acbeginAccountPayableId;
			}
			set 
			{
				this._acbeginAccountPayableId = value;
			}
		}

		/// <summary>
		/// 币别编号
		/// </summary>
		public string AtCurrencyCategoryId
		{
			get 
			{
				return this._atCurrencyCategoryId;
			}
			set 
			{
				this._atCurrencyCategoryId = value;
			}
		}

		/// <summary>
		/// 操作人
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 审核
		/// </summary>
		public string Employee0Id
		{
			get 
			{
				return this._employee0Id;
			}
			set 
			{
				this._employee0Id = value;
			}
		}

		/// <summary>
		/// 日期
		/// </summary>
		public DateTime? AcbeginAccountPayableDate
		{
			get 
			{
				return this._acbeginAccountPayableDate;
			}
			set 
			{
				this._acbeginAccountPayableDate = value;
			}
		}

		/// <summary>
		/// 备注
		/// </summary>
		public string AcbeginAccountPayableDesc
		{
			get 
			{
				return this._acbeginAccountPayableDesc;
			}
			set 
			{
				this._acbeginAccountPayableDesc = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 审核状态
		/// </summary>
		public int? AuditingState
		{
			get 
			{
				return this._auditingState;
			}
			set 
			{
				this._auditingState = value;
			}
		}

        public int? AuditState
        {
            get
            {
                return this._auditState;
            }
            set
            {
                this._auditState = value;
            }
        }

        public virtual string AuditEmpId
        {
            get
            {
                return this._auditEmpId;

            }
            set
            {
                this._auditEmpId = value;
            }
        }

        public virtual Employee AuditEmp
        {
            get
            {
                return this._auditEmp;
            }
            set
            {
                this._auditEmp = value;
            }

        }
	
		/// <summary>
		/// 币种类别
		/// </summary>
		public virtual AtCurrencyCategory AtCurrencyCategory
		{
			get
			{
				return this._atCurrencyCategory;
			}
			set
			{
				this._atCurrencyCategory = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee0
		{
			get
			{
				return this._employee0;
			}
			set
			{
				this._employee0 = value;
			}
			
		}
		/// <summary>
		/// 头编号
		/// </summary>
		public readonly static string PRO_AcbeginAccountPayableId = "AcbeginAccountPayableId";
		
		/// <summary>
		/// 币别编号
		/// </summary>
		public readonly static string PRO_AtCurrencyCategoryId = "AtCurrencyCategoryId";
		
		/// <summary>
		/// 操作人
		/// </summary>
		public readonly static string PRO_EmployeeId = "EmployeeId";
		
		/// <summary>
		/// 审核
		/// </summary>
		public readonly static string PRO_Employee0Id = "Employee0Id";
		
		/// <summary>
		/// 日期
		/// </summary>
		public readonly static string PRO_AcbeginAccountPayableDate = "AcbeginAccountPayableDate";
		
		/// <summary>
		/// 备注
		/// </summary>
		public readonly static string PRO_AcbeginAccountPayableDesc = "AcbeginAccountPayableDesc";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 审核状态
		/// </summary>
		public readonly static string PRO_AuditingState = "AuditingState";

        public readonly static string PRO_AuditState = "AuditState";

        public readonly static string PRO_AuditEmpId = "AuditEmpId";

		#endregion
	}
}
