//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：AcbeginAccountPayableDetail.autogenerated.cs
// author: mayanjun
// create date：2011-6-9 15:16:18
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class AcbeginAccountPayableDetail
	{
		#region Data

		/// <summary>
		/// 主键
		/// </summary>
		private string _acbeginAccountPayableDetailId;
		
		/// <summary>
		/// 头编号
		/// </summary>
		private string _acbeginAccountPayableId;
		
		/// <summary>
		/// 供应商编号
		/// </summary>
		private string _supplierId;
		
		/// <summary>
		/// 预付款
		/// </summary>
		private decimal? _advancePayment;
		
		/// <summary>
		/// 本币预付款
		/// </summary>
		private decimal? _domesticAdvancePayment;
		
		/// <summary>
		/// 应付款
		/// </summary>
		private decimal? _shouldPayment;
		
		/// <summary>
		/// 本币应付款
		/// </summary>
		private decimal? _domesticAccountPayable;
		
		/// <summary>
		/// 已付款
		/// </summary>
		private decimal? _alreadyPayment;
		
		/// <summary>
		/// 本币已付款
		/// </summary>
		private decimal? _domesticAlreadyPayment;
		
		/// <summary>
		/// 期初余额
		/// </summary>
		private decimal? _beginningBalance;
		
		/// <summary>
		/// 本币期初余额
		/// </summary>
		private decimal? _domesticBeginningBalance;
		
		/// <summary>
		/// 期初应付账款
		/// </summary>
		private AcbeginAccountPayable _acbeginAccountPayable;
		/// <summary>
		/// 供应商
		/// </summary>
		private Supplier _supplier;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 主键
		/// </summary>
		public string AcbeginAccountPayableDetailId
		{
			get 
			{
				return this._acbeginAccountPayableDetailId;
			}
			set 
			{
				this._acbeginAccountPayableDetailId = value;
			}
		}

		/// <summary>
		/// 头编号
		/// </summary>
		public string AcbeginAccountPayableId
		{
			get 
			{
				return this._acbeginAccountPayableId;
			}
			set 
			{
				this._acbeginAccountPayableId = value;
			}
		}

		/// <summary>
		/// 供应商编号
		/// </summary>
		public string SupplierId
		{
			get 
			{
				return this._supplierId;
			}
			set 
			{
				this._supplierId = value;
			}
		}

		/// <summary>
		/// 预付款
		/// </summary>
		public decimal? AdvancePayment
		{
			get 
			{
				return this._advancePayment;
			}
			set 
			{
				this._advancePayment = value;
			}
		}

		/// <summary>
		/// 本币预付款
		/// </summary>
		public decimal? DomesticAdvancePayment
		{
			get 
			{
				return this._domesticAdvancePayment;
			}
			set 
			{
				this._domesticAdvancePayment = value;
			}
		}

		/// <summary>
		/// 应付款
		/// </summary>
		public decimal? ShouldPayment
		{
			get 
			{
				return this._shouldPayment;
			}
			set 
			{
				this._shouldPayment = value;
			}
		}

		/// <summary>
		/// 本币应付款
		/// </summary>
		public decimal? DomesticAccountPayable
		{
			get 
			{
				return this._domesticAccountPayable;
			}
			set 
			{
				this._domesticAccountPayable = value;
			}
		}

		/// <summary>
		/// 已付款
		/// </summary>
		public decimal? AlreadyPayment
		{
			get 
			{
				return this._alreadyPayment;
			}
			set 
			{
				this._alreadyPayment = value;
			}
		}

		/// <summary>
		/// 本币已付款
		/// </summary>
		public decimal? DomesticAlreadyPayment
		{
			get 
			{
				return this._domesticAlreadyPayment;
			}
			set 
			{
				this._domesticAlreadyPayment = value;
			}
		}

		/// <summary>
		/// 期初余额
		/// </summary>
		public decimal? BeginningBalance
		{
			get 
			{
				return this._beginningBalance;
			}
			set 
			{
				this._beginningBalance = value;
			}
		}

		/// <summary>
		/// 本币期初余额
		/// </summary>
		public decimal? DomesticBeginningBalance
		{
			get 
			{
				return this._domesticBeginningBalance;
			}
			set 
			{
				this._domesticBeginningBalance = value;
			}
		}
	
		/// <summary>
		/// 期初应付账款
		/// </summary>
		public virtual AcbeginAccountPayable AcbeginAccountPayable
		{
			get
			{
				return this._acbeginAccountPayable;
			}
			set
			{
				this._acbeginAccountPayable = value;
			}
			
		}
		/// <summary>
		/// 供应商
		/// </summary>
		public virtual Supplier Supplier
		{
			get
			{
				return this._supplier;
			}
			set
			{
				this._supplier = value;
			}
			
		}
		/// <summary>
		/// 主键
		/// </summary>
		public readonly static string PRO_AcbeginAccountPayableDetailId = "AcbeginAccountPayableDetailId";
		
		/// <summary>
		/// 头编号
		/// </summary>
		public readonly static string PRO_AcbeginAccountPayableId = "AcbeginAccountPayableId";
		
		/// <summary>
		/// 供应商编号
		/// </summary>
		public readonly static string PRO_SupplierId = "SupplierId";
		
		/// <summary>
		/// 预付款
		/// </summary>
		public readonly static string PRO_AdvancePayment = "AdvancePayment";
		
		/// <summary>
		/// 本币预付款
		/// </summary>
		public readonly static string PRO_DomesticAdvancePayment = "DomesticAdvancePayment";
		
		/// <summary>
		/// 应付款
		/// </summary>
		public readonly static string PRO_ShouldPayment = "ShouldPayment";
		
		/// <summary>
		/// 本币应付款
		/// </summary>
		public readonly static string PRO_DomesticAccountPayable = "DomesticAccountPayable";
		
		/// <summary>
		/// 已付款
		/// </summary>
		public readonly static string PRO_AlreadyPayment = "AlreadyPayment";
		
		/// <summary>
		/// 本币已付款
		/// </summary>
		public readonly static string PRO_DomesticAlreadyPayment = "DomesticAlreadyPayment";
		
		/// <summary>
		/// 期初余额
		/// </summary>
		public readonly static string PRO_BeginningBalance = "BeginningBalance";
		
		/// <summary>
		/// 本币期初余额
		/// </summary>
		public readonly static string PRO_DomesticBeginningBalance = "DomesticBeginningBalance";
		

		#endregion
	}
}
