//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ANSIPCImpactCheck.autogenerated.cs
// author: mayanjun
// create date：2012-3-14 15:47:44
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class ANSIPCImpactCheck
    {
        #region Data

        /// <summary>
        /// 主键编号
        /// </summary>
        private string _aNSIPCImpactCheckID;

        /// <summary>
        /// 编号
        /// </summary>
        private string _employeeId;

        /// <summary>
        /// 商品编号
        /// </summary>
        private string _productId;

        /// <summary>
        /// 插入时间
        /// </summary>
        private DateTime? _insertTime;

        /// <summary>
        /// 修改时间
        /// </summary>
        private DateTime? _updateTime;

        /// <summary>
        /// 测试日期
        /// </summary>
        private DateTime? _aNSIPCImpactCheckDate;

        /// <summary>
        /// 客户订单编号
        /// </summary>
        private string _invoiceCusXOId;

        /// <summary>
        /// 加工单据编号
        /// </summary>
        private string _pronoteHeaderId;

        /// <summary>
        /// 冲击测试速度
        /// </summary>
        private string _spead;

        /// <summary>
        /// 备注
        /// </summary>
        private string _aNSIPCImpactCheckDesc;

        /// <summary>
        /// 质检标准
        /// </summary>
        private string _checkStandard;

        /// <summary>
        /// 客户订单数量
        /// </summary>
        private double? _invoiceXOQuantity;

        /// <summary>
        /// 冲击力度
        /// </summary>
        private string _powerImpact;

        /// <summary>
        /// 坠球重量
        /// </summary>
        private string _zhuiQiuKG;

        /// <summary>
        /// 打印所用描述1
        /// </summary>
        private string _printDesc1;

        /// <summary>
        /// 检测数量
        /// </summary>
        private int? _aNSIPCImpactCheckCount;

        /// <summary>
        /// 
        /// </summary>
        private string _invoiceId;

        /// <summary>
        /// 
        /// </summary>
        private bool? _isYuanZhuiZhuiLuo;

        /// <summary>
        /// 
        /// </summary>
        private bool? _isGaoSuChongJi;

        /// <summary>
        /// 
        /// </summary>
        private bool? _isNaiRanXing;

        /// <summary>
        /// 测试单类型
        /// </summary>
        private string _forANSIOrJIS;

        /// <summary>
        /// 单位
        /// </summary>
        private string _unitId;

        private int? _auditState;

        private string _auditEmpId;

        private Employee _auditEmp;

        /// <summary>
        /// 员工
        /// </summary>
        private Employee _employee;
        /// <summary>
        /// 产品
        /// </summary>
        private Product _product;
        /// <summary>
        /// 销售订单
        /// </summary>
        private InvoiceXO _invoice;

        /// <summary>
        /// 单位
        /// </summary>
        private ProductUnit _unit;

        #endregion

        #region Properties

        /// <summary>
        /// 主键编号
        /// </summary>
        public string ANSIPCImpactCheckID
        {
            get
            {
                return this._aNSIPCImpactCheckID;
            }
            set
            {
                this._aNSIPCImpactCheckID = value;
            }
        }

        /// <summary>
        /// 编号
        /// </summary>
        public string EmployeeId
        {
            get
            {
                return this._employeeId;
            }
            set
            {
                this._employeeId = value;
            }
        }

        /// <summary>
        /// 商品编号
        /// </summary>
        public string ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }

        /// <summary>
        /// 插入时间
        /// </summary>
        public DateTime? InsertTime
        {
            get
            {
                return this._insertTime;
            }
            set
            {
                this._insertTime = value;
            }
        }

        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? UpdateTime
        {
            get
            {
                return this._updateTime;
            }
            set
            {
                this._updateTime = value;
            }
        }

        /// <summary>
        /// 测试日期
        /// </summary>
        public DateTime? ANSIPCImpactCheckDate
        {
            get
            {
                return this._aNSIPCImpactCheckDate;
            }
            set
            {
                this._aNSIPCImpactCheckDate = value;
            }
        }

        /// <summary>
        /// 客户订单编号
        /// </summary>
        public string InvoiceCusXOId
        {
            get
            {
                return this._invoiceCusXOId;
            }
            set
            {
                this._invoiceCusXOId = value;
            }
        }

        /// <summary>
        /// 加工单据编号
        /// </summary>
        public string PronoteHeaderId
        {
            get
            {
                return this._pronoteHeaderId;
            }
            set
            {
                this._pronoteHeaderId = value;
            }
        }

        /// <summary>
        /// 冲击测试速度
        /// </summary>
        public string Spead
        {
            get
            {
                return this._spead;
            }
            set
            {
                this._spead = value;
            }
        }

        /// <summary>
        /// 备注
        /// </summary>
        public string ANSIPCImpactCheckDesc
        {
            get
            {
                return this._aNSIPCImpactCheckDesc;
            }
            set
            {
                this._aNSIPCImpactCheckDesc = value;
            }
        }

        /// <summary>
        /// 质检标准
        /// </summary>
        public string CheckStandard
        {
            get
            {
                return this._checkStandard;
            }
            set
            {
                this._checkStandard = value;
            }
        }

        /// <summary>
        /// 客户订单数量
        /// </summary>
        public double? InvoiceXOQuantity
        {
            get
            {
                return this._invoiceXOQuantity;
            }
            set
            {
                this._invoiceXOQuantity = value;
            }
        }

        /// <summary>
        /// 冲击力度
        /// </summary>
        public string PowerImpact
        {
            get
            {
                return this._powerImpact;
            }
            set
            {
                this._powerImpact = value;
            }
        }

        /// <summary>
        /// 坠球重量
        /// </summary>
        public string ZhuiQiuKG
        {
            get
            {
                return this._zhuiQiuKG;
            }
            set
            {
                this._zhuiQiuKG = value;
            }
        }

        /// <summary>
        /// 打印所用描述1
        /// </summary>
        public string PrintDesc1
        {
            get
            {
                return this._printDesc1;
            }
            set
            {
                this._printDesc1 = value;
            }
        }

        /// <summary>
        /// 检测数量
        /// </summary>
        public int? ANSIPCImpactCheckCount
        {
            get
            {
                return this._aNSIPCImpactCheckCount;
            }
            set
            {
                this._aNSIPCImpactCheckCount = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string InvoiceId
        {
            get
            {
                return this._invoiceId;
            }
            set
            {
                this._invoiceId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public bool? IsYuanZhuiZhuiLuo
        {
            get
            {
                return this._isYuanZhuiZhuiLuo;
            }
            set
            {
                this._isYuanZhuiZhuiLuo = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public bool? IsGaoSuChongJi
        {
            get
            {
                return this._isGaoSuChongJi;
            }
            set
            {
                this._isGaoSuChongJi = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public bool? IsNaiRanXing
        {
            get
            {
                return this._isNaiRanXing;
            }
            set
            {
                this._isNaiRanXing = value;
            }
        }

        /// <summary>
        /// 测试单类型
        /// </summary>
        public string ForANSIOrJIS
        {
            get { return _forANSIOrJIS; }
            set { _forANSIOrJIS = value; }
        }

        /// <summary>
        /// 单位
        /// </summary>
        public string UnitId
        {
            get { return _unitId; }
            set { _unitId = value; }
        }

        public int? AuditState
        {
            get
            {
                return this._auditState;
            }
            set
            {
                this._auditState = value;
            }
        }

        public virtual string AuditEmpId
        {
            get
            {
                return this._auditEmpId;

            }
            set
            {
                this._auditEmpId = value;
            }
        }

        public virtual Employee AuditEmp
        {
            get
            {
                return this._auditEmp;
            }
            set
            {
                this._auditEmp = value;
            }

        }

        /// <summary>
        /// 员工
        /// </summary>
        public virtual Employee Employee
        {
            get
            {
                return this._employee;
            }
            set
            {
                this._employee = value;
            }

        }
        /// <summary>
        /// 产品
        /// </summary>
        public virtual Product Product
        {
            get
            {
                return this._product;
            }
            set
            {
                this._product = value;
            }

        }
        /// <summary>
        /// 销售订单
        /// </summary>
        public virtual InvoiceXO Invoice
        {
            get
            {
                return this._invoice;
            }
            set
            {
                this._invoice = value;
            }

        }

        /// <summary>
        /// 单位
        /// </summary>
        public ProductUnit Unit
        {
            get { return _unit; }
            set { _unit = value; }
        }
        
        /// <summary>
        /// 主键编号
        /// </summary>
        public readonly static string PRO_ANSIPCImpactCheckID = "ANSIPCImpactCheckID";

        /// <summary>
        /// 编号
        /// </summary>
        public readonly static string PRO_EmployeeId = "EmployeeId";

        /// <summary>
        /// 商品编号
        /// </summary>
        public readonly static string PRO_ProductId = "ProductId";

        /// <summary>
        /// 插入时间
        /// </summary>
        public readonly static string PRO_InsertTime = "InsertTime";

        /// <summary>
        /// 修改时间
        /// </summary>
        public readonly static string PRO_UpdateTime = "UpdateTime";

        /// <summary>
        /// 测试日期
        /// </summary>
        public readonly static string PRO_ANSIPCImpactCheckDate = "ANSIPCImpactCheckDate";

        /// <summary>
        /// 客户订单编号
        /// </summary>
        public readonly static string PRO_InvoiceCusXOId = "InvoiceCusXOId";

        /// <summary>
        /// 加工单据编号
        /// </summary>
        public readonly static string PRO_PronoteHeaderId = "PronoteHeaderId";

        /// <summary>
        /// 冲击测试速度
        /// </summary>
        public readonly static string PRO_Spead = "Spead";

        /// <summary>
        /// 备注
        /// </summary>
        public readonly static string PRO_ANSIPCImpactCheckDesc = "ANSIPCImpactCheckDesc";

        /// <summary>
        /// 质检标准
        /// </summary>
        public readonly static string PRO_CheckStandard = "CheckStandard";

        /// <summary>
        /// 客户订单数量
        /// </summary>
        public readonly static string PRO_InvoiceXOQuantity = "InvoiceXOQuantity";

        /// <summary>
        /// 冲击力度
        /// </summary>
        public readonly static string PRO_PowerImpact = "PowerImpact";

        /// <summary>
        /// 坠球重量
        /// </summary>
        public readonly static string PRO_ZhuiQiuKG = "ZhuiQiuKG";

        /// <summary>
        /// 打印所用描述1
        /// </summary>
        public readonly static string PRO_PrintDesc1 = "PrintDesc1";

        /// <summary>
        /// 检测数量
        /// </summary>
        public readonly static string PRO_ANSIPCImpactCheckCount = "ANSIPCImpactCheckCount";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_InvoiceId = "InvoiceId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_IsYuanZhuiZhuiLuo = "IsYuanZhuiZhuiLuo";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_IsGaoSuChongJi = "IsGaoSuChongJi";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_IsNaiRanXing = "IsNaiRanXing";

        /// <summary>
        /// 测试单类型
        /// </summary>
        public readonly static string PRO_ForANSIOrJIS = "ForANSIOrJIS";

        /// <summary>
        /// 单位
        /// </summary>
        public readonly static string PRO_UnitId = "UnitId";

        public readonly static string PRO_AuditState = "AuditState";

        public readonly static string PRO_AuditEmpId = "AuditEmpId";
        #endregion
    }
}
