//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：BGHandbookRange.autogenerated.cs
// author: mayanjun
// create date：2013-4-17 15:13:05
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class BGHandbookRange
	{
		#region Data

		/// <summary>
		/// 主键
		/// </summary>
		private string _bGHandbookRangeId;
		
		/// <summary>
		/// 编号
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 审核人
		/// </summary>
		private string _auditEmpId;
		
		/// <summary>
		/// 插入时间
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 修改时间
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 企业名称、代码
		/// </summary>
		private string _companyNameAndId;
		
		/// <summary>
		/// 联系人电话
		/// </summary>
		private string _tel;
		
		/// <summary>
		/// 日期
		/// </summary>
		private DateTime? _bGHandbookRangeDate;
		
		/// <summary>
		/// 经办官员意见
		/// </summary>
		private string _opinion;
		
		/// <summary>
		/// 审核状态
		/// </summary>
		private int? _auditState;
		
		/// <summary>
		/// 成品料件类别
		/// </summary>
		private string _productType;
		
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _auditEmp;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 主键
		/// </summary>
		public string BGHandbookRangeId
		{
			get 
			{
				return this._bGHandbookRangeId;
			}
			set 
			{
				this._bGHandbookRangeId = value;
			}
		}

		/// <summary>
		/// 编号
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 审核人
		/// </summary>
		public string AuditEmpId
		{
			get 
			{
				return this._auditEmpId;
			}
			set 
			{
				this._auditEmpId = value;
			}
		}

		/// <summary>
		/// 插入时间
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 企业名称、代码
		/// </summary>
		public string CompanyNameAndId
		{
			get 
			{
				return this._companyNameAndId;
			}
			set 
			{
				this._companyNameAndId = value;
			}
		}

		/// <summary>
		/// 联系人电话
		/// </summary>
		public string Tel
		{
			get 
			{
				return this._tel;
			}
			set 
			{
				this._tel = value;
			}
		}

		/// <summary>
		/// 日期
		/// </summary>
		public DateTime? BGHandbookRangeDate
		{
			get 
			{
				return this._bGHandbookRangeDate;
			}
			set 
			{
				this._bGHandbookRangeDate = value;
			}
		}

		/// <summary>
		/// 经办官员意见
		/// </summary>
		public string Opinion
		{
			get 
			{
				return this._opinion;
			}
			set 
			{
				this._opinion = value;
			}
		}

		/// <summary>
		/// 审核状态
		/// </summary>
		public int? AuditState
		{
			get 
			{
				return this._auditState;
			}
			set 
			{
				this._auditState = value;
			}
		}

		/// <summary>
		/// 成品料件类别
		/// </summary>
		public string ProductType
		{
			get 
			{
				return this._productType;
			}
			set 
			{
				this._productType = value;
			}
		}
	
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee AuditEmp
		{
			get
			{
				return this._auditEmp;
			}
			set
			{
				this._auditEmp = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
			
		}
		/// <summary>
		/// 主键
		/// </summary>
		public readonly static string PRO_BGHandbookRangeId = "BGHandbookRangeId";
		
		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PRO_EmployeeId = "EmployeeId";
		
		/// <summary>
		/// 审核人
		/// </summary>
		public readonly static string PRO_AuditEmpId = "AuditEmpId";
		
		/// <summary>
		/// 插入时间
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 企业名称、代码
		/// </summary>
		public readonly static string PRO_CompanyNameAndId = "CompanyNameAndId";
		
		/// <summary>
		/// 联系人电话
		/// </summary>
		public readonly static string PRO_Tel = "Tel";
		
		/// <summary>
		/// 日期
		/// </summary>
		public readonly static string PRO_BGHandbookRangeDate = "BGHandbookRangeDate";
		
		/// <summary>
		/// 经办官员意见
		/// </summary>
		public readonly static string PRO_Opinion = "Opinion";
		
		/// <summary>
		/// 审核状态
		/// </summary>
		public readonly static string PRO_AuditState = "AuditState";
		
		/// <summary>
		/// 成品料件类别
		/// </summary>
		public readonly static string PRO_ProductType = "ProductType";
		

		#endregion
	}
}
