//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：BGHandbookDepotIn.autogenerated.cs
// author: mayanjun
// create date：2013/12/27 13:34:12
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class BGHandbookDepotIn
    {
        #region Data

        /// <summary>
        /// 
        /// </summary>
        private string _bGHandbookDepotInId;

        /// <summary>
        /// 
        /// </summary>
        private DateTime? _bGHandbookDepotInDate;

        /// <summary>
        /// 
        /// </summary>
        private string _bGHangbookId;

        /// <summary>
        /// 
        /// </summary>
        private DateTime? _insertTime;

        /// <summary>
        /// 
        /// </summary>
        private DateTime? _updateTime;


        #endregion

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string BGHandbookDepotInId
        {
            get
            {
                return this._bGHandbookDepotInId;
            }
            set
            {
                this._bGHandbookDepotInId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public DateTime? BGHandbookDepotInDate
        {
            get
            {
                return this._bGHandbookDepotInDate;
            }
            set
            {
                this._bGHandbookDepotInDate = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string BGHangbookId
        {
            get
            {
                return this._bGHangbookId;
            }
            set
            {
                this._bGHangbookId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public DateTime? InsertTime
        {
            get
            {
                return this._insertTime;
            }
            set
            {
                this._insertTime = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public DateTime? UpdateTime
        {
            get
            {
                return this._updateTime;
            }
            set
            {
                this._updateTime = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_BGHandbookDepotInId = "BGHandbookDepotInId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_BGHandbookDepotInDate = "BGHandbookDepotInDate";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_BGHangbookId = "BGHangbookId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_InsertTime = "InsertTime";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_UpdateTime = "UpdateTime";


        #endregion
    }
}
