//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：BGHandbookDepotOutDetail.autogenerated.cs
// author: mayanjun
// create date：2014/3/5 16:32:47
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class BGHandbookDepotOutDetail
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _bGHandbookDepotOutDetailId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _bGHandbookDepotOutId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _bGHandbookDepotOutDetailDate;
		
		/// <summary>
		/// 手册料件号
		/// </summary>
		private int? _bGHandbookProductId;
		
		/// <summary>
		/// 手册料件名称
		/// </summary>
		private string _bGHandbookProductName;
		
		/// <summary>
		/// 数量
		/// </summary>
		private double? _depotOutQuantity;
		
		/// <summary>
		/// 单位
		/// </summary>
		private string _productUnitId;
		
		/// <summary>
		/// 报关单号
		/// </summary>
		private string _declareCustomsId;
		
		/// <summary>
		/// 
		/// </summary>
		private BGHandbookDepotOut _bGHandbookDepotOut;
		/// <summary>
		/// 单位
		/// </summary>
		private ProductUnit _productUnit;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string BGHandbookDepotOutDetailId
		{
			get 
			{
				return this._bGHandbookDepotOutDetailId;
			}
			set 
			{
				this._bGHandbookDepotOutDetailId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string BGHandbookDepotOutId
		{
			get 
			{
				return this._bGHandbookDepotOutId;
			}
			set 
			{
				this._bGHandbookDepotOutId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? BGHandbookDepotOutDetailDate
		{
			get 
			{
				return this._bGHandbookDepotOutDetailDate;
			}
			set 
			{
				this._bGHandbookDepotOutDetailDate = value;
			}
		}

		/// <summary>
		/// 手册料件号
		/// </summary>
		public int? BGHandbookProductId
		{
			get 
			{
				return this._bGHandbookProductId;
			}
			set 
			{
				this._bGHandbookProductId = value;
			}
		}

		/// <summary>
		/// 手册料件名称
		/// </summary>
		public string BGHandbookProductName
		{
			get 
			{
				return this._bGHandbookProductName;
			}
			set 
			{
				this._bGHandbookProductName = value;
			}
		}

		/// <summary>
		/// 数量
		/// </summary>
		public double? DepotOutQuantity
		{
			get 
			{
				return this._depotOutQuantity;
			}
			set 
			{
				this._depotOutQuantity = value;
			}
		}

		/// <summary>
		/// 单位
		/// </summary>
		public string ProductUnitId
		{
			get 
			{
				return this._productUnitId;
			}
			set 
			{
				this._productUnitId = value;
			}
		}

		/// <summary>
		/// 报关单号
		/// </summary>
		public string DeclareCustomsId
		{
			get 
			{
				return this._declareCustomsId;
			}
			set 
			{
				this._declareCustomsId = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public virtual BGHandbookDepotOut BGHandbookDepotOut
		{
			get
			{
				return this._bGHandbookDepotOut;
			}
			set
			{
				this._bGHandbookDepotOut = value;
			}
			
		}
		/// <summary>
		/// 单位
		/// </summary>
		public virtual ProductUnit ProductUnit
		{
			get
			{
				return this._productUnit;
			}
			set
			{
				this._productUnit = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_BGHandbookDepotOutDetailId = "BGHandbookDepotOutDetailId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_BGHandbookDepotOutId = "BGHandbookDepotOutId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_BGHandbookDepotOutDetailDate = "BGHandbookDepotOutDetailDate";
		
		/// <summary>
		/// 手册料件号
		/// </summary>
		public readonly static string PRO_BGHandbookProductId = "BGHandbookProductId";
		
		/// <summary>
		/// 手册料件名称
		/// </summary>
		public readonly static string PRO_BGHandbookProductName = "BGHandbookProductName";
		
		/// <summary>
		/// 数量
		/// </summary>
		public readonly static string PRO_DepotOutQuantity = "DepotOutQuantity";
		
		/// <summary>
		/// 单位
		/// </summary>
		public readonly static string PRO_ProductUnitId = "ProductUnitId";
		
		/// <summary>
		/// 报关单号
		/// </summary>
		public readonly static string PRO_DeclareCustomsId = "DeclareCustomsId";
		

		#endregion
	}
}
