//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ConveyanceMethod.autogenerated.cs
// author: mayanjun
// create date：2010-8-9 15:00:28
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class ConveyanceMethod
	{
		#region Data

		/// <summary>
		/// 编号
		/// </summary>
		private string _conveyanceMethodId;
		
		/// <summary>
		/// 货运方式名称
		/// </summary>
		private string _conveyanceMethodName;
		
		/// <summary>
		/// 编号1
		/// </summary>
		private string _id;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 编号
		/// </summary>
		public string ConveyanceMethodId
		{
			get 
			{
				return this._conveyanceMethodId;
			}
			set 
			{
				this._conveyanceMethodId = value;
			}
		}

		/// <summary>
		/// 货运方式名称
		/// </summary>
		public string ConveyanceMethodName
		{
			get 
			{
				return this._conveyanceMethodName;
			}
			set 
			{
				this._conveyanceMethodName = value;
			}
		}

		/// <summary>
		/// 编号1
		/// </summary>
		public string Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}
	
		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PROPERTY_CONVEYANCEMETHODID = "ConveyanceMethodId";
		
		/// <summary>
		/// 货运方式名称
		/// </summary>
		public readonly static string PROPERTY_CONVEYANCEMETHODNAME = "ConveyanceMethodName";
		
		/// <summary>
		/// 编号1
		/// </summary>
		public readonly static string PROPERTY_ID = "Id";
		

		#endregion
	}
}
