//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：DepotIn.autogenerated.cs
// author: mayanjun
// create date：2011-3-17 17:41:08
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class DepotIn
	{
		#region Data

		/// <summary>
		/// 编号
		/// </summary>
		private string _depotInId;
		
		/// <summary>
		/// 操作人
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 入库人
		/// </summary>
		private string _employee0Id;
		
		/// <summary>
		/// 库房编号
		/// </summary>
		private string _depotId;
		
		/// <summary>
		/// 供应商编号
		/// </summary>
		private string _supplierId;
		
		/// <summary>
		/// 插入时间
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 修改时间
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 日期
		/// </summary>
		private DateTime? _depotInDate;
		
		/// <summary>
		/// 说明
		/// </summary>
		private string _description;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productCategoryId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _produceInDepotId;

        private int? _auditState;

        private string _auditEmpId;

        private Employee _auditEmp;
		
		/// <summary>
		/// 库房
		/// </summary>
		private Depot _depot;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee0;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee;
		/// <summary>
		/// 供应商
		/// </summary>
		private Supplier _supplier;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 编号
		/// </summary>
		public string DepotInId
		{
			get 
			{
				return this._depotInId;
			}
			set 
			{
				this._depotInId = value;
			}
		}

		/// <summary>
		/// 操作人
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 入库人
		/// </summary>
		public string Employee0Id
		{
			get 
			{
				return this._employee0Id;
			}
			set 
			{
				this._employee0Id = value;
			}
		}

		/// <summary>
		/// 库房编号
		/// </summary>
		public string DepotId
		{
			get 
			{
				return this._depotId;
			}
			set 
			{
				this._depotId = value;
			}
		}

		/// <summary>
		/// 供应商编号
		/// </summary>
		public string SupplierId
		{
			get 
			{
				return this._supplierId;
			}
			set 
			{
				this._supplierId = value;
			}
		}

		/// <summary>
		/// 插入时间
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 日期
		/// </summary>
		public DateTime? DepotInDate
		{
			get 
			{
				return this._depotInDate;
			}
			set 
			{
				this._depotInDate = value;
			}
		}

		/// <summary>
		/// 说明
		/// </summary>
		public string Description
		{
			get 
			{
				return this._description;
			}
			set 
			{
				this._description = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductCategoryId
		{
			get 
			{
				return this._productCategoryId;
			}
			set 
			{
				this._productCategoryId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProduceInDepotId
		{
			get 
			{
				return this._produceInDepotId;
			}
			set 
			{
				this._produceInDepotId = value;
			}
		}

        public int? AuditState
        {
            get
            {
                return this._auditState;
            }
            set
            {
                this._auditState = value;
            }
        }

        public virtual string AuditEmpId
        {
            get
            {
                return this._auditEmpId;

            }
            set
            {
                this._auditEmpId = value;
            }
        }

        public virtual Employee AuditEmp
        {
            get
            {
                return this._auditEmp;
            }
            set
            {
                this._auditEmp = value;
            }

        }
	
		/// <summary>
		/// 库房
		/// </summary>
		public virtual Depot Depot
		{
			get
			{
				return this._depot;
			}
			set
			{
				this._depot = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee0
		{
			get
			{
				return this._employee0;
			}
			set
			{
				this._employee0 = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
			
		}
		/// <summary>
		/// 供应商
		/// </summary>
		public virtual Supplier Supplier
		{
			get
			{
				return this._supplier;
			}
			set
			{
				this._supplier = value;
			}
			
		}
		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PRO_DepotInId = "DepotInId";
		
		/// <summary>
		/// 操作人
		/// </summary>
		public readonly static string PRO_EmployeeId = "EmployeeId";
		
		/// <summary>
		/// 入库人
		/// </summary>
		public readonly static string PRO_Employee0Id = "Employee0Id";
		
		/// <summary>
		/// 库房编号
		/// </summary>
		public readonly static string PRO_DepotId = "DepotId";
		
		/// <summary>
		/// 供应商编号
		/// </summary>
		public readonly static string PRO_SupplierId = "SupplierId";
		
		/// <summary>
		/// 插入时间
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 日期
		/// </summary>
		public readonly static string PRO_DepotInDate = "DepotInDate";
		
		/// <summary>
		/// 说明
		/// </summary>
		public readonly static string PRO_Description = "Description";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductCategoryId = "ProductCategoryId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProduceInDepotId = "ProduceInDepotId";

        public readonly static string PRO_AuditState = "AuditState";

        public readonly static string PRO_AuditEmpId = "AuditEmpId";

		#endregion
	}
}
