//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：FreightedCompany.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:12
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class FreightedCompany
	{
		#region Data

		/// <summary>
		/// 货运公司编号
		/// </summary>
		private string _freightedCompanyId;
		
		/// <summary>
		/// 插入时间
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 修改时间
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 页面编号
		/// </summary>
		private string _id;
		
		/// <summary>
		/// 名称
		/// </summary>
		private string _freightedCompanyName;
		
		/// <summary>
		/// 地址
		/// </summary>
		private string _freightedCompanyAddress;
		
		/// <summary>
		/// 联系电话
		/// </summary>
		private string _telphone;
		
		/// <summary>
		/// 说明
		/// </summary>
		private string _description;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 货运公司编号
		/// </summary>
		public string FreightedCompanyId
		{
			get 
			{
				return this._freightedCompanyId;
			}
			set 
			{
				this._freightedCompanyId = value;
			}
		}

		/// <summary>
		/// 插入时间
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 页面编号
		/// </summary>
		public string Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}

		/// <summary>
		/// 名称
		/// </summary>
		public string FreightedCompanyName
		{
			get 
			{
				return this._freightedCompanyName;
			}
			set 
			{
				this._freightedCompanyName = value;
			}
		}

		/// <summary>
		/// 地址
		/// </summary>
		public string FreightedCompanyAddress
		{
			get 
			{
				return this._freightedCompanyAddress;
			}
			set 
			{
				this._freightedCompanyAddress = value;
			}
		}

		/// <summary>
		/// 联系电话
		/// </summary>
		public string Telphone
		{
			get 
			{
				return this._telphone;
			}
			set 
			{
				this._telphone = value;
			}
		}

		/// <summary>
		/// 说明
		/// </summary>
		public string Description
		{
			get 
			{
				return this._description;
			}
			set 
			{
				this._description = value;
			}
		}
	
		/// <summary>
		/// 货运公司编号
		/// </summary>
		public readonly static string PROPERTY_FREIGHTEDCOMPANYID = "FreightedCompanyId";
		
		/// <summary>
		/// 插入时间
		/// </summary>
		public readonly static string PROPERTY_INSERTTIME = "InsertTime";
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public readonly static string PROPERTY_UPDATETIME = "UpdateTime";
		
		/// <summary>
		/// 页面编号
		/// </summary>
		public readonly static string PROPERTY_ID = "Id";
		
		/// <summary>
		/// 名称
		/// </summary>
		public readonly static string PROPERTY_FREIGHTEDCOMPANYNAME = "FreightedCompanyName";
		
		/// <summary>
		/// 地址
		/// </summary>
		public readonly static string PROPERTY_FREIGHTEDCOMPANYADDRESS = "FreightedCompanyAddress";
		
		/// <summary>
		/// 联系电话
		/// </summary>
		public readonly static string PROPERTY_TELPHONE = "Telphone";
		
		/// <summary>
		/// 说明
		/// </summary>
		public readonly static string PROPERTY_DESCRIPTION = "Description";
		

		#endregion
	}
}
