//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IncomingKind.autogenerated.cs
// author: peidun
// create date：2010-4-7 16:05:17
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class IncomingKind
	{
		#region Data

		/// <summary>
		/// 其他收入类型编号
		/// </summary>
		private string _incomingKindId;
		
		/// <summary>
		/// 插入时间
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 修改时间
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 其他收入类型名称
		/// </summary>
		private string _incomingKindName;
		
		/// <summary>
		/// 其他收入类型说明
		/// </summary>
		private string _incomingKindDescription;
		
		/// <summary>
		/// 
		/// </summary>
		private string _id;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 其他收入类型编号
		/// </summary>
		public string IncomingKindId
		{
			get 
			{
				return this._incomingKindId;
			}
			set 
			{
				this._incomingKindId = value;
			}
		}

		/// <summary>
		/// 插入时间
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 其他收入类型名称
		/// </summary>
		public string IncomingKindName
		{
			get 
			{
				return this._incomingKindName;
			}
			set 
			{
				this._incomingKindName = value;
			}
		}

		/// <summary>
		/// 其他收入类型说明
		/// </summary>
		public string IncomingKindDescription
		{
			get 
			{
				return this._incomingKindDescription;
			}
			set 
			{
				this._incomingKindDescription = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}
	
		/// <summary>
		/// 其他收入类型编号
		/// </summary>
		public readonly static string PROPERTY_INCOMINGKINDID = "IncomingKindId";
		
		/// <summary>
		/// 插入时间
		/// </summary>
		public readonly static string PROPERTY_INSERTTIME = "InsertTime";
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public readonly static string PROPERTY_UPDATETIME = "UpdateTime";
		
		/// <summary>
		/// 其他收入类型名称
		/// </summary>
		public readonly static string PROPERTY_INCOMINGKINDNAME = "IncomingKindName";
		
		/// <summary>
		/// 其他收入类型说明
		/// </summary>
		public readonly static string PROPERTY_INCOMINGKINDDESCRIPTION = "IncomingKindDescription";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_ID = "Id";
		

		#endregion
	}
}
