//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceXJPackageDetails.autogenerated.cs
// author: mayanjun
// create date：2012-8-14 17:52:28
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class InvoiceXJPackageDetails
    {
        #region Data

        /// <summary>
        /// 主键编号
        /// </summary>
        private string _invoiceXJPackageDetailsId;

        /// <summary>
        /// 商品编号
        /// </summary>
        private string _productId;

        /// <summary>
        /// 单据编号
        /// </summary>
        private string _invoiceId;

        /// <summary>
        /// 数量
        /// </summary>
        private double? _quantity;

        /// <summary>
        /// 使用数量
        /// </summary>
        private double? _useQuantity;

        /// <summary>
        /// 损耗率
        /// </summary>
        private double? _consumeRate;

        /// <summary>
        /// 生效日期
        /// </summary>
        private DateTime? _effectsDate;

        /// <summary>
        /// 失效日期
        /// </summary>
        private DateTime? _expiringDate;

        /// <summary>
        /// 单位
        /// </summary>
        private string _packageUnit;

        /// <summary>
        /// 描述
        /// </summary>
        private string _description;

        /// <summary>
        /// 序号
        /// </summary>
        private int? _inumber;

        /// <summary>
        /// 包装价格
        /// </summary>
        private decimal? _packagePrice;

        /// <summary>
        /// 包材类型
        /// </summary>
        private string _InvoiceXJPackageDetailsType;

        /// <summary>
        /// 成本一
        /// </summary>
        private double? _InvoiceXJProcessCB1;

        /// <summary>
        /// 成本二
        /// </summary>
        private double? _InvoiceXJProcessCB2;

        private string _ProcessCategoryId;

        private string _SupplierId;

        /// <summary>
        /// 数量
        /// </summary>
        private double? _InvoiceXJPackageDetailsQuantity;


        private string _ProductName;

        /// <summary>
        /// 加工单价(真)
        /// </summary>
        private double? _DanJia;
        




        /// <summary>
        /// 销售报价单
        /// </summary>
        private InvoiceXJ _invoice;
        /// <summary>
        /// 产品
        /// </summary>
        private Product _product;

        private ProcessCategory _ProcessCategory;

        private Supplier _Supplier;
        #endregion

        #region Properties

        /// <summary>
        /// 主键编号
        /// </summary>
        public string InvoiceXJPackageDetailsId
        {
            get
            {
                return this._invoiceXJPackageDetailsId;
            }
            set
            {
                this._invoiceXJPackageDetailsId = value;
            }
        }

        /// <summary>
        /// 商品编号
        /// </summary>
        public string ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }

        /// <summary>
        /// 单据编号
        /// </summary>
        public string InvoiceId
        {
            get
            {
                return this._invoiceId;
            }
            set
            {
                this._invoiceId = value;
            }
        }

        /// <summary>
        /// 数量
        /// </summary>
        public double? Quantity
        {
            get
            {
                return this._quantity;
            }
            set
            {
                this._quantity = value;
            }
        }

        /// <summary>
        /// 使用数量
        /// </summary>
        public double? UseQuantity
        {
            get
            {
                return this._useQuantity;
            }
            set
            {
                this._useQuantity = value;
            }
        }

        /// <summary>
        /// 损耗率
        /// </summary>
        public double? ConsumeRate
        {
            get
            {
                return this._consumeRate;
            }
            set
            {
                this._consumeRate = value;
            }
        }

        /// <summary>
        /// 生效日期
        /// </summary>
        public DateTime? EffectsDate
        {
            get
            {
                return this._effectsDate;
            }
            set
            {
                this._effectsDate = value;
            }
        }

        /// <summary>
        /// 失效日期
        /// </summary>
        public DateTime? ExpiringDate
        {
            get
            {
                return this._expiringDate;
            }
            set
            {
                this._expiringDate = value;
            }
        }

        /// <summary>
        /// 单位
        /// </summary>
        public string PackageUnit
        {
            get
            {
                return this._packageUnit;
            }
            set
            {
                this._packageUnit = value;
            }
        }

        /// <summary>
        /// 描述
        /// </summary>
        public string Description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }

        /// <summary>
        /// 序号
        /// </summary>
        public int? Inumber
        {
            get
            {
                return this._inumber;
            }
            set
            {
                this._inumber = value;
            }
        }

        /// <summary>
        /// 包装价格
        /// </summary>
        public decimal? PackagePrice
        {
            get
            {
                return this._packagePrice;
            }
            set
            {
                this._packagePrice = value;
            }
        }

        /// <summary>
        /// 包材类型
        /// </summary>
        public string InvoiceXJPackageDetailsType
        {
            get { return _InvoiceXJPackageDetailsType; }
            set { _InvoiceXJPackageDetailsType = value; }
        }

        /// <summary>
        /// 成本一
        /// </summary>
        public double? InvoiceXJProcessCB1
        {
            get { return _InvoiceXJProcessCB1; }
            set { _InvoiceXJProcessCB1 = value; }
        }
        /// <summary>
        /// 成本二
        /// </summary>
        public double? InvoiceXJProcessCB2
        {
            get { return _InvoiceXJProcessCB2; }
            set { _InvoiceXJProcessCB2 = value; }
        }

        public string ProcessCategoryId
        {
            get { return _ProcessCategoryId; }
            set { _ProcessCategoryId = value; }
        }

        public string SupplierId
        {
            get { return _SupplierId; }
            set { _SupplierId = value; }
        }

        /// <summary>
        /// 数量
        /// </summary>
        public double? InvoiceXJPackageDetailsQuantity
        {
            get { return _InvoiceXJPackageDetailsQuantity; }
            set { _InvoiceXJPackageDetailsQuantity = value; }
        }

        public string ProductName
        {
            get { return _ProductName; }
            set { _ProductName = value; }
        }

        /// <summary>
        /// 加工单价(真)
        /// </summary>
        public double? DanJia
        {
            get { return _DanJia; }
            set { _DanJia = value; }
        }

        /// <summary>
        /// 销售报价单
        /// </summary>
        public virtual InvoiceXJ Invoice
        {
            get
            {
                return this._invoice;
            }
            set
            {
                this._invoice = value;
            }

        }
        /// <summary>
        /// 产品
        /// </summary>
        public virtual Product Product
        {
            get
            {
                return this._product;
            }
            set
            {
                this._product = value;
            }

        }

        public ProcessCategory ProcessCategory
        {
            get { return _ProcessCategory; }
            set { _ProcessCategory = value; }
        }

        public Supplier Supplier
        {
            get { return _Supplier; }
            set { _Supplier = value; }
        }
        /// <summary>
        /// 主键编号
        /// </summary>
        public readonly static string PRO_InvoiceXJPackageDetailsId = "InvoiceXJPackageDetailsId";

        /// <summary>
        /// 商品编号
        /// </summary>
        public readonly static string PRO_ProductId = "ProductId";

        /// <summary>
        /// 单据编号
        /// </summary>
        public readonly static string PRO_InvoiceId = "InvoiceId";

        /// <summary>
        /// 数量
        /// </summary>
        public readonly static string PRO_Quantity = "Quantity";

        /// <summary>
        /// 使用数量
        /// </summary>
        public readonly static string PRO_UseQuantity = "UseQuantity";

        /// <summary>
        /// 损耗率
        /// </summary>
        public readonly static string PRO_ConsumeRate = "ConsumeRate";

        /// <summary>
        /// 生效日期
        /// </summary>
        public readonly static string PRO_EffectsDate = "EffectsDate";

        /// <summary>
        /// 失效日期
        /// </summary>
        public readonly static string PRO_ExpiringDate = "ExpiringDate";

        /// <summary>
        /// 单位
        /// </summary>
        public readonly static string PRO_PackageUnit = "PackageUnit";

        /// <summary>
        /// 描述
        /// </summary>
        public readonly static string PRO_Description = "Description";

        /// <summary>
        /// 序号
        /// </summary>
        public readonly static string PRO_Inumber = "Inumber";

        /// <summary>
        /// 包装价格
        /// </summary>
        public readonly static string PRO_PackagePrice = "PackagePrice";

        /// <summary>
        /// 包材类型
        /// </summary>
        public readonly static string PRO_InvoiceXJPackageDetailsType = "InvoiceXJPackageDetailsType";

        /// <summary>
        /// 成本一
        /// </summary>
        public readonly static string PRO_InvoiceXJProcessCB1 = "InvoiceXJProcessCB1";

        /// <summary>
        /// 成本二
        /// </summary>
        public readonly static string PRO_InvoiceXJProcessCB2 = "InvoiceXJProcessCB2";

        /// <summary>
        /// 数量
        /// </summary>
        public readonly static string PRO_InvoiceXJPackageDetailsQuantity = "InvoiceXJPackageDetailsQuantity";

        public readonly static string PRO_ProductName = "ProductName";

        public readonly static string PRO_DanJia = "DanJia";

        
        #endregion
    }
}
