//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceHR.autogenerated.cs
// author: mayanjun
// create date：2010-11-20 11:44:18
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class InvoiceHR
	{
		#region Data

		/// <summary>
		/// 客户编号
		/// </summary>
		private string _customerId;
		
		/// <summary>
		/// 借入单数量
		/// </summary>
		private double? _invoiceHRQuantity;
		
		/// <summary>
		/// 
		/// </summary>
		private string _jcInvoiceId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _depotId;
		
		/// <summary>
		/// 客户
		/// </summary>
		private Customer _customer;
		/// <summary>
		/// 库房
		/// </summary>
		private Depot _depot;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 客户编号
		/// </summary>
		public string CustomerId
		{
			get 
			{
				return this._customerId;
			}
			set 
			{
				this._customerId = value;
			}
		}

		/// <summary>
		/// 借入单数量
		/// </summary>
		public double? InvoiceHRQuantity
		{
			get 
			{
				return this._invoiceHRQuantity;
			}
			set 
			{
				this._invoiceHRQuantity = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string JcInvoiceId
		{
			get 
			{
				return this._jcInvoiceId;
			}
			set 
			{
				this._jcInvoiceId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string DepotId
		{
			get 
			{
				return this._depotId;
			}
			set 
			{
				this._depotId = value;
			}
		}
	
		/// <summary>
		/// 客户
		/// </summary>
		public virtual Customer Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
			
		}
		/// <summary>
		/// 库房
		/// </summary>
		public virtual Depot Depot
		{
			get
			{
				return this._depot;
			}
			set
			{
				this._depot = value;
			}
			
		}
		/// <summary>
		/// 客户编号
		/// </summary>
		public readonly static string PRO_CustomerId = "CustomerId";
		
		/// <summary>
		/// 借入单数量
		/// </summary>
		public readonly static string PRO_InvoiceHRQuantity = "InvoiceHRQuantity";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_JcInvoiceId = "JcInvoiceId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_DepotId = "DepotId";
		

		#endregion
	}
}
