//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：MPSdetails.autogenerated.cs
// author: mayanjun
// create date：2011-08-15 11:07:42
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class MPSdetails
	{
		#region Data

		/// <summary>
		/// 明细编号
		/// </summary>
		private string _mPSdetailsId;
		
		/// <summary>
		/// 商品编号
		/// </summary>
		private string _productId;
		
		/// <summary>
		/// 编号
		/// </summary>
		private string _mPSheaderId;
		
		/// <summary>
		/// 明细数量
		/// </summary>
		private double? _mPSdetailssum;
		
		/// <summary>
		/// 明细说明
		/// </summary>
		private string _mPSdetailsdes;
		
		/// <summary>
		/// 单位
		/// </summary>
		private string _productUnit;
		
		/// <summary>
		/// 销售订单编号
		/// </summary>
		private string _invoiceXOId;
		
		/// <summary>
		/// 库存
		/// </summary>
		private double? _productStock;
		
		/// <summary>
		/// 客户编号
		/// </summary>
		private string _customerId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _invoiceXODetailId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _primaryKeyId;
		
		/// <summary>
		/// 
		/// </summary>
		private double? _invoiceXODetailSum;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _checkeds;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _mPSEndState;
		
		/// <summary>
		/// 
		/// </summary>
		private double? _mPSHasSingleSum;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _isPronoteHeader;
		
		/// <summary>
		/// 
		/// </summary>
		private int? _inumber;
		
		/// <summary>
		/// 预扣库存
		/// </summary>
		private double? _yuKouStock;

        /// <summary>
        /// 手册号
        /// </summary>
        private string _handbookId;

        /// <summary>
        /// 手册项号
        /// </summary>
        private string _handbookProductId;
		
		/// <summary>
		/// 客户产品
		/// </summary>
		private CustomerProducts _primaryKey;
		/// <summary>
		/// 主生产计划头
		/// </summary>
		private MPSheader _mPSheader;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _product;
		/// <summary>
		/// 客户
		/// </summary>
		private Customer _customer;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 明细编号
		/// </summary>
		public string MPSdetailsId
		{
			get 
			{
				return this._mPSdetailsId;
			}
			set 
			{
				this._mPSdetailsId = value;
			}
		}

		/// <summary>
		/// 商品编号
		/// </summary>
		public string ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 编号
		/// </summary>
		public string MPSheaderId
		{
			get 
			{
				return this._mPSheaderId;
			}
			set 
			{
				this._mPSheaderId = value;
			}
		}

		/// <summary>
		/// 明细数量
		/// </summary>
		public double? MPSdetailssum
		{
			get 
			{
				return this._mPSdetailssum;
			}
			set 
			{
				this._mPSdetailssum = value;
			}
		}

		/// <summary>
		/// 明细说明
		/// </summary>
		public string MPSdetailsdes
		{
			get 
			{
				return this._mPSdetailsdes;
			}
			set 
			{
				this._mPSdetailsdes = value;
			}
		}

		/// <summary>
		/// 单位
		/// </summary>
		public string ProductUnit
		{
			get 
			{
				return this._productUnit;
			}
			set 
			{
				this._productUnit = value;
			}
		}

		/// <summary>
		/// 销售订单编号
		/// </summary>
		public string InvoiceXOId
		{
			get 
			{
				return this._invoiceXOId;
			}
			set 
			{
				this._invoiceXOId = value;
			}
		}

		/// <summary>
		/// 库存
		/// </summary>
		public double? ProductStock
		{
			get 
			{
				return this._productStock;
			}
			set 
			{
				this._productStock = value;
			}
		}

		/// <summary>
		/// 客户编号
		/// </summary>
		public string CustomerId
		{
			get 
			{
				return this._customerId;
			}
			set 
			{
				this._customerId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string InvoiceXODetailId
		{
			get 
			{
				return this._invoiceXODetailId;
			}
			set 
			{
				this._invoiceXODetailId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PrimaryKeyId
		{
			get 
			{
				return this._primaryKeyId;
			}
			set 
			{
				this._primaryKeyId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public double? InvoiceXODetailSum
		{
			get 
			{
				return this._invoiceXODetailSum;
			}
			set 
			{
				this._invoiceXODetailSum = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Checkeds
		{
			get 
			{
				return this._checkeds;
			}
			set 
			{
				this._checkeds = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? MPSEndState
		{
			get 
			{
				return this._mPSEndState;
			}
			set 
			{
				this._mPSEndState = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public double? MPSHasSingleSum
		{
			get 
			{
				return this._mPSHasSingleSum;
			}
			set 
			{
				this._mPSHasSingleSum = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? IsPronoteHeader
		{
			get 
			{
				return this._isPronoteHeader;
			}
			set 
			{
				this._isPronoteHeader = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int? Inumber
		{
			get 
			{
				return this._inumber;
			}
			set 
			{
				this._inumber = value;
			}
		}

		/// <summary>
		/// 预扣库存
		/// </summary>
		public double? YuKouStock
		{
			get 
			{
				return this._yuKouStock;
			}
			set 
			{
				this._yuKouStock = value;
			}
        }

        /// <summary>
        /// 手册号
        /// </summary>
        public string HandbookId
        {
            get { return _handbookId; }
            set { _handbookId = value; }
        }

        /// <summary>
        /// 手册项号
        /// </summary>
        public string HandbookProductId
        {
            get { return _handbookProductId; }
            set { _handbookProductId = value; }
        }
	
		/// <summary>
		/// 客户产品
		/// </summary>
		public virtual CustomerProducts PrimaryKey
		{
			get
			{
				return this._primaryKey;
			}
			set
			{
				this._primaryKey = value;
			}
			
		}
		/// <summary>
		/// 主生产计划头
		/// </summary>
		public virtual MPSheader MPSheader
		{
			get
			{
				return this._mPSheader;
			}
			set
			{
				this._mPSheader = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
			
		}
		/// <summary>
		/// 客户
		/// </summary>
		public virtual Customer Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
			
		}
		/// <summary>
		/// 明细编号
		/// </summary>
		public readonly static string PRO_MPSdetailsId = "MPSdetailsId";
		
		/// <summary>
		/// 商品编号
		/// </summary>
		public readonly static string PRO_ProductId = "ProductId";
		
		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PRO_MPSheaderId = "MPSheaderId";
		
		/// <summary>
		/// 明细数量
		/// </summary>
		public readonly static string PRO_MPSdetailssum = "MPSdetailssum";
		
		/// <summary>
		/// 明细说明
		/// </summary>
		public readonly static string PRO_MPSdetailsdes = "MPSdetailsdes";
		
		/// <summary>
		/// 单位
		/// </summary>
		public readonly static string PRO_ProductUnit = "ProductUnit";
		
		/// <summary>
		/// 销售订单编号
		/// </summary>
		public readonly static string PRO_InvoiceXOId = "InvoiceXOId";
		
		/// <summary>
		/// 库存
		/// </summary>
		public readonly static string PRO_ProductStock = "ProductStock";
		
		/// <summary>
		/// 客户编号
		/// </summary>
		public readonly static string PRO_CustomerId = "CustomerId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceXODetailId = "InvoiceXODetailId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PrimaryKeyId = "PrimaryKeyId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceXODetailSum = "InvoiceXODetailSum";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Checkeds = "Checkeds";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_MPSEndState = "MPSEndState";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_MPSHasSingleSum = "MPSHasSingleSum";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_IsPronoteHeader = "IsPronoteHeader";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Inumber = "Inumber";
		
		/// <summary>
		/// 预扣库存
		/// </summary>
		public readonly static string PRO_YuKouStock = "YuKouStock";


        public readonly static string PRO_HandbookId = "HandbookId";

        public readonly static string PRO_HandbookProductId = "HandbookProductId";


		#endregion
	}
}
