//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCDoubleImpactCheck.autogenerated.cs
// author: mayanjun
// create date：2011-12-22 09:51:52
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class PCDoubleImpactCheck
    {
        #region Data

        /// <summary>
        /// 
        /// </summary>
        private string _pCDoubleImpactCheckID;

        /// <summary>
        /// 
        /// </summary>
        private string _productId;

        /// <summary>
        /// 
        /// </summary>
        private string _employeeId;

        /// <summary>
        /// 
        /// </summary>
        private DateTime? _insertTime;

        /// <summary>
        /// 
        /// </summary>
        private DateTime? _updateTime;

        /// <summary>
        /// 
        /// </summary>
        private DateTime? _pCDoubleImpactCheckDate;

        /// <summary>
        /// 
        /// </summary>
        private string _invoiceCusXOId;

        /// <summary>
        /// 
        /// </summary>
        private string _pronoteHeaderId;

        /// <summary>
        /// 
        /// </summary>
        private string _pCDoubleImpactCheckDesc;

        /// <summary>
        /// 
        /// </summary>
        private int? _pCDoubleImpactCheckType;

        /// <summary>
        /// 
        /// </summary>
        private string _spead;

        /// <summary>
        /// 
        /// </summary>
        private string _checkStandard;

        /// <summary>
        /// 
        /// </summary>
        private double? _invoiceXOQuantity;

        /// <summary>
        /// 
        /// </summary>
        private string _powerImpact;

        /// <summary>
        /// 检测数量
        /// </summary>
        private int? _pCDoubleImpactCheckCount;

        private string _ProductUnitId;

        private string _jiaReWenDu;

        private string _lengDongWenDu;

        private string _zhuiQiuKG;

        private string _printHeader;

        /// <summary>
        /// 员工
        /// </summary>
        private Employee _employee;
        /// <summary>
        /// 产品
        /// </summary>
        private Product _product;

        private int? _auditState;

        private string _auditEmpId;

        private Employee _auditEmp;

        private ProductUnit _ProductUnit;



        #endregion

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string PCDoubleImpactCheckID
        {
            get
            {
                return this._pCDoubleImpactCheckID;
            }
            set
            {
                this._pCDoubleImpactCheckID = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string EmployeeId
        {
            get
            {
                return this._employeeId;
            }
            set
            {
                this._employeeId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public DateTime? InsertTime
        {
            get
            {
                return this._insertTime;
            }
            set
            {
                this._insertTime = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public DateTime? UpdateTime
        {
            get
            {
                return this._updateTime;
            }
            set
            {
                this._updateTime = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public DateTime? PCDoubleImpactCheckDate
        {
            get
            {
                return this._pCDoubleImpactCheckDate;
            }
            set
            {
                this._pCDoubleImpactCheckDate = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string InvoiceCusXOId
        {
            get
            {
                return this._invoiceCusXOId;
            }
            set
            {
                this._invoiceCusXOId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string PronoteHeaderId
        {
            get
            {
                return this._pronoteHeaderId;
            }
            set
            {
                this._pronoteHeaderId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string PCDoubleImpactCheckDesc
        {
            get
            {
                return this._pCDoubleImpactCheckDesc;
            }
            set
            {
                this._pCDoubleImpactCheckDesc = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public int? PCDoubleImpactCheckType
        {
            get
            {
                return this._pCDoubleImpactCheckType;
            }
            set
            {
                this._pCDoubleImpactCheckType = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string Spead
        {
            get
            {
                return this._spead;
            }
            set
            {
                this._spead = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string CheckStandard
        {
            get
            {
                return this._checkStandard;
            }
            set
            {
                this._checkStandard = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public double? InvoiceXOQuantity
        {
            get
            {
                return this._invoiceXOQuantity;
            }
            set
            {
                this._invoiceXOQuantity = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string PowerImpact
        {
            get
            {
                return this._powerImpact;
            }
            set
            {
                this._powerImpact = value;
            }
        }

        /// <summary>
        /// 检测数量
        /// </summary>
        public int? PCDoubleImpactCheckCount
        {
            get
            {
                return this._pCDoubleImpactCheckCount;
            }
            set
            {
                this._pCDoubleImpactCheckCount = value;
            }
        }
        public int? AuditState
        {
            get
            {
                return this._auditState;
            }
            set
            {
                this._auditState = value;
            }
        }

        public virtual string AuditEmpId
        {
            get
            {
                return this._auditEmpId;

            }
            set
            {
                this._auditEmpId = value;
            }
        }

        public string ProductUnitId
        {
            get { return _ProductUnitId; }
            set { _ProductUnitId = value; }
        }

        public string JiaReWenDu
        {
            get { return _jiaReWenDu; }
            set { _jiaReWenDu = value; }
        }

        public string LengDongWenDu
        {
            get { return _lengDongWenDu; }
            set { _lengDongWenDu = value; }
        }


        public string ZhuiQiuKG
        {
            get { return _zhuiQiuKG; }
            set { _zhuiQiuKG = value; }
        }

        public string PrintHeader
        {
            get { return _printHeader; }
            set { _printHeader = value; }
        }


        public virtual Employee AuditEmp
        {
            get
            {
                return this._auditEmp;
            }
            set
            {
                this._auditEmp = value;
            }

        }

        /// <summary>
        /// 员工
        /// </summary>
        public virtual Employee Employee
        {
            get
            {
                return this._employee;
            }
            set
            {
                this._employee = value;
            }

        }
        /// <summary>
        /// 产品
        /// </summary>
        public virtual Product Product
        {
            get
            {
                return this._product;
            }
            set
            {
                this._product = value;
            }

        }

        public ProductUnit ProductUnit
        {
            get { return _ProductUnit; }
            set { _ProductUnit = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCDoubleImpactCheckID = "PCDoubleImpactCheckID";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProductId = "ProductId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_EmployeeId = "EmployeeId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_InsertTime = "InsertTime";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_UpdateTime = "UpdateTime";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCDoubleImpactCheckDate = "PCDoubleImpactCheckDate";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_InvoiceCusXOId = "InvoiceCusXOId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PronoteHeaderId = "PronoteHeaderId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCDoubleImpactCheckDesc = "PCDoubleImpactCheckDesc";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCDoubleImpactCheckType = "PCDoubleImpactCheckType";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_Spead = "Spead";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_CheckStandard = "CheckStandard";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_InvoiceXOQuantity = "InvoiceXOQuantity";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PowerImpact = "PowerImpact";

        /// <summary>
        /// 检测数量
        /// </summary>
        public readonly static string PRO_PCDoubleImpactCheckCount = "PCDoubleImpactCheckCount";

        public readonly static string PRO_AuditState = "AuditState";

        public readonly static string PRO_AuditEmpId = "AuditEmpId";

        public readonly static string PRO_ProductUnitId = "ProductUnitId";

        public readonly static string PRO_JiaReWenDu = "JiaReWenDu";

        public readonly static string PRO_LengDongWenDu = "LengDongWenDu";

        public readonly static string PRO_ZhuiQiuKG = "ZhuiQiuKG";

        public readonly static string PRO_PrintHeader = "PrintHeader";

        #endregion
    }
}
