//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProduceOtherExitDetail.autogenerated.cs
// author: mayanjun
// create date：2011-12-06 17:11:03
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class ProduceOtherExitDetail
	{
		#region Data

		/// <summary>
		/// 编号
		/// </summary>
		private string _produceOtherExitDetailId;
		
		/// <summary>
		/// 商品编号
		/// </summary>
		private string _productId;
		
		/// <summary>
		/// 位置编号
		/// </summary>
		private string _depotPositionId;
		
		/// <summary>
		/// 编号2
		/// </summary>
		private string _produceOtherExitMaterialId;
		
		/// <summary>
		/// 数量
		/// </summary>
		private double? _produceQuantity;
		
		/// <summary>
		/// 货品库存
		/// </summary>
		private double? _productStock;
		
		/// <summary>
		/// 使用总量
		/// </summary>
		private double? _produceAllUserQuantity;
		
		/// <summary>
		/// 计划单号
		/// </summary>
		private string _mPSheaderId;
		
		/// <summary>
		/// 标准使用数量
		/// </summary>
		private double? _criterionUserQuantity;
		
		/// <summary>
		/// 
		/// </summary>
		private string _invoiceXOId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _invoiceXODetailId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productUnit;
		
		/// <summary>
		/// 
		/// </summary>
		private string _primaryKeyId;
		
		/// <summary>
		/// 
		/// </summary>
		private double? _produceRepayQuantity;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _repayDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _description;
		
		/// <summary>
		/// 
		/// </summary>
		private string _produceOtherCompactMaterialId;

        /// <summary>
        /// 手册号
        /// </summary>
        private string _handbookId;

        /// <summary>
        /// 手册项号
        /// </summary>
        private string _handbookProductId;
		
		/// <summary>
		/// 库库货位
		/// </summary>
		private DepotPosition _depotPosition;
		/// <summary>
		/// 外包合同配料
		/// </summary>
		private ProduceOtherCompactMaterial _produceOtherCompactMaterial;
		/// <summary>
		/// 客户产品
		/// </summary>
		private CustomerProducts _primaryKey;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _product;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 编号
		/// </summary>
		public string ProduceOtherExitDetailId
		{
			get 
			{
				return this._produceOtherExitDetailId;
			}
			set 
			{
				this._produceOtherExitDetailId = value;
			}
		}

		/// <summary>
		/// 商品编号
		/// </summary>
		public string ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 位置编号
		/// </summary>
		public string DepotPositionId
		{
			get 
			{
				return this._depotPositionId;
			}
			set 
			{
				this._depotPositionId = value;
			}
		}

		/// <summary>
		/// 编号2
		/// </summary>
		public string ProduceOtherExitMaterialId
		{
			get 
			{
				return this._produceOtherExitMaterialId;
			}
			set 
			{
				this._produceOtherExitMaterialId = value;
			}
		}

		/// <summary>
		/// 数量
		/// </summary>
		public double? ProduceQuantity
		{
			get 
			{
				return this._produceQuantity;
			}
			set 
			{
				this._produceQuantity = value;
			}
		}

		/// <summary>
		/// 货品库存
		/// </summary>
		public double? ProductStock
		{
			get 
			{
				return this._productStock;
			}
			set 
			{
				this._productStock = value;
			}
		}

		/// <summary>
		/// 使用总量
		/// </summary>
		public double? ProduceAllUserQuantity
		{
			get 
			{
				return this._produceAllUserQuantity;
			}
			set 
			{
				this._produceAllUserQuantity = value;
			}
		}

		/// <summary>
		/// 计划单号
		/// </summary>
		public string MPSheaderId
		{
			get 
			{
				return this._mPSheaderId;
			}
			set 
			{
				this._mPSheaderId = value;
			}
		}

		/// <summary>
		/// 标准使用数量
		/// </summary>
		public double? CriterionUserQuantity
		{
			get 
			{
				return this._criterionUserQuantity;
			}
			set 
			{
				this._criterionUserQuantity = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string InvoiceXOId
		{
			get 
			{
				return this._invoiceXOId;
			}
			set 
			{
				this._invoiceXOId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string InvoiceXODetailId
		{
			get 
			{
				return this._invoiceXODetailId;
			}
			set 
			{
				this._invoiceXODetailId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductUnit
		{
			get 
			{
				return this._productUnit;
			}
			set 
			{
				this._productUnit = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PrimaryKeyId
		{
			get 
			{
				return this._primaryKeyId;
			}
			set 
			{
				this._primaryKeyId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public double? ProduceRepayQuantity
		{
			get 
			{
				return this._produceRepayQuantity;
			}
			set 
			{
				this._produceRepayQuantity = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? RepayDate
		{
			get 
			{
				return this._repayDate;
			}
			set 
			{
				this._repayDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Description
		{
			get 
			{
				return this._description;
			}
			set 
			{
				this._description = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProduceOtherCompactMaterialId
		{
			get 
			{
				return this._produceOtherCompactMaterialId;
			}
			set 
			{
				this._produceOtherCompactMaterialId = value;
			}
		}

        /// <summary>
        /// 手册号
        /// </summary>
        public string HandbookId
        {
            get { return _handbookId; }
            set { _handbookId = value; }
        }

        /// <summary>
        /// 手册项号
        /// </summary>
        public string HandbookProductId
        {
            get { return _handbookProductId; }
            set { _handbookProductId = value; }
        }
	
		/// <summary>
		/// 库库货位
		/// </summary>
		public virtual DepotPosition DepotPosition
		{
			get
			{
				return this._depotPosition;
			}
			set
			{
				this._depotPosition = value;
			}
			
		}
		/// <summary>
		/// 外包合同配料
		/// </summary>
		public virtual ProduceOtherCompactMaterial ProduceOtherCompactMaterial
		{
			get
			{
				return this._produceOtherCompactMaterial;
			}
			set
			{
				this._produceOtherCompactMaterial = value;
			}
			
		}
		/// <summary>
		/// 客户产品
		/// </summary>
		public virtual CustomerProducts PrimaryKey
		{
			get
			{
				return this._primaryKey;
			}
			set
			{
				this._primaryKey = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
			
		}
		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PRO_ProduceOtherExitDetailId = "ProduceOtherExitDetailId";
		
		/// <summary>
		/// 商品编号
		/// </summary>
		public readonly static string PRO_ProductId = "ProductId";
		
		/// <summary>
		/// 位置编号
		/// </summary>
		public readonly static string PRO_DepotPositionId = "DepotPositionId";
		
		/// <summary>
		/// 编号2
		/// </summary>
		public readonly static string PRO_ProduceOtherExitMaterialId = "ProduceOtherExitMaterialId";
		
		/// <summary>
		/// 数量
		/// </summary>
		public readonly static string PRO_ProduceQuantity = "ProduceQuantity";
		
		/// <summary>
		/// 货品库存
		/// </summary>
		public readonly static string PRO_ProductStock = "ProductStock";
		
		/// <summary>
		/// 使用总量
		/// </summary>
		public readonly static string PRO_ProduceAllUserQuantity = "ProduceAllUserQuantity";
		
		/// <summary>
		/// 计划单号
		/// </summary>
		public readonly static string PRO_MPSheaderId = "MPSheaderId";
		
		/// <summary>
		/// 标准使用数量
		/// </summary>
		public readonly static string PRO_CriterionUserQuantity = "CriterionUserQuantity";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceXOId = "InvoiceXOId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceXODetailId = "InvoiceXODetailId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductUnit = "ProductUnit";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PrimaryKeyId = "PrimaryKeyId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProduceRepayQuantity = "ProduceRepayQuantity";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RepayDate = "RepayDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Description = "Description";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProduceOtherCompactMaterialId = "ProduceOtherCompactMaterialId";

        public readonly static string PRO_HandbookId = "HandbookId";

        public readonly static string PRO_HandbookProductId = "HandbookProductId";


		#endregion
	}
}
