//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：Product.autogenerated.cs
// author: mayanjun
// create date：2012-02-16 15:44:22
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class Product
    {
        #region Data

        /// <summary>
        /// 产品编号
        /// </summary>
        private string _id;

        /// <summary>
        /// 商品编号
        /// </summary>
        private string _productId;

        /// <summary>
        /// 基础单位组
        /// </summary>
        private string _basedUnitGroupId;

        /// <summary>
        /// 主计量单位
        /// </summary>
        private string _mainUnitId;

        /// <summary>
        /// 采购单位
        /// </summary>
        private string _buyUnitId;

        /// <summary>
        /// 体积单位
        /// </summary>
        private string _volumeUnitId;

        /// <summary>
        /// 自定义抽检规则编号
        /// </summary>
        private string _customInspectionRuleId;

        /// <summary>
        /// 变更人
        /// </summary>
        private string _employeeChangeId;

        /// <summary>
        /// 替换件
        /// </summary>
        private string _insteadOfProductId;

        /// <summary>
        /// 建档人
        /// </summary>
        private string _employeeCreatorId;

        /// <summary>
        /// 生产单位
        /// </summary>
        private string _produceUnitId;

        /// <summary>
        /// 体积单位组
        /// </summary>
        private string _volumeUnitGroupId;

        /// <summary>
        /// 采购人员
        /// </summary>
        private string _buyEmployeeId;

        /// <summary>
        /// 重量单位组
        /// </summary>
        private string _weightUnitGroupId;

        /// <summary>
        /// 质检单位
        /// </summary>
        private string _qualityTestUnitId;

        /// <summary>
        /// 包装类型编号
        /// </summary>
        private string _packageTypeId;

        /// <summary>
        /// 销售单位
        /// </summary>
        private string _sellUnitId;

        /// <summary>
        /// 库存单位
        /// </summary>
        private string _depotUnitId;

        /// <summary>
        /// 重量单位
        /// </summary>
        private string _weightUnitId;

        /// <summary>
        /// 质检方案编号
        /// </summary>
        private string _qualityTestPlanId;

        /// <summary>
        /// 位置编号
        /// </summary>
        private string _depotPositionId;

        /// <summary>
        /// 库房编号
        /// </summary>
        private string _depotId;

        /// <summary>
        /// 供应商编号
        /// </summary>
        private string _supplierId;

        /// <summary>
        /// 商品种类编号
        /// </summary>
        private string _productCategoryId;

        /// <summary>
        /// 插入时间
        /// </summary>
        private DateTime? _insertTime;

        /// <summary>
        /// 修改时间
        /// </summary>
        private DateTime? _updateTime;

        /// <summary>
        /// 商品名称
        /// </summary>
        private string _productName;

        /// <summary>
        /// 商品条码
        /// </summary>
        private string _productBarCode;

        /// <summary>
        /// 规格型号
        /// </summary>
        private string _productSpecification;

        /// <summary>
        /// 商品说明
        /// </summary>
        private string _productDescription;

        /// <summary>
        /// 产地厂牌
        /// </summary>
        private string _productPlace;

        /// <summary>
        /// 商品批号
        /// </summary>
        private string _productBatch;

        /// <summary>
        /// 有效期至
        /// </summary>
        private DateTime? _productDeadDate;

        /// <summary>
        /// 最近进货日
        /// </summary>
        private DateTime? _productNearCGDate;

        /// <summary>
        /// 最近出货日
        /// </summary>
        private DateTime? _productNearXSDate;

        /// <summary>
        /// 生产国家
        /// </summary>
        private string _produceCounty;

        /// <summary>
        /// 計價方式
        /// </summary>
        private string _valuationWay;

        /// <summary>
        /// 计划售价
        /// </summary>
        private decimal? _planSellPrice;

        /// <summary>
        /// 参考成本
        /// </summary>
        private decimal? _referenceCost;

        /// <summary>
        /// 最低售价
        /// </summary>
        private decimal? _lowestSellPrice;

        /// <summary>
        /// 最高进价
        /// </summary>
        private decimal? _highestPurchasingPrice;

        /// <summary>
        /// 最新成本
        /// </summary>
        private decimal? _newestCost;

        /// <summary>
        /// 参考售价
        /// </summary>
        private decimal? _referenceSellPrice;

        /// <summary>
        /// 最高库存
        /// </summary>
        private double? _highestStock;

        /// <summary>
        /// 最低库存
        /// </summary>
        private double? _lowestStock;

        /// <summary>
        /// 安全库存
        /// </summary>
        private double? _safeStock;

        /// <summary>
        /// 合理损耗率
        /// </summary>
        private decimal? _damageRate;

        /// <summary>
        /// Abc分类
        /// </summary>
        private string _abcCategory;

        /// <summary>
        /// 盘点周期单位
        /// </summary>
        private double? _stockCheckTimeParts;

        /// <summary>
        /// 盘点周期
        /// </summary>
        private string _stockTakeCycle;

        /// <summary>
        /// 上次盘点时间
        /// </summary>
        private DateTime? _lastStockTakeTime;

        /// <summary>
        /// 每第
        /// </summary>
        private string _digital;

        /// <summary>
        /// 长度
        /// </summary>
        private double? _length;

        /// <summary>
        /// 宽度
        /// </summary>
        private double? _width;

        /// <summary>
        /// 高度
        /// </summary>
        private double? _height;

        /// <summary>
        /// 体积
        /// </summary>
        private double? _volume;

        /// <summary>
        /// 净重
        /// </summary>
        private double? _netWeight;

        /// <summary>
        /// 毛重
        /// </summary>
        private double? _grossWeight;

        /// <summary>
        /// 检验方式
        /// </summary>
        private string _checkCategory;

        /// <summary>
        /// 抽检规则
        /// </summary>
        private string _checkRule;

        /// <summary>
        /// 抽检率
        /// </summary>
        private double? _checkRate;

        /// <summary>
        /// 抽检量
        /// </summary>
        private double? _checkCount;

        /// <summary>
        /// 质量要求
        /// </summary>
        private string _qualityRequire;

        /// <summary>
        /// 所属权限组
        /// </summary>
        private string _powerGroup;

        /// <summary>
        /// 外购
        /// </summary>
        private bool? _outSourcing;

        /// <summary>
        /// 耗用
        /// </summary>
        private bool? _consume;

        /// <summary>
        /// 委外
        /// </summary>
        private bool? _trustOut;

        /// <summary>
        /// 自制
        /// </summary>
        private bool? _homeMade;

        /// <summary>
        /// 在制数量
        /// </summary>
        private double? _onMadingQuantity;

        /// <summary>
        /// 已分配量
        /// </summary>
        private double? _beenAssigned;

        /// <summary>
        /// 实际在库量
        /// </summary>
        private double? _stocksQuantity;

        /// <summary>
        /// 已定未入量
        /// </summary>
        private double? _orderOnWayQuantity;

        /// <summary>
        /// 借出未还入量
        /// </summary>
        private double? _lendQuantity;

        /// <summary>
        /// 借入未还出量
        /// </summary>
        private double? _borrowQuantity;

        /// <summary>
        /// 是否质检
        /// </summary>
        private bool? _isRequiredCheck;

        /// <summary>
        /// 是否周期检验
        /// </summary>
        private bool? _isRequiredCheckCycle;

        /// <summary>
        /// 周期检验周期
        /// </summary>
        private string _checkCycle;

        /// <summary>
        /// 
        /// </summary>
        private string _proceebeforeProductId;

        /// <summary>
        /// 
        /// </summary>
        private bool? _isProcee;

        /// <summary>
        /// 
        /// </summary>
        private bool? _isCustomerProduct;

        /// <summary>
        /// 
        /// </summary>
        private string _customerBeforeProductId;

        /// <summary>
        /// 
        /// </summary>
        private string _customerProductName;

        /// <summary>
        /// 
        /// </summary>
        private string _customerBeforeProductName;

        /// <summary>
        /// 
        /// </summary>
        private string _customerId;

        /// <summary>
        /// 
        /// </summary>
        private bool? _productBarCodeIsAuto;

        /// <summary>
        /// 
        /// </summary>
        private string _techonlogyHeaderid;

        /// <summary>
        /// 
        /// </summary>
        private string _proceduresId;

        /// <summary>
        /// 
        /// </summary>
        private double? _mpsStockQuantity;

        /// <summary>
        /// 
        /// </summary>
        private int? _inumber;

        /// <summary>
        /// 
        /// </summary>
        private double? _mRSStockQuantity;

        /// <summary>
        /// 
        /// </summary>
        private double? _produceMaterialDistributioned;

        /// <summary>
        /// 
        /// </summary>
        private double? _otherMaterialDistributioned;

        /// <summary>
        /// 
        /// </summary>
        private string _priceAndRange;

        /// <summary>
        /// 
        /// </summary>
        private int? _productType;

        /// <summary>
        /// 
        /// </summary>
        private string _xOPriceAndRange;

        /// <summary>
        /// 正麦
        /// </summary>
        private string _attrZhengMai;

        /// <summary>
        /// 侧麦
        /// </summary>
        private string _attrCeMai;

        /// <summary>
        /// 
        /// </summary>
        private int? _productState;

        /// <summary>
        /// 
        /// </summary>
        private string _productVersion;

        /// <summary>
        /// 原料净重
        /// </summary>
        private string _materialIds;

        /// <summary>
        /// 原料数量
        /// </summary>
        private string _materialNum;

        private string _productCategoryId2;

        private string _productCategoryId3;

        /// <summary>
        /// 客户
        /// </summary>
        private Customer _customer;
        /// <summary>
        /// 员工
        /// </summary>
        private Employee _employeeChange;
        /// <summary>
        /// 员工
        /// </summary>
        private Employee _employeeCreator;
        /// <summary>
        /// 自定义抽检规则
        /// </summary>
        private CustomInspectionRule _customInspectionRule;
        /// <summary>
        /// 库房
        /// </summary>
        private Depot _depot;
        /// <summary>
        /// 库库货位
        /// </summary>
        private DepotPosition _depotPosition;
        /// <summary>
        /// 员工
        /// </summary>
        private Employee _buyEmployee;
        /// <summary>
        /// 包装类型
        /// </summary>
        //   private PackageType _packageType;
        /// <summary>
        /// 产品类型
        /// </summary>
        private ProductCategory _productCategory;
        /// <summary>
        /// 单位
        /// </summary>
        private ProductUnit _buyUnit;
        /// <summary>
        /// 单位
        /// </summary>
        private ProductUnit _sellUnit;
        /// <summary>
        /// 单位
        /// </summary>
        private ProductUnit _depotUnit;
        /// <summary>
        /// 单位
        /// </summary>
        private ProductUnit _produceUnit;
        /// <summary>
        /// 单位
        /// </summary>
        private ProductUnit _mainUnit;
        /// <summary>
        /// 单位
        /// </summary>
        private ProductUnit _weightUnit;
        /// <summary>
        /// 单位
        /// </summary>
        private ProductUnit _volumeUnit;
        /// <summary>
        /// 单位
        /// </summary>
        private ProductUnit _qualityTestUnit;
        /// <summary>
        /// 质检方案
        /// </summary>
        private QualityTestPlan _qualityTestPlan;
        /// <summary>
        /// 供应商
        /// </summary>
        private Supplier _supplier;
        /// <summary>
        /// 单位组
        /// </summary>
        private UnitGroup _basedUnitGroup;
        /// <summary>
        /// 单位组
        /// </summary>
        private UnitGroup _volumeUnitGroup;
        /// <summary>
        /// 单位组
        /// </summary>
        private UnitGroup _weightUnitGroup;

        private ProductCategory _productCategory2;

        private ProductCategory _productCategory3;

        #endregion

        #region Properties

        /// <summary>
        /// 产品编号
        /// </summary>
        public string Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }

        /// <summary>
        /// 商品编号
        /// </summary>
        public string ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }

        /// <summary>
        /// 基础单位组
        /// </summary>
        public string BasedUnitGroupId
        {
            get
            {
                return this._basedUnitGroupId;
            }
            set
            {
                this._basedUnitGroupId = value;
            }
        }

        /// <summary>
        /// 主计量单位
        /// </summary>
        public string MainUnitId
        {
            get
            {
                return this._mainUnitId;
            }
            set
            {
                this._mainUnitId = value;
            }
        }

        /// <summary>
        /// 采购单位
        /// </summary>
        public string BuyUnitId
        {
            get
            {
                return this._buyUnitId;
            }
            set
            {
                this._buyUnitId = value;
            }
        }

        /// <summary>
        /// 体积单位
        /// </summary>
        public string VolumeUnitId
        {
            get
            {
                return this._volumeUnitId;
            }
            set
            {
                this._volumeUnitId = value;
            }
        }

        /// <summary>
        /// 自定义抽检规则编号
        /// </summary>
        public string CustomInspectionRuleId
        {
            get
            {
                return this._customInspectionRuleId;
            }
            set
            {
                this._customInspectionRuleId = value;
            }
        }

        /// <summary>
        /// 变更人
        /// </summary>
        public string EmployeeChangeId
        {
            get
            {
                return this._employeeChangeId;
            }
            set
            {
                this._employeeChangeId = value;
            }
        }

        /// <summary>
        /// 替换件
        /// </summary>
        public string InsteadOfProductId
        {
            get
            {
                return this._insteadOfProductId;
            }
            set
            {
                this._insteadOfProductId = value;
            }
        }

        /// <summary>
        /// 建档人
        /// </summary>
        public string EmployeeCreatorId
        {
            get
            {
                return this._employeeCreatorId;
            }
            set
            {
                this._employeeCreatorId = value;
            }
        }

        /// <summary>
        /// 生产单位
        /// </summary>
        public string ProduceUnitId
        {
            get
            {
                return this._produceUnitId;
            }
            set
            {
                this._produceUnitId = value;
            }
        }

        /// <summary>
        /// 体积单位组
        /// </summary>
        public string VolumeUnitGroupId
        {
            get
            {
                return this._volumeUnitGroupId;
            }
            set
            {
                this._volumeUnitGroupId = value;
            }
        }

        /// <summary>
        /// 采购人员
        /// </summary>
        public string BuyEmployeeId
        {
            get
            {
                return this._buyEmployeeId;
            }
            set
            {
                this._buyEmployeeId = value;
            }
        }

        /// <summary>
        /// 重量单位组
        /// </summary>
        public string WeightUnitGroupId
        {
            get
            {
                return this._weightUnitGroupId;
            }
            set
            {
                this._weightUnitGroupId = value;
            }
        }

        /// <summary>
        /// 质检单位
        /// </summary>
        public string QualityTestUnitId
        {
            get
            {
                return this._qualityTestUnitId;
            }
            set
            {
                this._qualityTestUnitId = value;
            }
        }

        /// <summary>
        /// 包装类型编号
        /// </summary>
        public string PackageTypeId
        {
            get
            {
                return this._packageTypeId;
            }
            set
            {
                this._packageTypeId = value;
            }
        }

        /// <summary>
        /// 销售单位
        /// </summary>
        public string SellUnitId
        {
            get
            {
                return this._sellUnitId;
            }
            set
            {
                this._sellUnitId = value;
            }
        }

        /// <summary>
        /// 库存单位
        /// </summary>
        public string DepotUnitId
        {
            get
            {
                return this._depotUnitId;
            }
            set
            {
                this._depotUnitId = value;
            }
        }

        /// <summary>
        /// 重量单位
        /// </summary>
        public string WeightUnitId
        {
            get
            {
                return this._weightUnitId;
            }
            set
            {
                this._weightUnitId = value;
            }
        }

        /// <summary>
        /// 质检方案编号
        /// </summary>
        public string QualityTestPlanId
        {
            get
            {
                return this._qualityTestPlanId;
            }
            set
            {
                this._qualityTestPlanId = value;
            }
        }

        /// <summary>
        /// 位置编号
        /// </summary>
        public string DepotPositionId
        {
            get
            {
                return this._depotPositionId;
            }
            set
            {
                this._depotPositionId = value;
            }
        }

        /// <summary>
        /// 库房编号
        /// </summary>
        public string DepotId
        {
            get
            {
                return this._depotId;
            }
            set
            {
                this._depotId = value;
            }
        }

        /// <summary>
        /// 供应商编号
        /// </summary>
        public string SupplierId
        {
            get
            {
                return this._supplierId;
            }
            set
            {
                this._supplierId = value;
            }
        }

        /// <summary>
        /// 商品种类编号
        /// </summary>
        public string ProductCategoryId
        {
            get
            {
                return this._productCategoryId;
            }
            set
            {
                this._productCategoryId = value;
            }
        }

        /// <summary>
        /// 插入时间
        /// </summary>
        public DateTime? InsertTime
        {
            get
            {
                return this._insertTime;
            }
            set
            {
                this._insertTime = value;
            }
        }

        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? UpdateTime
        {
            get
            {
                return this._updateTime;
            }
            set
            {
                this._updateTime = value;
            }
        }

        /// <summary>
        /// 商品名称
        /// </summary>
        public string ProductName
        {
            get
            {
                return this._productName;
            }
            set
            {
                this._productName = value;
            }
        }

        /// <summary>
        /// 商品条码
        /// </summary>
        public string ProductBarCode
        {
            get
            {
                return this._productBarCode;
            }
            set
            {
                this._productBarCode = value;
            }
        }

        /// <summary>
        /// 规格型号
        /// </summary>
        public string ProductSpecification
        {
            get
            {
                return this._productSpecification;
            }
            set
            {
                this._productSpecification = value;
            }
        }

        /// <summary>
        /// 商品说明
        /// </summary>
        public string ProductDescription
        {
            get
            {
                return this._productDescription;
            }
            set
            {
                this._productDescription = value;
            }
        }

        /// <summary>
        /// 产地厂牌
        /// </summary>
        public string ProductPlace
        {
            get
            {
                return this._productPlace;
            }
            set
            {
                this._productPlace = value;
            }
        }

        /// <summary>
        /// 商品批号
        /// </summary>
        public string ProductBatch
        {
            get
            {
                return this._productBatch;
            }
            set
            {
                this._productBatch = value;
            }
        }

        /// <summary>
        /// 有效期至
        /// </summary>
        public DateTime? ProductDeadDate
        {
            get
            {
                return this._productDeadDate;
            }
            set
            {
                this._productDeadDate = value;
            }
        }

        /// <summary>
        /// 最近进货日
        /// </summary>
        public DateTime? ProductNearCGDate
        {
            get
            {
                return this._productNearCGDate;
            }
            set
            {
                this._productNearCGDate = value;
            }
        }

        /// <summary>
        /// 最近出货日
        /// </summary>
        public DateTime? ProductNearXSDate
        {
            get
            {
                return this._productNearXSDate;
            }
            set
            {
                this._productNearXSDate = value;
            }
        }

        /// <summary>
        /// 生产国家
        /// </summary>
        public string ProduceCounty
        {
            get
            {
                return this._produceCounty;
            }
            set
            {
                this._produceCounty = value;
            }
        }

        /// <summary>
        /// 計價方式
        /// </summary>
        public string ValuationWay
        {
            get
            {
                return this._valuationWay;
            }
            set
            {
                this._valuationWay = value;
            }
        }

        /// <summary>
        /// 计划售价
        /// </summary>
        public decimal? PlanSellPrice
        {
            get
            {
                return this._planSellPrice;
            }
            set
            {
                this._planSellPrice = value;
            }
        }

        /// <summary>
        /// 参考成本
        /// </summary>
        public decimal? ReferenceCost
        {
            get
            {
                return this._referenceCost;
            }
            set
            {
                this._referenceCost = value;
            }
        }

        /// <summary>
        /// 最低售价
        /// </summary>
        public decimal? LowestSellPrice
        {
            get
            {
                return this._lowestSellPrice;
            }
            set
            {
                this._lowestSellPrice = value;
            }
        }

        /// <summary>
        /// 最高进价
        /// </summary>
        public decimal? HighestPurchasingPrice
        {
            get
            {
                return this._highestPurchasingPrice;
            }
            set
            {
                this._highestPurchasingPrice = value;
            }
        }

        /// <summary>
        /// 最新成本
        /// </summary>
        public decimal? NewestCost
        {
            get
            {
                return this._newestCost;
            }
            set
            {
                this._newestCost = value;
            }
        }

        /// <summary>
        /// 参考售价
        /// </summary>
        public decimal? ReferenceSellPrice
        {
            get
            {
                return this._referenceSellPrice;
            }
            set
            {
                this._referenceSellPrice = value;
            }
        }

        /// <summary>
        /// 最高库存
        /// </summary>
        public double? HighestStock
        {
            get
            {
                return this._highestStock;
            }
            set
            {
                this._highestStock = value;
            }
        }

        /// <summary>
        /// 最低库存
        /// </summary>
        public double? LowestStock
        {
            get
            {
                return this._lowestStock;
            }
            set
            {
                this._lowestStock = value;
            }
        }

        /// <summary>
        /// 安全库存
        /// </summary>
        public double? SafeStock
        {
            get
            {
                return this._safeStock;
            }
            set
            {
                this._safeStock = value;
            }
        }

        /// <summary>
        /// 合理损耗率
        /// </summary>
        public decimal? DamageRate
        {
            get
            {
                return this._damageRate;
            }
            set
            {
                this._damageRate = value;
            }
        }

        /// <summary>
        /// Abc分类
        /// </summary>
        public string AbcCategory
        {
            get
            {
                return this._abcCategory;
            }
            set
            {
                this._abcCategory = value;
            }
        }

        /// <summary>
        /// 盘点周期单位
        /// </summary>
        public double? StockCheckTimeParts
        {
            get
            {
                return this._stockCheckTimeParts;
            }
            set
            {
                this._stockCheckTimeParts = value;
            }
        }

        /// <summary>
        /// 盘点周期
        /// </summary>
        public string StockTakeCycle
        {
            get
            {
                return this._stockTakeCycle;
            }
            set
            {
                this._stockTakeCycle = value;
            }
        }

        /// <summary>
        /// 上次盘点时间
        /// </summary>
        public DateTime? LastStockTakeTime
        {
            get
            {
                return this._lastStockTakeTime;
            }
            set
            {
                this._lastStockTakeTime = value;
            }
        }

        /// <summary>
        /// 每第
        /// </summary>
        public string Digital
        {
            get
            {
                return this._digital;
            }
            set
            {
                this._digital = value;
            }
        }

        /// <summary>
        /// 长度
        /// </summary>
        public double? Length
        {
            get
            {
                return this._length;
            }
            set
            {
                this._length = value;
            }
        }

        /// <summary>
        /// 宽度
        /// </summary>
        public double? Width
        {
            get
            {
                return this._width;
            }
            set
            {
                this._width = value;
            }
        }

        /// <summary>
        /// 高度
        /// </summary>
        public double? Height
        {
            get
            {
                return this._height;
            }
            set
            {
                this._height = value;
            }
        }

        /// <summary>
        /// 体积
        /// </summary>
        public double? Volume
        {
            get
            {
                return this._volume;
            }
            set
            {
                this._volume = value;
            }
        }

        /// <summary>
        /// 净重
        /// </summary>
        public double? NetWeight
        {
            get
            {
                return this._netWeight;
            }
            set
            {
                this._netWeight = value;
            }
        }

        /// <summary>
        /// 毛重
        /// </summary>
        public double? GrossWeight
        {
            get
            {
                return this._grossWeight;
            }
            set
            {
                this._grossWeight = value;
            }
        }

        /// <summary>
        /// 检验方式
        /// </summary>
        public string CheckCategory
        {
            get
            {
                return this._checkCategory;
            }
            set
            {
                this._checkCategory = value;
            }
        }

        /// <summary>
        /// 抽检规则
        /// </summary>
        public string CheckRule
        {
            get
            {
                return this._checkRule;
            }
            set
            {
                this._checkRule = value;
            }
        }

        /// <summary>
        /// 抽检率
        /// </summary>
        public double? CheckRate
        {
            get
            {
                return this._checkRate;
            }
            set
            {
                this._checkRate = value;
            }
        }

        /// <summary>
        /// 抽检量
        /// </summary>
        public double? CheckCount
        {
            get
            {
                return this._checkCount;
            }
            set
            {
                this._checkCount = value;
            }
        }

        /// <summary>
        /// 质量要求
        /// </summary>
        public string QualityRequire
        {
            get
            {
                return this._qualityRequire;
            }
            set
            {
                this._qualityRequire = value;
            }
        }

        /// <summary>
        /// 所属权限组
        /// </summary>
        public string PowerGroup
        {
            get
            {
                return this._powerGroup;
            }
            set
            {
                this._powerGroup = value;
            }
        }

        /// <summary>
        /// 外购
        /// </summary>
        public bool? OutSourcing
        {
            get
            {
                return this._outSourcing;
            }
            set
            {
                this._outSourcing = value;
            }
        }

        /// <summary>
        /// 耗用
        /// </summary>
        public bool? Consume
        {
            get
            {
                return this._consume;
            }
            set
            {
                this._consume = value;
            }
        }

        /// <summary>
        /// 委外
        /// </summary>
        public bool? TrustOut
        {
            get
            {
                return this._trustOut;
            }
            set
            {
                this._trustOut = value;
            }
        }

        /// <summary>
        /// 自制
        /// </summary>
        public bool? HomeMade
        {
            get
            {
                return this._homeMade;
            }
            set
            {
                this._homeMade = value;
            }
        }

        /// <summary>
        /// 在制数量
        /// </summary>
        public double? OnMadingQuantity
        {
            get
            {
                return this._onMadingQuantity;
            }
            set
            {
                this._onMadingQuantity = value;
            }
        }

        /// <summary>
        /// 已分配量
        /// </summary>
        public double? BeenAssigned
        {
            get
            {
                return this._beenAssigned;
            }
            set
            {
                this._beenAssigned = value;
            }
        }

        /// <summary>
        /// 实际在库量
        /// </summary>
        public double? StocksQuantity
        {
            get
            {
                return this._stocksQuantity;
            }
            set
            {
                this._stocksQuantity = value;
            }
        }

        /// <summary>
        /// 已定未入量
        /// </summary>
        public double? OrderOnWayQuantity
        {
            get
            {
                return this._orderOnWayQuantity;
            }
            set
            {
                this._orderOnWayQuantity = value;
            }
        }

        /// <summary>
        /// 借出未还入量
        /// </summary>
        public double? LendQuantity
        {
            get
            {
                return this._lendQuantity;
            }
            set
            {
                this._lendQuantity = value;
            }
        }

        /// <summary>
        /// 借入未还出量
        /// </summary>
        public double? BorrowQuantity
        {
            get
            {
                return this._borrowQuantity;
            }
            set
            {
                this._borrowQuantity = value;
            }
        }

        /// <summary>
        /// 是否质检
        /// </summary>
        public bool? IsRequiredCheck
        {
            get
            {
                return this._isRequiredCheck;
            }
            set
            {
                this._isRequiredCheck = value;
            }
        }

        /// <summary>
        /// 是否周期检验
        /// </summary>
        public bool? IsRequiredCheckCycle
        {
            get
            {
                return this._isRequiredCheckCycle;
            }
            set
            {
                this._isRequiredCheckCycle = value;
            }
        }

        /// <summary>
        /// 周期检验周期
        /// </summary>
        public string CheckCycle
        {
            get
            {
                return this._checkCycle;
            }
            set
            {
                this._checkCycle = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string ProceebeforeProductId
        {
            get
            {
                return this._proceebeforeProductId;
            }
            set
            {
                this._proceebeforeProductId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public bool? IsProcee
        {
            get
            {
                return this._isProcee;
            }
            set
            {
                this._isProcee = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public bool? IsCustomerProduct
        {
            get
            {
                return this._isCustomerProduct;
            }
            set
            {
                this._isCustomerProduct = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string CustomerBeforeProductId
        {
            get
            {
                return this._customerBeforeProductId;
            }
            set
            {
                this._customerBeforeProductId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string CustomerProductName
        {
            get
            {
                return this._customerProductName;
            }
            set
            {
                this._customerProductName = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string CustomerBeforeProductName
        {
            get
            {
                return this._customerBeforeProductName;
            }
            set
            {
                this._customerBeforeProductName = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string CustomerId
        {
            get
            {
                return this._customerId;
            }
            set
            {
                this._customerId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public bool? ProductBarCodeIsAuto
        {
            get
            {
                return this._productBarCodeIsAuto;
            }
            set
            {
                this._productBarCodeIsAuto = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string TechonlogyHeaderid
        {
            get
            {
                return this._techonlogyHeaderid;
            }
            set
            {
                this._techonlogyHeaderid = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string ProceduresId
        {
            get
            {
                return this._proceduresId;
            }
            set
            {
                this._proceduresId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public double? MpsStockQuantity
        {
            get
            {
                return this._mpsStockQuantity;
            }
            set
            {
                this._mpsStockQuantity = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public int? Inumber
        {
            get
            {
                return this._inumber;
            }
            set
            {
                this._inumber = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public double? MRSStockQuantity
        {
            get
            {
                return this._mRSStockQuantity;
            }
            set
            {
                this._mRSStockQuantity = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public double? ProduceMaterialDistributioned
        {
            get
            {
                return this._produceMaterialDistributioned;
            }
            set
            {
                this._produceMaterialDistributioned = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public double? OtherMaterialDistributioned
        {
            get
            {
                return this._otherMaterialDistributioned;
            }
            set
            {
                this._otherMaterialDistributioned = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string PriceAndRange
        {
            get
            {
                return this._priceAndRange;
            }
            set
            {
                this._priceAndRange = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public int? ProductType
        {
            get
            {
                return this._productType;
            }
            set
            {
                this._productType = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string XOPriceAndRange
        {
            get
            {
                return this._xOPriceAndRange;
            }
            set
            {
                this._xOPriceAndRange = value;
            }
        }

        /// <summary>
        /// 正麦
        /// </summary>
        public string AttrZhengMai
        {
            get
            {
                return this._attrZhengMai;
            }
            set
            {
                this._attrZhengMai = value;
            }
        }

        /// <summary>
        /// 侧麦
        /// </summary>
        public string AttrCeMai
        {
            get
            {
                return this._attrCeMai;
            }
            set
            {
                this._attrCeMai = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public int? ProductState
        {
            get
            {
                return this._productState;
            }
            set
            {
                this._productState = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string ProductVersion
        {
            get
            {
                return this._productVersion;
            }
            set
            {
                this._productVersion = value;
            }
        }

        /// <summary>
        /// 原料净重
        /// </summary>
        public string MaterialIds
        {
            get { return _materialIds; }
            set { _materialIds = value; }
        }

        /// <summary>
        /// 原料数量
        /// </summary>
        public string MaterialNum
        {
            get { return _materialNum; }
            set { _materialNum = value; }
        }

        public string ProductCategoryId2
        {
            get { return _productCategoryId2; }
            set { _productCategoryId2 = value; }
        }

        public string ProductCategoryId3
        {
            get { return _productCategoryId3; }
            set { _productCategoryId3 = value; }
        }

        /// <summary>
        /// 客户
        /// </summary>
        public virtual Customer Customer
        {
            get
            {
                return this._customer;
            }
            set
            {
                this._customer = value;
            }

        }
        /// <summary>
        /// 员工
        /// </summary>
        public virtual Employee EmployeeChange
        {
            get
            {
                return this._employeeChange;
            }
            set
            {
                this._employeeChange = value;
            }

        }
        /// <summary>
        /// 员工
        /// </summary>
        public virtual Employee EmployeeCreator
        {
            get
            {
                return this._employeeCreator;
            }
            set
            {
                this._employeeCreator = value;
            }

        }
        /// <summary>
        /// 自定义抽检规则
        /// </summary>
        public virtual CustomInspectionRule CustomInspectionRule
        {
            get
            {
                return this._customInspectionRule;
            }
            set
            {
                this._customInspectionRule = value;
            }

        }
        /// <summary>
        /// 库房
        /// </summary>
        public virtual Depot Depot
        {
            get
            {
                return this._depot;
            }
            set
            {
                this._depot = value;
            }

        }
        /// <summary>
        /// 库库货位
        /// </summary>
        public virtual DepotPosition DepotPosition
        {
            get
            {
                return this._depotPosition;
            }
            set
            {
                this._depotPosition = value;
            }

        }
        /// <summary>
        /// 员工
        /// </summary>
        public virtual Employee BuyEmployee
        {
            get
            {
                return this._buyEmployee;
            }
            set
            {
                this._buyEmployee = value;
            }

        }

        /// <summary>
        /// 产品类型
        /// </summary>
        public virtual ProductCategory ProductCategory
        {
            get
            {
                return this._productCategory;
            }
            set
            {
                this._productCategory = value;
            }

        }
        /// <summary>
        /// 单位
        /// </summary>
        public virtual ProductUnit BuyUnit
        {
            get
            {
                return this._buyUnit;
            }
            set
            {
                this._buyUnit = value;
            }

        }
        /// <summary>
        /// 单位
        /// </summary>
        public virtual ProductUnit SellUnit
        {
            get
            {
                return this._sellUnit;
            }
            set
            {
                this._sellUnit = value;
            }

        }
        /// <summary>
        /// 单位
        /// </summary>
        public virtual ProductUnit DepotUnit
        {
            get
            {
                return this._depotUnit;
            }
            set
            {
                this._depotUnit = value;
            }

        }
        /// <summary>
        /// 单位
        /// </summary>
        public virtual ProductUnit ProduceUnit
        {
            get
            {
                return this._produceUnit;
            }
            set
            {
                this._produceUnit = value;
            }

        }
        /// <summary>
        /// 单位
        /// </summary>
        public virtual ProductUnit MainUnit
        {
            get
            {
                return this._mainUnit;
            }
            set
            {
                this._mainUnit = value;
            }

        }
        /// <summary>
        /// 单位
        /// </summary>
        public virtual ProductUnit WeightUnit
        {
            get
            {
                return this._weightUnit;
            }
            set
            {
                this._weightUnit = value;
            }

        }
        /// <summary>
        /// 单位
        /// </summary>
        public virtual ProductUnit VolumeUnit
        {
            get
            {
                return this._volumeUnit;
            }
            set
            {
                this._volumeUnit = value;
            }

        }
        /// <summary>
        /// 单位
        /// </summary>
        public virtual ProductUnit QualityTestUnit
        {
            get
            {
                return this._qualityTestUnit;
            }
            set
            {
                this._qualityTestUnit = value;
            }

        }
        /// <summary>
        /// 质检方案
        /// </summary>
        public virtual QualityTestPlan QualityTestPlan
        {
            get
            {
                return this._qualityTestPlan;
            }
            set
            {
                this._qualityTestPlan = value;
            }

        }
        /// <summary>
        /// 供应商
        /// </summary>
        public virtual Supplier Supplier
        {
            get
            {
                return this._supplier;
            }
            set
            {
                this._supplier = value;
            }

        }
        /// <summary>
        /// 单位组
        /// </summary>
        public virtual UnitGroup BasedUnitGroup
        {
            get
            {
                return this._basedUnitGroup;
            }
            set
            {
                this._basedUnitGroup = value;
            }

        }
        /// <summary>
        /// 单位组
        /// </summary>
        public virtual UnitGroup VolumeUnitGroup
        {
            get
            {
                return this._volumeUnitGroup;
            }
            set
            {
                this._volumeUnitGroup = value;
            }

        }
        /// <summary>
        /// 单位组
        /// </summary>
        public virtual UnitGroup WeightUnitGroup
        {
            get
            {
                return this._weightUnitGroup;
            }
            set
            {
                this._weightUnitGroup = value;
            }

        }

        public ProductCategory ProductCategory2
        {
            get { return _productCategory2; }
            set { _productCategory2 = value; }
        }

        public ProductCategory ProductCategory3
        {
            get { return _productCategory3; }
            set { _productCategory3 = value; }
        }

        private bool? _isQiangHua;
        public bool? IsQiangHua
        {
            get
            { return this._isQiangHua; }
            set { this._isQiangHua = value; }
        }
        private bool? _isFangWu;
        public bool? IsFangWu
        {
            get
            { return this._isFangWu; }
            set { this._isFangWu = value; }
        }
        private bool? _isNoQiangFang;
        public bool? IsNoQiangFang
        {
            get
            { return this._isNoQiangFang; }
            set { this._isNoQiangFang = value; }
        }
        /// <summary>
        /// 强化
        /// </summary>
        public readonly static string PRO_IsQiangHua = "IsQiangHua";
        /// <summary>
        /// 防雾
        /// </summary>
        public readonly static string PRO_IsFangWu = "IsFangWu";
        /// <summary>
        /// 非强化防雾
        /// </summary>
        public readonly static string PRO_IsNoQiangFang = "IsNoQiangFang";

        /// <summary>
        /// 产品编号
        /// </summary>
        public readonly static string PRO_Id = "Id";

        /// <summary>
        /// 商品编号
        /// </summary>
        public readonly static string PRO_ProductId = "ProductId";

        /// <summary>
        /// 基础单位组
        /// </summary>
        public readonly static string PRO_BasedUnitGroupId = "BasedUnitGroupId";

        /// <summary>
        /// 主计量单位
        /// </summary>
        public readonly static string PRO_MainUnitId = "MainUnitId";

        /// <summary>
        /// 采购单位
        /// </summary>
        public readonly static string PRO_BuyUnitId = "BuyUnitId";

        /// <summary>
        /// 体积单位
        /// </summary>
        public readonly static string PRO_VolumeUnitId = "VolumeUnitId";

        /// <summary>
        /// 自定义抽检规则编号
        /// </summary>
        public readonly static string PRO_CustomInspectionRuleId = "CustomInspectionRuleId";

        /// <summary>
        /// 变更人
        /// </summary>
        public readonly static string PRO_EmployeeChangeId = "EmployeeChangeId";

        /// <summary>
        /// 替换件
        /// </summary>
        public readonly static string PRO_InsteadOfProductId = "InsteadOfProductId";

        /// <summary>
        /// 建档人
        /// </summary>
        public readonly static string PRO_EmployeeCreatorId = "EmployeeCreatorId";

        /// <summary>
        /// 生产单位
        /// </summary>
        public readonly static string PRO_ProduceUnitId = "ProduceUnitId";

        /// <summary>
        /// 体积单位组
        /// </summary>
        public readonly static string PRO_VolumeUnitGroupId = "VolumeUnitGroupId";

        /// <summary>
        /// 采购人员
        /// </summary>
        public readonly static string PRO_BuyEmployeeId = "BuyEmployeeId";

        /// <summary>
        /// 重量单位组
        /// </summary>
        public readonly static string PRO_WeightUnitGroupId = "WeightUnitGroupId";

        /// <summary>
        /// 质检单位
        /// </summary>
        public readonly static string PRO_QualityTestUnitId = "QualityTestUnitId";

        /// <summary>
        /// 包装类型编号
        /// </summary>
        public readonly static string PRO_PackageTypeId = "PackageTypeId";

        /// <summary>
        /// 销售单位
        /// </summary>
        public readonly static string PRO_SellUnitId = "SellUnitId";

        /// <summary>
        /// 库存单位
        /// </summary>
        public readonly static string PRO_DepotUnitId = "DepotUnitId";

        /// <summary>
        /// 重量单位
        /// </summary>
        public readonly static string PRO_WeightUnitId = "WeightUnitId";

        /// <summary>
        /// 质检方案编号
        /// </summary>
        public readonly static string PRO_QualityTestPlanId = "QualityTestPlanId";

        /// <summary>
        /// 位置编号
        /// </summary>
        public readonly static string PRO_DepotPositionId = "DepotPositionId";

        /// <summary>
        /// 库房编号
        /// </summary>
        public readonly static string PRO_DepotId = "DepotId";

        /// <summary>
        /// 供应商编号
        /// </summary>
        public readonly static string PRO_SupplierId = "SupplierId";

        /// <summary>
        /// 商品种类编号
        /// </summary>
        public readonly static string PRO_ProductCategoryId = "ProductCategoryId";

        /// <summary>
        /// 插入时间
        /// </summary>
        public readonly static string PRO_InsertTime = "InsertTime";

        /// <summary>
        /// 修改时间
        /// </summary>
        public readonly static string PRO_UpdateTime = "UpdateTime";

        /// <summary>
        /// 商品名称
        /// </summary>
        public readonly static string PRO_ProductName = "ProductName";

        /// <summary>
        /// 商品条码
        /// </summary>
        public readonly static string PRO_ProductBarCode = "ProductBarCode";

        /// <summary>
        /// 规格型号
        /// </summary>
        public readonly static string PRO_ProductSpecification = "ProductSpecification";

        /// <summary>
        /// 商品说明
        /// </summary>
        public readonly static string PRO_ProductDescription = "ProductDescription";

        /// <summary>
        /// 产地厂牌
        /// </summary>
        public readonly static string PRO_ProductPlace = "ProductPlace";

        /// <summary>
        /// 商品批号
        /// </summary>
        public readonly static string PRO_ProductBatch = "ProductBatch";

        /// <summary>
        /// 有效期至
        /// </summary>
        public readonly static string PRO_ProductDeadDate = "ProductDeadDate";

        /// <summary>
        /// 最近进货日
        /// </summary>
        public readonly static string PRO_ProductNearCGDate = "ProductNearCGDate";

        /// <summary>
        /// 最近出货日
        /// </summary>
        public readonly static string PRO_ProductNearXSDate = "ProductNearXSDate";

        /// <summary>
        /// 生产国家
        /// </summary>
        public readonly static string PRO_ProduceCounty = "ProduceCounty";

        /// <summary>
        /// 計價方式
        /// </summary>
        public readonly static string PRO_ValuationWay = "ValuationWay";

        /// <summary>
        /// 计划售价
        /// </summary>
        public readonly static string PRO_PlanSellPrice = "PlanSellPrice";

        /// <summary>
        /// 参考成本
        /// </summary>
        public readonly static string PRO_ReferenceCost = "ReferenceCost";

        /// <summary>
        /// 最低售价
        /// </summary>
        public readonly static string PRO_LowestSellPrice = "LowestSellPrice";

        /// <summary>
        /// 最高进价
        /// </summary>
        public readonly static string PRO_HighestPurchasingPrice = "HighestPurchasingPrice";

        /// <summary>
        /// 最新成本
        /// </summary>
        public readonly static string PRO_NewestCost = "NewestCost";

        /// <summary>
        /// 参考售价
        /// </summary>
        public readonly static string PRO_ReferenceSellPrice = "ReferenceSellPrice";

        /// <summary>
        /// 最高库存
        /// </summary>
        public readonly static string PRO_HighestStock = "HighestStock";

        /// <summary>
        /// 最低库存
        /// </summary>
        public readonly static string PRO_LowestStock = "LowestStock";

        /// <summary>
        /// 安全库存
        /// </summary>
        public readonly static string PRO_SafeStock = "SafeStock";

        /// <summary>
        /// 合理损耗率
        /// </summary>
        public readonly static string PRO_DamageRate = "DamageRate";

        /// <summary>
        /// Abc分类
        /// </summary>
        public readonly static string PRO_AbcCategory = "AbcCategory";

        /// <summary>
        /// 盘点周期单位
        /// </summary>
        public readonly static string PRO_StockCheckTimeParts = "StockCheckTimeParts";

        /// <summary>
        /// 盘点周期
        /// </summary>
        public readonly static string PRO_StockTakeCycle = "StockTakeCycle";

        /// <summary>
        /// 上次盘点时间
        /// </summary>
        public readonly static string PRO_LastStockTakeTime = "LastStockTakeTime";

        /// <summary>
        /// 每第
        /// </summary>
        public readonly static string PRO_Digital = "Digital";

        /// <summary>
        /// 长度
        /// </summary>
        public readonly static string PRO_Length = "Length";

        /// <summary>
        /// 宽度
        /// </summary>
        public readonly static string PRO_Width = "Width";

        /// <summary>
        /// 高度
        /// </summary>
        public readonly static string PRO_Height = "Height";

        /// <summary>
        /// 体积
        /// </summary>
        public readonly static string PRO_Volume = "Volume";

        /// <summary>
        /// 净重
        /// </summary>
        public readonly static string PRO_NetWeight = "NetWeight";

        /// <summary>
        /// 毛重
        /// </summary>
        public readonly static string PRO_GrossWeight = "GrossWeight";

        /// <summary>
        /// 检验方式
        /// </summary>
        public readonly static string PRO_CheckCategory = "CheckCategory";

        /// <summary>
        /// 抽检规则
        /// </summary>
        public readonly static string PRO_CheckRule = "CheckRule";

        /// <summary>
        /// 抽检率
        /// </summary>
        public readonly static string PRO_CheckRate = "CheckRate";

        /// <summary>
        /// 抽检量
        /// </summary>
        public readonly static string PRO_CheckCount = "CheckCount";

        /// <summary>
        /// 质量要求
        /// </summary>
        public readonly static string PRO_QualityRequire = "QualityRequire";

        /// <summary>
        /// 所属权限组
        /// </summary>
        public readonly static string PRO_PowerGroup = "PowerGroup";

        /// <summary>
        /// 外购
        /// </summary>
        public readonly static string PRO_OutSourcing = "OutSourcing";

        /// <summary>
        /// 耗用
        /// </summary>
        public readonly static string PRO_Consume = "Consume";

        /// <summary>
        /// 委外
        /// </summary>
        public readonly static string PRO_TrustOut = "TrustOut";

        /// <summary>
        /// 自制
        /// </summary>
        public readonly static string PRO_HomeMade = "HomeMade";

        /// <summary>
        /// 在制数量
        /// </summary>
        public readonly static string PRO_OnMadingQuantity = "OnMadingQuantity";

        /// <summary>
        /// 已分配量
        /// </summary>
        public readonly static string PRO_BeenAssigned = "BeenAssigned";

        /// <summary>
        /// 实际在库量
        /// </summary>
        public readonly static string PRO_StocksQuantity = "StocksQuantity";

        /// <summary>
        /// 已定未入量
        /// </summary>
        public readonly static string PRO_OrderOnWayQuantity = "OrderOnWayQuantity";

        /// <summary>
        /// 借出未还入量
        /// </summary>
        public readonly static string PRO_LendQuantity = "LendQuantity";

        /// <summary>
        /// 借入未还出量
        /// </summary>
        public readonly static string PRO_BorrowQuantity = "BorrowQuantity";

        /// <summary>
        /// 是否质检
        /// </summary>
        public readonly static string PRO_IsRequiredCheck = "IsRequiredCheck";

        /// <summary>
        /// 是否周期检验
        /// </summary>
        public readonly static string PRO_IsRequiredCheckCycle = "IsRequiredCheckCycle";

        /// <summary>
        /// 周期检验周期
        /// </summary>
        public readonly static string PRO_CheckCycle = "CheckCycle";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProceebeforeProductId = "ProceebeforeProductId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_IsProcee = "IsProcee";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_IsCustomerProduct = "IsCustomerProduct";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_CustomerBeforeProductId = "CustomerBeforeProductId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_CustomerProductName = "CustomerProductName";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_CustomerBeforeProductName = "CustomerBeforeProductName";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_CustomerId = "CustomerId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProductBarCodeIsAuto = "ProductBarCodeIsAuto";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_TechonlogyHeaderid = "TechonlogyHeaderid";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProceduresId = "ProceduresId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_MpsStockQuantity = "MpsStockQuantity";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_Inumber = "Inumber";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_MRSStockQuantity = "MRSStockQuantity";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProduceMaterialDistributioned = "ProduceMaterialDistributioned";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_OtherMaterialDistributioned = "OtherMaterialDistributioned";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PriceAndRange = "PriceAndRange";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProductType = "ProductType";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_XOPriceAndRange = "XOPriceAndRange";

        /// <summary>
        /// 正麦
        /// </summary>
        public readonly static string PRO_AttrZhengMai = "AttrZhengMai";

        /// <summary>
        /// 侧麦
        /// </summary>
        public readonly static string PRO_AttrCeMai = "AttrCeMai";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProductState = "ProductState";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProductVersion = "ProductVersion";

        /// <summary>
        /// 原料净重
        /// </summary>
        public readonly static string PRO_MaterialIds = "MaterialIds";

        /// <summary>
        /// 原料数量
        /// </summary>
        public readonly static string PRO_MaterialNum = "MaterialNum";

        public readonly static string PRO_ProductCategoryId2 = "ProductCategoryId2";

        public readonly static string PRO_ProductCategoryId3 = "ProductCategoryId3";
        #endregion
    }
}
