//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：AtProperty.autogenerated.cs
// author: mayanjun
// create date：2011-3-3 14:30:28
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class AtProperty
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _propertyId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _propertyName;
		
		/// <summary>
		/// 
		/// </summary>
		private string _specifications;
		
		/// <summary>
		/// 
		/// </summary>
		private string _position;
		
		/// <summary>
		/// 
		/// </summary>
		private double? _quantity;
		
		/// <summary>
		/// 
		/// </summary>
		private string _unit;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _toDate;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _obtainRegular;
		
		/// <summary>
		/// 
		/// </summary>
		private string _often;
		
		/// <summary>
		/// 
		/// </summary>
		private int? _durableMonths;
		
		/// <summary>
		/// 
		/// </summary>
		private double? _reserveValue;
		
		/// <summary>
		/// 
		/// </summary>
		private string _depreciation;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _depreciationDate;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _depreciationMoney;
		
		/// <summary>
		/// 
		/// </summary>
		private string _depreciationSubject;
		
		/// <summary>
		/// 
		/// </summary>
		private string _respectiveSubject;
		
		/// <summary>
		/// 
		/// </summary>
		private string _costSubject;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _improvedDate;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _improvedMoney;
		
		/// <summary>
		/// 
		/// </summary>
		private string _departmentId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _mark;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 
		/// </summary>
		private string _id;
		
		/// <summary>
		/// 部门
		/// </summary>
		private Department _department;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PropertyId
		{
			get 
			{
				return this._propertyId;
			}
			set 
			{
				this._propertyId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PropertyName
		{
			get 
			{
				return this._propertyName;
			}
			set 
			{
				this._propertyName = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Specifications
		{
			get 
			{
				return this._specifications;
			}
			set 
			{
				this._specifications = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Position
		{
			get 
			{
				return this._position;
			}
			set 
			{
				this._position = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public double? Quantity
		{
			get 
			{
				return this._quantity;
			}
			set 
			{
				this._quantity = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Unit
		{
			get 
			{
				return this._unit;
			}
			set 
			{
				this._unit = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? ToDate
		{
			get 
			{
				return this._toDate;
			}
			set 
			{
				this._toDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? ObtainRegular
		{
			get 
			{
				return this._obtainRegular;
			}
			set 
			{
				this._obtainRegular = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Often
		{
			get 
			{
				return this._often;
			}
			set 
			{
				this._often = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int? DurableMonths
		{
			get 
			{
				return this._durableMonths;
			}
			set 
			{
				this._durableMonths = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public double? ReserveValue
		{
			get 
			{
				return this._reserveValue;
			}
			set 
			{
				this._reserveValue = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Depreciation
		{
			get 
			{
				return this._depreciation;
			}
			set 
			{
				this._depreciation = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? DepreciationDate
		{
			get 
			{
				return this._depreciationDate;
			}
			set 
			{
				this._depreciationDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? DepreciationMoney
		{
			get 
			{
				return this._depreciationMoney;
			}
			set 
			{
				this._depreciationMoney = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string DepreciationSubject
		{
			get 
			{
				return this._depreciationSubject;
			}
			set 
			{
				this._depreciationSubject = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string RespectiveSubject
		{
			get 
			{
				return this._respectiveSubject;
			}
			set 
			{
				this._respectiveSubject = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string CostSubject
		{
			get 
			{
				return this._costSubject;
			}
			set 
			{
				this._costSubject = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? ImprovedDate
		{
			get 
			{
				return this._improvedDate;
			}
			set 
			{
				this._improvedDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? ImprovedMoney
		{
			get 
			{
				return this._improvedMoney;
			}
			set 
			{
				this._improvedMoney = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string DepartmentId
		{
			get 
			{
				return this._departmentId;
			}
			set 
			{
				this._departmentId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Mark
		{
			get 
			{
				return this._mark;
			}
			set 
			{
				this._mark = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}
	
		/// <summary>
		/// 部门
		/// </summary>
		public virtual Department Department
		{
			get
			{
				return this._department;
			}
			set
			{
				this._department = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PropertyId = "PropertyId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PropertyName = "PropertyName";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Specifications = "Specifications";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Position = "Position";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Quantity = "Quantity";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Unit = "Unit";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ToDate = "ToDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ObtainRegular = "ObtainRegular";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Often = "Often";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_DurableMonths = "DurableMonths";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ReserveValue = "ReserveValue";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Depreciation = "Depreciation";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_DepreciationDate = "DepreciationDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_DepreciationMoney = "DepreciationMoney";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_DepreciationSubject = "DepreciationSubject";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RespectiveSubject = "RespectiveSubject";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_CostSubject = "CostSubject";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ImprovedDate = "ImprovedDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ImprovedMoney = "ImprovedMoney";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_DepartmentId = "DepartmentId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Mark = "Mark";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Id = "Id";
		

		#endregion
	}
}
