//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ClockData.autogenerated.cs
// author: peidun
// create date：2010-4-27 16:23:12
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class ClockData
	{
		#region Data

		/// <summary>
		/// 打卡记录编号
		/// </summary>
		private string _clockDataId;
		
		/// <summary>
		/// 编号
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 插入时间
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 修改时间
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 打卡日期
		/// </summary>
		private DateTime? _empclockdate;
		
		/// <summary>
		/// 打卡时间
		/// </summary>
		private DateTime? _clocktime;
		
		/// <summary>
		/// 上下班
		/// </summary>
		private string _clockType;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _description;
		
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 打卡记录编号
		/// </summary>
		public string ClockDataId
		{
			get 
			{
				return this._clockDataId;
			}
			set 
			{
				this._clockDataId = value;
			}
		}

		/// <summary>
		/// 编号
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 插入时间
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 打卡日期
		/// </summary>
		public DateTime? Empclockdate
		{
			get 
			{
				return this._empclockdate;
			}
			set 
			{
				this._empclockdate = value;
			}
		}

		/// <summary>
		/// 打卡时间
		/// </summary>
		public DateTime? Clocktime
		{
			get 
			{
				return this._clocktime;
			}
			set 
			{
				this._clocktime = value;
			}
		}

		/// <summary>
		/// 上下班
		/// </summary>
		public string ClockType
		{
			get 
			{
				return this._clockType;
			}
			set 
			{
				this._clockType = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Description
		{
			get 
			{
				return this._description;
			}
			set 
			{
				this._description = value;
			}
		}
	
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
			
		}
		/// <summary>
		/// 打卡记录编号
		/// </summary>
		public readonly static string PROPERTY_CLOCKDATAID = "ClockDataId";
		
		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PROPERTY_EMPLOYEEID = "EmployeeId";
		
		/// <summary>
		/// 插入时间
		/// </summary>
		public readonly static string PROPERTY_INSERTTIME = "InsertTime";
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public readonly static string PROPERTY_UPDATETIME = "UpdateTime";
		
		/// <summary>
		/// 打卡日期
		/// </summary>
		public readonly static string PROPERTY_EMPCLOCKDATE = "Empclockdate";
		
		/// <summary>
		/// 打卡时间
		/// </summary>
		public readonly static string PROPERTY_CLOCKTIME = "Clocktime";
		
		/// <summary>
		/// 上下班
		/// </summary>
		public readonly static string PROPERTY_CLOCKTYPE = "ClockType";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_DESCRIPTION = "Description";
		

		#endregion
	}
}
