//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceCJDetail.autogenerated.cs
// author: mayanjun
// create date：2011-06-28 10:01:23
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class InvoiceCJDetail
	{
		#region Data

		/// <summary>
		/// 采购询价单货品编号
		/// </summary>
		private string _invoiceCJDetailId;
		
		/// <summary>
		/// 商品编号
		/// </summary>
		private string _productId;
		
		/// <summary>
		/// 单据编号
		/// </summary>
		private string _invoiceId;
		
		/// <summary>
		/// 采购询价单货品单价
		/// </summary>
		private decimal? _invoiceCJDetailPrice;
		
		/// <summary>
		/// 采购询价单货品数量
		/// </summary>
		private double? _invoiceCJDetailQuantity;
		
		/// <summary>
		/// 采购询价单货品金额
		/// </summary>
		private decimal? _invoiceCJDetailMoney;
		
		/// <summary>
		/// 采购询价单货品备注
		/// </summary>
		private string _invoiceCJDetailNote;
		
		/// <summary>
		/// 单位
		/// </summary>
		private string _invoiceProductUnit;
		
		/// <summary>
		/// 
		/// </summary>
		private int? _inumber;
		
		/// <summary>
		/// 采购报价单
		/// </summary>
		private InvoiceCJ _invoice;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _product;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 采购询价单货品编号
		/// </summary>
		public string InvoiceCJDetailId
		{
			get 
			{
				return this._invoiceCJDetailId;
			}
			set 
			{
				this._invoiceCJDetailId = value;
			}
		}

		/// <summary>
		/// 商品编号
		/// </summary>
		public string ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 单据编号
		/// </summary>
		public string InvoiceId
		{
			get 
			{
				return this._invoiceId;
			}
			set 
			{
				this._invoiceId = value;
			}
		}

		/// <summary>
		/// 采购询价单货品单价
		/// </summary>
		public decimal? InvoiceCJDetailPrice
		{
			get 
			{
				return this._invoiceCJDetailPrice;
			}
			set 
			{
				this._invoiceCJDetailPrice = value;
			}
		}

		/// <summary>
		/// 采购询价单货品数量
		/// </summary>
		public double? InvoiceCJDetailQuantity
		{
			get 
			{
				return this._invoiceCJDetailQuantity;
			}
			set 
			{
				this._invoiceCJDetailQuantity = value;
			}
		}

		/// <summary>
		/// 采购询价单货品金额
		/// </summary>
		public decimal? InvoiceCJDetailMoney
		{
			get 
			{
				return this._invoiceCJDetailMoney;
			}
			set 
			{
				this._invoiceCJDetailMoney = value;
			}
		}

		/// <summary>
		/// 采购询价单货品备注
		/// </summary>
		public string InvoiceCJDetailNote
		{
			get 
			{
				return this._invoiceCJDetailNote;
			}
			set 
			{
				this._invoiceCJDetailNote = value;
			}
		}

		/// <summary>
		/// 单位
		/// </summary>
		public string InvoiceProductUnit
		{
			get 
			{
				return this._invoiceProductUnit;
			}
			set 
			{
				this._invoiceProductUnit = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int? Inumber
		{
			get 
			{
				return this._inumber;
			}
			set 
			{
				this._inumber = value;
			}
		}
	
		/// <summary>
		/// 采购报价单
		/// </summary>
		public virtual InvoiceCJ Invoice
		{
			get
			{
				return this._invoice;
			}
			set
			{
				this._invoice = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
			
		}
		/// <summary>
		/// 采购询价单货品编号
		/// </summary>
		public readonly static string PRO_InvoiceCJDetailId = "InvoiceCJDetailId";
		
		/// <summary>
		/// 商品编号
		/// </summary>
		public readonly static string PRO_ProductId = "ProductId";
		
		/// <summary>
		/// 单据编号
		/// </summary>
		public readonly static string PRO_InvoiceId = "InvoiceId";
		
		/// <summary>
		/// 采购询价单货品单价
		/// </summary>
		public readonly static string PRO_InvoiceCJDetailPrice = "InvoiceCJDetailPrice";
		
		/// <summary>
		/// 采购询价单货品数量
		/// </summary>
		public readonly static string PRO_InvoiceCJDetailQuantity = "InvoiceCJDetailQuantity";
		
		/// <summary>
		/// 采购询价单货品金额
		/// </summary>
		public readonly static string PRO_InvoiceCJDetailMoney = "InvoiceCJDetailMoney";
		
		/// <summary>
		/// 采购询价单货品备注
		/// </summary>
		public readonly static string PRO_InvoiceCJDetailNote = "InvoiceCJDetailNote";
		
		/// <summary>
		/// 单位
		/// </summary>
		public readonly static string PRO_InvoiceProductUnit = "InvoiceProductUnit";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Inumber = "Inumber";
		

		#endregion
	}
}
