//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceXJDetail.autogenerated.cs
// author: mayanjun
// create date：2011-06-28 15:21:29
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class InvoiceXJDetail
	{
		#region Data

		/// <summary>
		/// 销售报价单货品编号
		/// </summary>
		private string _invoiceXJDetailId;
		
		/// <summary>
		/// 主键
		/// </summary>
		private string _primaryKeyId;
		
		/// <summary>
		/// 单据编号
		/// </summary>
		private string _invoiceId;
		
		/// <summary>
		/// 销售报价单货品单价
		/// </summary>
		private decimal? _invoiceXJDetailPrice;
		
		/// <summary>
		/// 销售报价单货品数量
		/// </summary>
		private double? _invoiceXJDetailQuantity;
		
		/// <summary>
		/// 销售报价单货品金额
		/// </summary>
		private decimal? _invoiceXJDetailMoney;
		
		/// <summary>
		/// 销售报价单货品备注
		/// </summary>
		private string _invoiceXJDetailNote;
		
		/// <summary>
		/// 单位
		/// </summary>
		private string _invoiceProductUnit;
		
		/// <summary>
		/// 产品编号
		/// </summary>
		private string _productId;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _isCustomerProduct;
		
		/// <summary>
		/// 
		/// </summary>
		private string _customerId;
		
		/// <summary>
		/// 
		/// </summary>
		private double? _invoiceAllowance;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _islargess;
		
		/// <summary>
		/// 
		/// </summary>
		private int? _inumber;
		
		/// <summary>
		/// 客户
		/// </summary>
		private Customer _customer;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _product;
		/// <summary>
		/// 客户产品
		/// </summary>
		private CustomerProducts _primaryKey;
		/// <summary>
		/// 销售报价单
		/// </summary>
		private InvoiceXJ _invoice;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 销售报价单货品编号
		/// </summary>
		public string InvoiceXJDetailId
		{
			get 
			{
				return this._invoiceXJDetailId;
			}
			set 
			{
				this._invoiceXJDetailId = value;
			}
		}

		/// <summary>
		/// 主键
		/// </summary>
		public string PrimaryKeyId
		{
			get 
			{
				return this._primaryKeyId;
			}
			set 
			{
				this._primaryKeyId = value;
			}
		}

		/// <summary>
		/// 单据编号
		/// </summary>
		public string InvoiceId
		{
			get 
			{
				return this._invoiceId;
			}
			set 
			{
				this._invoiceId = value;
			}
		}

		/// <summary>
		/// 销售报价单货品单价
		/// </summary>
		public decimal? InvoiceXJDetailPrice
		{
			get 
			{
				return this._invoiceXJDetailPrice;
			}
			set 
			{
				this._invoiceXJDetailPrice = value;
			}
		}

		/// <summary>
		/// 销售报价单货品数量
		/// </summary>
		public double? InvoiceXJDetailQuantity
		{
			get 
			{
				return this._invoiceXJDetailQuantity;
			}
			set 
			{
				this._invoiceXJDetailQuantity = value;
			}
		}

		/// <summary>
		/// 销售报价单货品金额
		/// </summary>
		public decimal? InvoiceXJDetailMoney
		{
			get 
			{
				return this._invoiceXJDetailMoney;
			}
			set 
			{
				this._invoiceXJDetailMoney = value;
			}
		}

		/// <summary>
		/// 销售报价单货品备注
		/// </summary>
		public string InvoiceXJDetailNote
		{
			get 
			{
				return this._invoiceXJDetailNote;
			}
			set 
			{
				this._invoiceXJDetailNote = value;
			}
		}

		/// <summary>
		/// 单位
		/// </summary>
		public string InvoiceProductUnit
		{
			get 
			{
				return this._invoiceProductUnit;
			}
			set 
			{
				this._invoiceProductUnit = value;
			}
		}

		/// <summary>
		/// 产品编号
		/// </summary>
		public string ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? IsCustomerProduct
		{
			get 
			{
				return this._isCustomerProduct;
			}
			set 
			{
				this._isCustomerProduct = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string CustomerId
		{
			get 
			{
				return this._customerId;
			}
			set 
			{
				this._customerId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public double? InvoiceAllowance
		{
			get 
			{
				return this._invoiceAllowance;
			}
			set 
			{
				this._invoiceAllowance = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Islargess
		{
			get 
			{
				return this._islargess;
			}
			set 
			{
				this._islargess = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int? Inumber
		{
			get 
			{
				return this._inumber;
			}
			set 
			{
				this._inumber = value;
			}
		}
	
		/// <summary>
		/// 客户
		/// </summary>
		public virtual Customer Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
			
		}
		/// <summary>
		/// 客户产品
		/// </summary>
		public virtual CustomerProducts PrimaryKey
		{
			get
			{
				return this._primaryKey;
			}
			set
			{
				this._primaryKey = value;
			}
			
		}
		/// <summary>
		/// 销售报价单
		/// </summary>
		public virtual InvoiceXJ Invoice
		{
			get
			{
				return this._invoice;
			}
			set
			{
				this._invoice = value;
			}
			
		}
		/// <summary>
		/// 销售报价单货品编号
		/// </summary>
		public readonly static string PRO_InvoiceXJDetailId = "InvoiceXJDetailId";
		
		/// <summary>
		/// 主键
		/// </summary>
		public readonly static string PRO_PrimaryKeyId = "PrimaryKeyId";
		
		/// <summary>
		/// 单据编号
		/// </summary>
		public readonly static string PRO_InvoiceId = "InvoiceId";
		
		/// <summary>
		/// 销售报价单货品单价
		/// </summary>
		public readonly static string PRO_InvoiceXJDetailPrice = "InvoiceXJDetailPrice";
		
		/// <summary>
		/// 销售报价单货品数量
		/// </summary>
		public readonly static string PRO_InvoiceXJDetailQuantity = "InvoiceXJDetailQuantity";
		
		/// <summary>
		/// 销售报价单货品金额
		/// </summary>
		public readonly static string PRO_InvoiceXJDetailMoney = "InvoiceXJDetailMoney";
		
		/// <summary>
		/// 销售报价单货品备注
		/// </summary>
		public readonly static string PRO_InvoiceXJDetailNote = "InvoiceXJDetailNote";
		
		/// <summary>
		/// 单位
		/// </summary>
		public readonly static string PRO_InvoiceProductUnit = "InvoiceProductUnit";
		
		/// <summary>
		/// 产品编号
		/// </summary>
		public readonly static string PRO_ProductId = "ProductId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_IsCustomerProduct = "IsCustomerProduct";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_CustomerId = "CustomerId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceAllowance = "InvoiceAllowance";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Islargess = "Islargess";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Inumber = "Inumber";
		

		#endregion
	}
}
