//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceFK.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:14
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class InvoiceFK
	{
		#region Data

		/// <summary>
		/// 客户编号
		/// </summary>
		private string _customerId;
		
		/// <summary>
		/// 支付方式编号
		/// </summary>
		private string _payMethodId;
		
		/// <summary>
		/// 资金账户编号
		/// </summary>
		private string _accountId;
		
		/// <summary>
		/// 付款单金额
		/// </summary>
		private decimal? _invoiceTotal;
		
		/// <summary>
		/// 资金账户
		/// </summary>
		private Account account;
		/// <summary>
		/// 客户
		/// </summary>
		private Customer customer;
		/// <summary>
		/// 支付方式
		/// </summary>
		private PayMethod payMethod;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 客户编号
		/// </summary>
		public string CustomerId
		{
			get 
			{
				return this._customerId;
			}
			set 
			{
				this._customerId = value;
			}
		}

		/// <summary>
		/// 支付方式编号
		/// </summary>
		public string PayMethodId
		{
			get 
			{
				return this._payMethodId;
			}
			set 
			{
				this._payMethodId = value;
			}
		}

		/// <summary>
		/// 资金账户编号
		/// </summary>
		public string AccountId
		{
			get 
			{
				return this._accountId;
			}
			set 
			{
				this._accountId = value;
			}
		}

		/// <summary>
		/// 付款单金额
		/// </summary>
		public decimal? InvoiceTotal
		{
			get 
			{
				return this._invoiceTotal;
			}
			set 
			{
				this._invoiceTotal = value;
			}
		}
	
		/// <summary>
		/// 资金账户
		/// </summary>
		public virtual Account Account
		{
			get
			{
				return this.account;
			}
			set
			{
				this.account = value;
			}
			
		}
		/// <summary>
		/// 客户
		/// </summary>
		public virtual Customer Customer
		{
			get
			{
				return this.customer;
			}
			set
			{
				this.customer = value;
			}
			
		}
		/// <summary>
		/// 支付方式
		/// </summary>
		public virtual PayMethod PayMethod
		{
			get
			{
				return this.payMethod;
			}
			set
			{
				this.payMethod = value;
			}
			
		}
		/// <summary>
		/// 客户编号
		/// </summary>
		public readonly static string PROPERTY_CUSTOMERID = "CustomerId";
		
		/// <summary>
		/// 支付方式编号
		/// </summary>
		public readonly static string PROPERTY_PAYMETHODID = "PayMethodId";
		
		/// <summary>
		/// 资金账户编号
		/// </summary>
		public readonly static string PROPERTY_ACCOUNTID = "AccountId";
		
		/// <summary>
		/// 付款单金额
		/// </summary>
		public readonly static string PROPERTY_INVOICETOTAL = "InvoiceTotal";
		

		#endregion
	}
}
