//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InvoiceXS.autogenerated.cs
// author: mayanjun
// create date：2010-8-23 9:35:07
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class InvoiceXS
	{
		#region Data

		/// <summary>
		/// 客户编号
		/// </summary>
		private string _customerId;
		
		/// <summary>
		/// 库房编号
		/// </summary>
		private string _depotId;
		
		/// <summary>
		/// 销售订单编号
		/// </summary>
		private string _invoiceXOId;
		
		/// <summary>
		/// 货运公司
		/// </summary>
		private string _transportCompany;
		
		/// <summary>
		/// 产品类型
		/// </summary>
		private int? _productType;
		
		/// <summary>
		/// 
		/// </summary>
		private string _xSCustomerId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _conveyanceMethodId;
		
		/// <summary>
		/// 库房
		/// </summary>
		private Depot _depot;
		/// <summary>
		/// 销售订单
		/// </summary>
		private InvoiceXO _invoiceXO;
		/// <summary>
		/// 货运方式
		/// </summary>
		private ConveyanceMethod _conveyanceMethod;
		/// <summary>
		/// 客户
		/// </summary>
		private Customer _customer;
		/// <summary>
		/// 客户
		/// </summary>
		private Customer _xSCustomer;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 客户编号
		/// </summary>
		public string CustomerId
		{
			get 
			{
				return this._customerId;
			}
			set 
			{
				this._customerId = value;
			}
		}

		/// <summary>
		/// 库房编号
		/// </summary>
		public string DepotId
		{
			get 
			{
				return this._depotId;
			}
			set 
			{
				this._depotId = value;
			}
		}

		/// <summary>
		/// 销售订单编号
		/// </summary>
		public string InvoiceXOId
		{
			get 
			{
				return this._invoiceXOId;
			}
			set 
			{
				this._invoiceXOId = value;
			}
		}

		/// <summary>
		/// 货运公司
		/// </summary>
		public string TransportCompany
		{
			get 
			{
				return this._transportCompany;
			}
			set 
			{
				this._transportCompany = value;
			}
		}

		/// <summary>
		/// 产品类型
		/// </summary>
		public int? ProductType
		{
			get 
			{
				return this._productType;
			}
			set 
			{
				this._productType = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string XSCustomerId
		{
			get 
			{
				return this._xSCustomerId;
			}
			set 
			{
				this._xSCustomerId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ConveyanceMethodId
		{
			get 
			{
				return this._conveyanceMethodId;
			}
			set 
			{
				this._conveyanceMethodId = value;
			}
		}
	
		/// <summary>
		/// 库房
		/// </summary>
		public virtual Depot Depot
		{
			get
			{
				return this._depot;
			}
			set
			{
				this._depot = value;
			}
			
		}
		/// <summary>
		/// 销售订单
		/// </summary>
		public virtual InvoiceXO InvoiceXO
		{
			get
			{
				return this._invoiceXO;
			}
			set
			{
				this._invoiceXO = value;
			}
			
		}
		/// <summary>
		/// 货运方式
		/// </summary>
		public virtual ConveyanceMethod ConveyanceMethod
		{
			get
			{
				return this._conveyanceMethod;
			}
			set
			{
				this._conveyanceMethod = value;
			}
			
		}
		/// <summary>
		/// 客户
		/// </summary>
		public virtual Customer Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
			
		}
		/// <summary>
		/// 客户
		/// </summary>
		public virtual Customer XSCustomer
		{
			get
			{
				return this._xSCustomer;
			}
			set
			{
				this._xSCustomer = value;
			}
			
		}
		/// <summary>
		/// 客户编号
		/// </summary>
		public readonly static string PROPERTY_CUSTOMERID = "CustomerId";
		
		/// <summary>
		/// 库房编号
		/// </summary>
		public readonly static string PROPERTY_DEPOTID = "DepotId";
		
		/// <summary>
		/// 销售订单编号
		/// </summary>
		public readonly static string PROPERTY_INVOICEXOID = "InvoiceXOId";
		
		/// <summary>
		/// 货运公司
		/// </summary>
		public readonly static string PROPERTY_TRANSPORTCOMPANY = "TransportCompany";
		
		/// <summary>
		/// 产品类型
		/// </summary>
		public readonly static string PROPERTY_PRODUCTTYPE = "ProductType";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_XSCUSTOMERID = "XSCustomerId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_CONVEYANCEMETHODID = "ConveyanceMethodId";
		

		#endregion
	}
}
