//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ManProcedure.autogenerated.cs
// author: mayanjun
// create date：2011-3-23 15:08:17
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class ManProcedure
	{
		#region Data

		/// <summary>
		/// Attribute_743
		/// </summary>
		private string _manProcedureId;
		
		/// <summary>
		/// 清单编号
		/// </summary>
		private string _bomId;
		
		/// <summary>
		/// Procedureid
		/// </summary>
		private string _proceduresId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _techonlogyHeaderId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 
		/// </summary>
		private string _customerId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 制成品
		/// </summary>
		private string _madeProductId;
		
		/// <summary>
		/// 客户
		/// </summary>
		private Customer _customer;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _madeProduct;
		/// <summary>
		/// Bom母件信息
		/// </summary>
		private BomParentPartInfo _bom;
		/// <summary>
		/// 标准工序
		/// </summary>
		private Procedures _procedures;
		/// <summary>
		/// 工艺路线头
		/// </summary>
		private TechonlogyHeader _techonlogyHeader;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// Attribute_743
		/// </summary>
		public string ManProcedureId
		{
			get 
			{
				return this._manProcedureId;
			}
			set 
			{
				this._manProcedureId = value;
			}
		}

		/// <summary>
		/// 清单编号
		/// </summary>
		public string BomId
		{
			get 
			{
				return this._bomId;
			}
			set 
			{
				this._bomId = value;
			}
		}

		/// <summary>
		/// Procedureid
		/// </summary>
		public string ProceduresId
		{
			get 
			{
				return this._proceduresId;
			}
			set 
			{
				this._proceduresId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string TechonlogyHeaderId
		{
			get 
			{
				return this._techonlogyHeaderId;
			}
			set 
			{
				this._techonlogyHeaderId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string CustomerId
		{
			get 
			{
				return this._customerId;
			}
			set 
			{
				this._customerId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 制成品
		/// </summary>
		public string MadeProductId
		{
			get 
			{
				return this._madeProductId;
			}
			set 
			{
				this._madeProductId = value;
			}
		}
	
		/// <summary>
		/// 客户
		/// </summary>
		public virtual Customer Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product MadeProduct
		{
			get
			{
				return this._madeProduct;
			}
			set
			{
				this._madeProduct = value;
			}
			
		}
		/// <summary>
		/// Bom母件信息
		/// </summary>
		public virtual BomParentPartInfo Bom
		{
			get
			{
				return this._bom;
			}
			set
			{
				this._bom = value;
			}
			
		}
		/// <summary>
		/// 标准工序
		/// </summary>
		public virtual Procedures Procedures
		{
			get
			{
				return this._procedures;
			}
			set
			{
				this._procedures = value;
			}
			
		}
		/// <summary>
		/// 工艺路线头
		/// </summary>
		public virtual TechonlogyHeader TechonlogyHeader
		{
			get
			{
				return this._techonlogyHeader;
			}
			set
			{
				this._techonlogyHeader = value;
			}
			
		}
		/// <summary>
		/// Attribute_743
		/// </summary>
		public readonly static string PRO_ManProcedureId = "ManProcedureId";
		
		/// <summary>
		/// 清单编号
		/// </summary>
		public readonly static string PRO_BomId = "BomId";
		
		/// <summary>
		/// Procedureid
		/// </summary>
		public readonly static string PRO_ProceduresId = "ProceduresId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_TechonlogyHeaderId = "TechonlogyHeaderId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_CustomerId = "CustomerId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 制成品
		/// </summary>
		public readonly static string PRO_MadeProductId = "MadeProductId";
		

		#endregion
	}
}
