//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：OverTime.autogenerated.cs
// author: peidun
// create date：2010-3-20 11:59:57
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class OverTime
    {
        #region Data

        /// <summary>
        /// 加班编号
        /// </summary>
        private string _overTimeId;

        /// <summary>
        /// 编号
        /// </summary>
        private string _employeeId;

        /// <summary>
        /// 插入时间
        /// </summary>
        private DateTime? _insertTime;

        /// <summary>
        /// 修改时间
        /// </summary>
        private DateTime? _updateTime;

        /// <summary>
        /// 日期
        /// </summary>
        private DateTime _dueDate;

        /// <summary>
        /// 加班时间
        /// </summary>
        private double _eoverTime;

        /// <summary>
        /// 加班薪酬
        /// </summary>
        private decimal _overTimeFee;

        /// <summary>
        /// 加班奖金
        /// </summary>
        private decimal _overTimeBonus;

        /// <summary>
        /// 是否节假日
        /// </summary>
        private bool _isHoliday;

        /// <summary>
        /// 加班记录
        /// </summary>
        private string _note;

        /// <summary>
        /// 员工
        /// </summary>
        private Employee _employee;

        #endregion

        #region Properties

        /// <summary>
        /// 加班编号
        /// </summary>
        public string OverTimeId
        {
            get
            {
                return this._overTimeId;
            }
            set
            {
                this._overTimeId = value;
            }
        }

        /// <summary>
        /// 编号
        /// </summary>
        public string EmployeeId
        {
            get
            {
                return this._employeeId;
            }
            set
            {
                this._employeeId = value;
            }
        }

        /// <summary>
        /// 插入时间
        /// </summary>
        public DateTime? InsertTime
        {
            get
            {
                return this._insertTime;
            }
            set
            {
                this._insertTime = value;
            }
        }

        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? UpdateTime
        {
            get
            {
                return this._updateTime;
            }
            set
            {
                this._updateTime = value;
            }
        }

        /// <summary>
        /// 日期
        /// </summary>
        public DateTime DueDate
        {
            get
            {
                return this._dueDate;
            }
            set
            {
                this._dueDate = value;
            }
        }

        /// <summary>
        /// 加班时间
        /// </summary>
        public double EoverTime
        {
            get
            {
                return this._eoverTime;
            }
            set
            {
                this._eoverTime = value;
            }
        }

        /// <summary>
        /// 加班薪酬
        /// </summary>
        public decimal OverTimeFee
        {
            get
            {
                return this._overTimeFee;
            }
            set
            {
                this._overTimeFee = value;
            }
        }

        /// <summary>
        /// 加班奖金
        /// </summary>
        public decimal OverTimeBonus
        {
            get
            {
                return this._overTimeBonus;
            }
            set
            {
                this._overTimeBonus = value;
            }
        }

        /// <summary>
        /// 是否节假日
        /// </summary>
        public bool IsHoliday
        {
            get
            {
                return this._isHoliday;
            }
            set
            {
                this._isHoliday = value;
            }
        }

        /// <summary>
        /// 加班记录
        /// </summary>
        public string Note
        {
            get
            {
                return this._note;
            }
            set
            {
                this._note = value;
            }
        }

        /// <summary>
        /// 员工
        /// </summary>
        public virtual Employee Employee
        {
            get
            {
                return this._employee;
            }
            set
            {
                this._employee = value;
            }

        }
        /// <summary>
        /// 加班编号
        /// </summary>
        public readonly static string PROPERTY_OVERTIMEID = "OverTimeId";

        /// <summary>
        /// 编号
        /// </summary>
        public readonly static string PROPERTY_EMPLOYEEID = "EmployeeId";

        /// <summary>
        /// 插入时间
        /// </summary>
        public readonly static string PROPERTY_INSERTTIME = "InsertTime";

        /// <summary>
        /// 修改时间
        /// </summary>
        public readonly static string PROPERTY_UPDATETIME = "UpdateTime";

        /// <summary>
        /// 日期
        /// </summary>
        public readonly static string PROPERTY_DUEDATE = "DueDate";

        /// <summary>
        /// 加班时间
        /// </summary>
        public readonly static string PROPERTY_EOVERTIME = "EoverTime";

        /// <summary>
        /// 加班薪酬
        /// </summary>
        public readonly static string PROPERTY_OVERTIMEFEE = "OverTimeFee";

        /// <summary>
        /// 加班奖金
        /// </summary>
        public readonly static string PROPERTY_OVERTIMEBONUS = "OverTimeBonus";

        /// <summary>
        /// 是否节假日
        /// </summary>
        public readonly static string PROPERTY_ISHOLIDAY = "IsHoliday";

        /// <summary>
        /// 加班记录
        /// </summary>
        public readonly static string PROPERTY_NOTE = "Note";


        #endregion
    }
}
