//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PayMethod.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:15
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PayMethod
	{
		#region Data

		/// <summary>
		/// 编号
		/// </summary>
		private string _id;
		
		/// <summary>
		/// 支付方式编号
		/// </summary>
		private string _payMethodId;
		
		/// <summary>
		/// 插入时间
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 修改时间
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 支付方式名称
		/// </summary>
		private string _payMethodName;
		
		/// <summary>
		/// 支付方式说明
		/// </summary>
		private string _payMethodDescription;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 编号
		/// </summary>
		public string Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}

		/// <summary>
		/// 支付方式编号
		/// </summary>
		public string PayMethodId
		{
			get 
			{
				return this._payMethodId;
			}
			set 
			{
				this._payMethodId = value;
			}
		}

		/// <summary>
		/// 插入时间
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 支付方式名称
		/// </summary>
		public string PayMethodName
		{
			get 
			{
				return this._payMethodName;
			}
			set 
			{
				this._payMethodName = value;
			}
		}

		/// <summary>
		/// 支付方式说明
		/// </summary>
		public string PayMethodDescription
		{
			get 
			{
				return this._payMethodDescription;
			}
			set 
			{
				this._payMethodDescription = value;
			}
		}
	
		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PROPERTY_ID = "Id";
		
		/// <summary>
		/// 支付方式编号
		/// </summary>
		public readonly static string PROPERTY_PAYMETHODID = "PayMethodId";
		
		/// <summary>
		/// 插入时间
		/// </summary>
		public readonly static string PROPERTY_INSERTTIME = "InsertTime";
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public readonly static string PROPERTY_UPDATETIME = "UpdateTime";
		
		/// <summary>
		/// 支付方式名称
		/// </summary>
		public readonly static string PROPERTY_PAYMETHODNAME = "PayMethodName";
		
		/// <summary>
		/// 支付方式说明
		/// </summary>
		public readonly static string PROPERTY_PAYMETHODDESCRIPTION = "PayMethodDescription";
		

		#endregion
	}
}
