//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：processrecord.autogenerated.cs
// author: peidun
// create date：2009-12-11 16:14:14
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class processrecord
	{
		#region Data

		/// <summary>
		/// 编号
		/// </summary>
		private string _processrecordID;
		
		/// <summary>
		/// 过程编号
		/// </summary>
		private string _processId;
		
		/// <summary>
		/// 插入时间
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 修改时间
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 过程结束时间
		/// </summary>
		private DateTime? _endtime;
		
		/// <summary>
		/// 处理状态
		/// </summary>
		private string _dealstate;
		
		/// <summary>
		/// 催办信息
		/// </summary>
		private string _clewinfo;
		
		/// <summary>
		/// 过程表
		/// </summary>
		private process _process;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 编号
		/// </summary>
		public string processrecordID
		{
			get 
			{
				return this._processrecordID;
			}
			set 
			{
				this._processrecordID = value;
			}
		}

		/// <summary>
		/// 过程编号
		/// </summary>
		public string processId
		{
			get 
			{
				return this._processId;
			}
			set 
			{
				this._processId = value;
			}
		}

		/// <summary>
		/// 插入时间
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 过程结束时间
		/// </summary>
		public DateTime? endtime
		{
			get 
			{
				return this._endtime;
			}
			set 
			{
				this._endtime = value;
			}
		}

		/// <summary>
		/// 处理状态
		/// </summary>
		public string dealstate
		{
			get 
			{
				return this._dealstate;
			}
			set 
			{
				this._dealstate = value;
			}
		}

		/// <summary>
		/// 催办信息
		/// </summary>
		public string clewinfo
		{
			get 
			{
				return this._clewinfo;
			}
			set 
			{
				this._clewinfo = value;
			}
		}
	
		/// <summary>
		/// 过程表
		/// </summary>
		public virtual process process
		{
			get
			{
				return this._process;
			}
			set
			{
				this._process = value;
			}
			
		}
		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PROPERTY_PROCESSRECORDID = "processrecordID";
		
		/// <summary>
		/// 过程编号
		/// </summary>
		public readonly static string PROPERTY_PROCESSID = "processId";
		
		/// <summary>
		/// 插入时间
		/// </summary>
		public readonly static string PROPERTY_INSERTTIME = "InsertTime";
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public readonly static string PROPERTY_UPDATETIME = "UpdateTime";
		
		/// <summary>
		/// 过程结束时间
		/// </summary>
		public readonly static string PROPERTY_ENDTIME = "endtime";
		
		/// <summary>
		/// 处理状态
		/// </summary>
		public readonly static string PROPERTY_DEALSTATE = "dealstate";
		
		/// <summary>
		/// 催办信息
		/// </summary>
		public readonly static string PROPERTY_CLEWINFO = "clewinfo";
		

		#endregion
	}
}
