//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProduceStatistics.autogenerated.cs
// author: mayanjun
// create date：2011-07-04 11:24:16
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class ProduceStatistics
	{
		#region Data

		/// <summary>
		/// 主键
		/// </summary>
		private string _produceStatisticsId;
		
		/// <summary>
		/// 加工单
		/// </summary>
		private string _pronoteHeaderID;
		
		/// <summary>
		/// 主键编号
		/// </summary>
		private string _proceduresId;
		
		/// <summary>
		/// 描述
		/// </summary>
		private string _description;
		
		/// <summary>
		/// 操作员
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 插入时间
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 修改时间
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 日期
		/// </summary>
		private DateTime? _produceStatisticsDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _workHouseId;
		
		/// <summary>
		/// 0:射出 1:质检 2:组装
		/// </summary>
		private int? _produceStatisticsType;
		
		/// <summary>
		/// 生产通知头
		/// </summary>
		private PronoteHeader _pronoteHeader;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee;
		/// <summary>
		/// 标准工序
		/// </summary>
		private Procedures _procedures;
		/// <summary>
		/// 工作中心
		/// </summary>
		private WorkHouse _workHouse;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 主键
		/// </summary>
		public string ProduceStatisticsId
		{
			get 
			{
				return this._produceStatisticsId;
			}
			set 
			{
				this._produceStatisticsId = value;
			}
		}

		/// <summary>
		/// 加工单
		/// </summary>
		public string PronoteHeaderID
		{
			get 
			{
				return this._pronoteHeaderID;
			}
			set 
			{
				this._pronoteHeaderID = value;
			}
		}

		/// <summary>
		/// 主键编号
		/// </summary>
		public string ProceduresId
		{
			get 
			{
				return this._proceduresId;
			}
			set 
			{
				this._proceduresId = value;
			}
		}

		/// <summary>
		/// 描述
		/// </summary>
		public string Description
		{
			get 
			{
				return this._description;
			}
			set 
			{
				this._description = value;
			}
		}

		/// <summary>
		/// 操作员
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 插入时间
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 日期
		/// </summary>
		public DateTime? ProduceStatisticsDate
		{
			get 
			{
				return this._produceStatisticsDate;
			}
			set 
			{
				this._produceStatisticsDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string WorkHouseId
		{
			get 
			{
				return this._workHouseId;
			}
			set 
			{
				this._workHouseId = value;
			}
		}

		/// <summary>
		/// 0:射出 1:质检 2:组装
		/// </summary>
		public int? ProduceStatisticsType
		{
			get 
			{
				return this._produceStatisticsType;
			}
			set 
			{
				this._produceStatisticsType = value;
			}
		}
	
		/// <summary>
		/// 生产通知头
		/// </summary>
		public virtual PronoteHeader PronoteHeader
		{
			get
			{
				return this._pronoteHeader;
			}
			set
			{
				this._pronoteHeader = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
			
		}
		/// <summary>
		/// 标准工序
		/// </summary>
		public virtual Procedures Procedures
		{
			get
			{
				return this._procedures;
			}
			set
			{
				this._procedures = value;
			}
			
		}
		/// <summary>
		/// 工作中心
		/// </summary>
		public virtual WorkHouse WorkHouse
		{
			get
			{
				return this._workHouse;
			}
			set
			{
				this._workHouse = value;
			}
			
		}
		/// <summary>
		/// 主键
		/// </summary>
		public readonly static string PRO_ProduceStatisticsId = "ProduceStatisticsId";
		
		/// <summary>
		/// 加工单
		/// </summary>
		public readonly static string PRO_PronoteHeaderID = "PronoteHeaderID";
		
		/// <summary>
		/// 主键编号
		/// </summary>
		public readonly static string PRO_ProceduresId = "ProceduresId";
		
		/// <summary>
		/// 描述
		/// </summary>
		public readonly static string PRO_Description = "Description";
		
		/// <summary>
		/// 操作员
		/// </summary>
		public readonly static string PRO_EmployeeId = "EmployeeId";
		
		/// <summary>
		/// 插入时间
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 日期
		/// </summary>
		public readonly static string PRO_ProduceStatisticsDate = "ProduceStatisticsDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_WorkHouseId = "WorkHouseId";
		
		/// <summary>
		/// 0:射出 1:质检 2:组装
		/// </summary>
		public readonly static string PRO_ProduceStatisticsType = "ProduceStatisticsType";
		

		#endregion
	}
}
