//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：ProductMouldDetail.autogenerated.cs
// author: mayanjun
// create date：2010-10-4 11:11:54
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class ProductMouldDetail
	{
		#region Data

		/// <summary>
		/// 编号
		/// </summary>
		private string _productMouldDetailId;
		
		/// <summary>
		/// 模板编号
		/// </summary>
		private string _mouldId;
		
		/// <summary>
		/// 商品编号
		/// </summary>
		private string _productId;
		
		/// <summary>
		/// 说明
		/// </summary>
		private string _description;
		
		/// <summary>
		/// 产品
		/// </summary>
		private Product _product;
		/// <summary>
		/// 产品模具
		/// </summary>
		private ProductMould _mould;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 编号
		/// </summary>
		public string ProductMouldDetailId
		{
			get 
			{
				return this._productMouldDetailId;
			}
			set 
			{
				this._productMouldDetailId = value;
			}
		}

		/// <summary>
		/// 模板编号
		/// </summary>
		public string MouldId
		{
			get 
			{
				return this._mouldId;
			}
			set 
			{
				this._mouldId = value;
			}
		}

		/// <summary>
		/// 商品编号
		/// </summary>
		public string ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 说明
		/// </summary>
		public string Description
		{
			get 
			{
				return this._description;
			}
			set 
			{
				this._description = value;
			}
		}
	
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
			
		}
		/// <summary>
		/// 产品模具
		/// </summary>
		public virtual ProductMould Mould
		{
			get
			{
				return this._mould;
			}
			set
			{
				this._mould = value;
			}
			
		}
		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PROPERTY_PRODUCTMOULDDETAILID = "ProductMouldDetailId";
		
		/// <summary>
		/// 模板编号
		/// </summary>
		public readonly static string PROPERTY_MOULDID = "MouldId";
		
		/// <summary>
		/// 商品编号
		/// </summary>
		public readonly static string PROPERTY_PRODUCTID = "ProductId";
		
		/// <summary>
		/// 说明
		/// </summary>
		public readonly static string PROPERTY_DESCRIPTION = "Description";
		

		#endregion
	}
}
