//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PronoteMachine.autogenerated.cs
// author: mayanjun
// create date：2010-10-12 16:43:39
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PronoteMachine
	{
		#region Data

		/// <summary>
		/// 编号
		/// </summary>
		private string _pronoteMachineId;
		
		/// <summary>
		/// 工作中心编号
		/// </summary>
		private string _workHouseId;
		
		/// <summary>
		/// 机器序号
		/// </summary>
		private string _id;
		
		/// <summary>
		/// 机器名称
		/// </summary>
		private string _pronoteMachineName;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _isChecked;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productUnitId;
		
		/// <summary>
		/// 
		/// </summary>
		private double? _quantity;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _machineTotal;
		
		/// <summary>
		/// 
		/// </summary>
		private double? _machinePower;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _machineState;
		
		/// <summary>
		/// 工作中心
		/// </summary>
		private WorkHouse _workHouse;
		/// <summary>
		/// 单位
		/// </summary>
		private ProductUnit _productUnit;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 编号
		/// </summary>
		public string PronoteMachineId
		{
			get 
			{
				return this._pronoteMachineId;
			}
			set 
			{
				this._pronoteMachineId = value;
			}
		}

		/// <summary>
		/// 工作中心编号
		/// </summary>
		public string WorkHouseId
		{
			get 
			{
				return this._workHouseId;
			}
			set 
			{
				this._workHouseId = value;
			}
		}

		/// <summary>
		/// 机器序号
		/// </summary>
		public string Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}

		/// <summary>
		/// 机器名称
		/// </summary>
		public string PronoteMachineName
		{
			get 
			{
				return this._pronoteMachineName;
			}
			set 
			{
				this._pronoteMachineName = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? IsChecked
		{
			get 
			{
				return this._isChecked;
			}
			set 
			{
				this._isChecked = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductUnitId
		{
			get 
			{
				return this._productUnitId;
			}
			set 
			{
				this._productUnitId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public double? Quantity
		{
			get 
			{
				return this._quantity;
			}
			set 
			{
				this._quantity = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? MachineTotal
		{
			get 
			{
				return this._machineTotal;
			}
			set 
			{
				this._machineTotal = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public double? MachinePower
		{
			get 
			{
				return this._machinePower;
			}
			set 
			{
				this._machinePower = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? MachineState
		{
			get 
			{
				return this._machineState;
			}
			set 
			{
				this._machineState = value;
			}
		}
	
		/// <summary>
		/// 工作中心
		/// </summary>
		public virtual WorkHouse WorkHouse
		{
			get
			{
				return this._workHouse;
			}
			set
			{
				this._workHouse = value;
			}
			
		}
		/// <summary>
		/// 单位
		/// </summary>
		public virtual ProductUnit ProductUnit
		{
			get
			{
				return this._productUnit;
			}
			set
			{
				this._productUnit = value;
			}
			
		}
		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PROPERTY_PRONOTEMACHINEID = "PronoteMachineId";
		
		/// <summary>
		/// 工作中心编号
		/// </summary>
		public readonly static string PROPERTY_WORKHOUSEID = "WorkHouseId";
		
		/// <summary>
		/// 机器序号
		/// </summary>
		public readonly static string PROPERTY_ID = "Id";
		
		/// <summary>
		/// 机器名称
		/// </summary>
		public readonly static string PROPERTY_PRONOTEMACHINENAME = "PronoteMachineName";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_INSERTTIME = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_UPDATETIME = "UpdateTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_ISCHECKED = "IsChecked";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_PRODUCTUNITID = "ProductUnitId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_QUANTITY = "Quantity";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_MACHINETOTAL = "MachineTotal";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_MACHINEPOWER = "MachinePower";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_MACHINESTATE = "MachineState";
		

		#endregion
	}
}
