//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：UnitGroup.autogenerated.cs
// author: peidun
// create date：2009-10-13 上午 11:45:18
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class UnitGroup
	{
		#region Data

		/// <summary>
		/// 编号
		/// </summary>
		private string _id;
		
		/// <summary>
		/// 单位组编号
		/// </summary>
		private string _unitGroupId;
		
		/// <summary>
		/// 插入时间
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 修改时间
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 单位组名称
		/// </summary>
		private string _unitGroupName;
		
		/// <summary>
		/// 组类别
		/// </summary>
		private string _unitGroupType;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 编号
		/// </summary>
		public string Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}

		/// <summary>
		/// 单位组编号
		/// </summary>
		public string UnitGroupId
		{
			get 
			{
				return this._unitGroupId;
			}
			set 
			{
				this._unitGroupId = value;
			}
		}

		/// <summary>
		/// 插入时间
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 单位组名称
		/// </summary>
		public string UnitGroupName
		{
			get 
			{
				return this._unitGroupName;
			}
			set 
			{
				this._unitGroupName = value;
			}
		}

		/// <summary>
		/// 组类别
		/// </summary>
		public string UnitGroupType
		{
			get 
			{
				return this._unitGroupType;
			}
			set 
			{
				this._unitGroupType = value;
			}
		}
	
		/// <summary>
		/// 编号
		/// </summary>
		public readonly static string PROPERTY_ID = "Id";
		
		/// <summary>
		/// 单位组编号
		/// </summary>
		public readonly static string PROPERTY_UNITGROUPID = "UnitGroupId";
		
		/// <summary>
		/// 插入时间
		/// </summary>
		public readonly static string PROPERTY_INSERTTIME = "InsertTime";
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public readonly static string PROPERTY_UPDATETIME = "UpdateTime";
		
		/// <summary>
		/// 单位组名称
		/// </summary>
		public readonly static string PROPERTY_UNITGROUPNAME = "UnitGroupName";
		
		/// <summary>
		/// 组类别
		/// </summary>
		public readonly static string PROPERTY_UNITGROUPTYPE = "UnitGroupType";
		

		#endregion
	}
}
