//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：wfrecordlog.autogenerated.cs
// author: peidun
// create date：2009-12-11 16:14:14
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class wfrecordlog
	{
		#region Data

		/// <summary>
		/// 记录编号
		/// </summary>
		private string _wfrecordlogid;
		
		/// <summary>
		/// 工作流执行记录编号
		/// </summary>
		private string _wfrecordId;
		
		/// <summary>
		/// 插入时间
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 修改时间
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 操作编号
		/// </summary>
		private string _logid;
		
		/// <summary>
		/// 记录类型
		/// </summary>
		private string _logtype;
		
		/// <summary>
		/// 修改后编号
		/// </summary>
		private string _updatelogid;
		
		/// <summary>
		/// 
   
		/// </summary>
		private wfrecord _wfrecord;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 记录编号
		/// </summary>
		public string wfrecordlogid
		{
			get 
			{
				return this._wfrecordlogid;
			}
			set 
			{
				this._wfrecordlogid = value;
			}
		}

		/// <summary>
		/// 工作流执行记录编号
		/// </summary>
		public string wfrecordId
		{
			get 
			{
				return this._wfrecordId;
			}
			set 
			{
				this._wfrecordId = value;
			}
		}

		/// <summary>
		/// 插入时间
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 操作编号
		/// </summary>
		public string logid
		{
			get 
			{
				return this._logid;
			}
			set 
			{
				this._logid = value;
			}
		}

		/// <summary>
		/// 记录类型
		/// </summary>
		public string logtype
		{
			get 
			{
				return this._logtype;
			}
			set 
			{
				this._logtype = value;
			}
		}

		/// <summary>
		/// 修改后编号
		/// </summary>
		public string updatelogid
		{
			get 
			{
				return this._updatelogid;
			}
			set 
			{
				this._updatelogid = value;
			}
		}
	
		/// <summary>
		/// 
   
		/// </summary>
		public virtual wfrecord wfrecord
		{
			get
			{
				return this._wfrecord;
			}
			set
			{
				this._wfrecord = value;
			}
			
		}
		/// <summary>
		/// 记录编号
		/// </summary>
		public readonly static string PROPERTY_WFRECORDLOGID = "wfrecordlogid";
		
		/// <summary>
		/// 工作流执行记录编号
		/// </summary>
		public readonly static string PROPERTY_WFRECORDID = "wfrecordId";
		
		/// <summary>
		/// 插入时间
		/// </summary>
		public readonly static string PROPERTY_INSERTTIME = "InsertTime";
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public readonly static string PROPERTY_UPDATETIME = "UpdateTime";
		
		/// <summary>
		/// 操作编号
		/// </summary>
		public readonly static string PROPERTY_LOGID = "logid";
		
		/// <summary>
		/// 记录类型
		/// </summary>
		public readonly static string PROPERTY_LOGTYPE = "logtype";
		
		/// <summary>
		/// 修改后编号
		/// </summary>
		public readonly static string PROPERTY_UPDATELOGID = "updatelogid";
		

		#endregion
	}
}
