//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：Workflow.autogenerated.cs
// author: mayanjun
// create date：2010-9-1 14:55:14
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class Workflow
	{
		#region Data

		/// <summary>
		/// 工作流编号
		/// </summary>
		private string _workflowId;
		
		/// <summary>
		/// 表单编号
		/// </summary>
		private string _tablesID;
		
		/// <summary>
		/// 插入时间
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 修改时间
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 工作流名称
		/// </summary>
		private string _workflowname;
		
		/// <summary>
		/// 工作流的描述
		/// </summary>
		private string _description;
		
		/// <summary>
		/// 
		/// </summary>
		private string _id;
		
		/// <summary>
		/// 表单
		/// </summary>
		private Tables _tables;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 工作流编号
		/// </summary>
		public string WorkflowId
		{
			get 
			{
				return this._workflowId;
			}
			set 
			{
				this._workflowId = value;
			}
		}

		/// <summary>
		/// 表单编号
		/// </summary>
		public string TablesID
		{
			get 
			{
				return this._tablesID;
			}
			set 
			{
				this._tablesID = value;
			}
		}

		/// <summary>
		/// 插入时间
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 修改时间
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 工作流名称
		/// </summary>
		public string workflowname
		{
			get 
			{
				return this._workflowname;
			}
			set 
			{
				this._workflowname = value;
			}
		}

		/// <summary>
		/// 工作流的描述
		/// </summary>
		public string description
		{
			get 
			{
				return this._description;
			}
			set 
			{
				this._description = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Id
		{
			get 
			{
				return this._id;
			}
			set 
			{
				this._id = value;
			}
		}
	
		/// <summary>
		/// 表单
		/// </summary>
		public virtual Tables Tables
		{
			get
			{
				return this._tables;
			}
			set
			{
				this._tables = value;
			}
			
		}
		/// <summary>
		/// 工作流编号
		/// </summary>
		public readonly static string PROPERTY_WORKFLOWID = "WorkflowId";
		
		/// <summary>
		/// 表单编号
		/// </summary>
		public readonly static string PROPERTY_TABLESID = "TablesID";
		
		/// <summary>
		/// 插入时间
		/// </summary>
		public readonly static string PROPERTY_INSERTTIME = "InsertTime";
		
		/// <summary>
		/// 修改时间
		/// </summary>
		public readonly static string PROPERTY_UPDATETIME = "UpdateTime";
		
		/// <summary>
		/// 工作流名称
		/// </summary>
		public readonly static string PROPERTY_WORKFLOWNAME = "workflowname";
		
		/// <summary>
		/// 工作流的描述
		/// </summary>
		public readonly static string PROPERTY_DESCRIPTION = "description";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PROPERTY_ID = "Id";
		

		#endregion
	}
}
